### ISSUE TITLE
Clarification on isSiteLicensed property

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#102]
Just to clarify, if isSiteLicensed is set to true does that mean existing customers that have already activated will get a prompt to activate again?

I'd like to turn this on although only if existing customers will not have to enter their license keys again.

**Comment by avalore** [comment]
Currently, that is the case (when turned on, existing customers will need to re-enter details). I'll add a ticket to transfer existing licences to site licences so this isn't the case.

**Comment by tunabelly** [comment]
Ok thanks for the extra info.
