### ISSUE TITLE
PaddleToolKit showing messages on first launch

### ISSUE THREAD

**Issue by charlieMonroe** [PaddleHQ/Mac-Framework#103]
Hi,

I've been using the `PaddleToolKit` as such:

```
let toolkit = PaddleToolKit.sharedInstance()
toolkit.presentHappinessView(withSchedule: "5 days", message: nil)
toolkit.presentEmailSubscribePrompt(withSchedule: "10 days", message: nil)
toolkit.presentFeedbackView(withSchedule: "20 days", message: nil, label: "help")
```

Unfortunately, there are many, many people reporting (and I've just tried it myself) that all 3 get displayed on the first launch! This is a very bad user experience where the user gets bombarded by one message after another.

I've tested this in a Guest user account which must be completely clean since everything gets wiped out after sign out.

**Comment by avalore** [comment]
Hi, we've found the cause of this and will get a fix released asap.

**Comment by charlieMonroe** [comment]
Thanks, glad to hear that!

**Comment by avalore** [comment]
`3.0.13` resolves this issue
