### ISSUE TITLE
Customer's license reverted back to trial

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#106]
I have a customer who I now have to give a refund to because his license for TG Pro suddenly went back to trial mode. I can't get anymore information from him since he's quite upset although he did provide two console entries that got written out on app launch:

20.09.16 0:07:11,190 TG Pro[465]: tcp_connection_destination_perform_socket_connect 2 connectx to 104.45.136.42:443@0 failed: [64] Host is down 
20.09.16 0:07:11,613 TG Pro[465]: not verified: Product not activated

The most important piece of information is that he blocked all network connections to/from TG Pro so it can no longer connect with Paddle. However, the code is setup now to only remove the license iff it connects to Paddle and the license is invalid.

Any ideas of what's going on and how it might be avoided in a future update?

**Comment by avalore** [comment]
v3.0.10 has fixed this issue. There was a scenario that produced a false positive with only destroying licence on verification fail.

**Comment by tunabelly** [comment]
Thank you for the timely fix - it's just in time for a TG Pro update so hopefully this fixes it for good!
