### ISSUE TITLE
Feature Request: Add "Deactivate License" button to License Info Window

### ISSUE THREAD

**Issue by tjosten** [PaddleHQ/Mac-Framework#107]
We have the functionality to deactivate a license to reduce the number of activated licenses with `[[Paddle sharedInstance] deactivateLicence]`, which is great. However, without implementing a custom UI, this cannot be used by a customer. How about adding a button to the left side of the License Info Window, which is being shown then the app is licensed and we call `[[Paddle sharedInstance] showLicencing]`? Make it configurable if you want. That way, we can easily offer the user the functionality to
- get information about the license used to activate the app
- deactivate a license when a Mac is being sold or given back to the company

What do you think?

**Comment by avalore** [comment]
@tjosten Good spot and nice idea - we'll look at including this

**Comment by involer** [comment]
v3.0.15 fixes this: 

> Added "Deactivate" button to existing/activated licence view. Enabled setting `willShowDeactivateLicenceButton` to `YES`
