### ISSUE TITLE
Crash on call to -startLicencing:

### ISSUE THREAD

**Issue by nightbirdsevolve** [PaddleHQ/Mac-Framework#108]
Paddle (NonApp Store) SDK v3.0.10.
`com.apple.NSURLConnectionLoader` crashes the app, after a call to `-startLicensing`. Just add an 'all exceptions' breakpoint and you'll experience it. 
![screen shot 2016-09-30 at 13 13 06](https://cloud.githubusercontent.com/assets/528537/18990099/0a4db820-8710-11e6-8fbd-1ceae0511e33.png)

Crash occurs on both sierra & el cap, running either xc 8 / 7.

**Comment by avalore** [comment]
On research this looks to be a bug in NSURLConnection (we're still using older style connections to support some older OS versions). 

Fortunately it doesn't cause a crash. This same issue has been raised in other frameworks.
https://github.com/AFNetworking/AFNetworking/issues/501
https://www.parse.com/questions/multiple-exceptions-with-comapplensurlconnectionloader
