### ISSUE TITLE
Feedback form isn't displaying any feedback when hitting “Send”

### ISSUE THREAD

**Issue by nightbirdsevolve** [PaddleHQ/Mac-Framework#109]
Nothing happens when you hit the “send feedback” button. 
A simple “Thank you, message was devlivered ok” / “Err: couldn't blabla”, would be nice.
Also, no validation is done: at least the email address and message could be validated.

**Comment by avalore** [comment]
Thanks, agreed some feedback would be nice. We'll look at this following the next release.
