### ISSUE TITLE
Crash in call to loadCheckout from Paddle framework

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#110]
Using version 3.0.11 of the framework running on macOS 10.12.0, a customer is having TG Pro quit unexpectedly because of a crash inside the Paddle code.

Here's the crashlog:

Incident Identifier: AB1186AD-EB15-47ED-ABA2-32AC9149AB64
CrashReporter Key:   1B9A1633-FE35-542A-B764-A30AC3C0DE0D
Hardware Model:      MacBookPro11,3
Process:         TG Pro [933]
Path:  
Identifier:      com.tunabellysoftware.tgpro
Version:         2.17 (3676)
Code Type:       X86-64
Parent Process:  launchd [1]

Date/Time:       2016-10-06 22:36:45 +0000
OS Version:      Mac OS X 10.12.0 (16A323)
Report Version:  104

Exception Type:  SIGSEGV
Exception Codes: SEGV_MAPERR at 0xa14c448bec0
Crashed Thread:  0

Application Specific Information:
Selector name found in current argument registers: loadCheckout

Thread 0 Crashed:
0   libobjc.A.dylib                      0x00007fff8b647b5d objc_msgSend + 29
1   Paddle                               0x0000000108686209 0x108674000 + 74249
2   WebKitLegacy                         0x00007fff7ef7c02b _Z21CallFrameLoadDelegatePFvvEP7WebViewP13objc_selectorP11objc_object + 59
3   WebKitLegacy                         0x00007fff7ef0ec41 _ZN20WebFrameLoaderClient21dispatchDidFinishLoadEv + 81
4   WebCore                              0x00007fff7dd14298 _ZN7WebCore11FrameLoader29checkLoadCompleteForThisFrameEv + 2120
5   WebCore                              0x00007fff7dd1399b _ZN7WebCore11FrameLoader17checkLoadCompleteEv + 443
6   WebCore                              0x00007fff7dd1668c _ZN7WebCore11FrameLoader14checkCompletedEv + 316
7   WebCore                              0x00007fff7dd17084 _ZN7WebCore11FrameLoader9completedEv + 116
8   WebCore                              0x00007fff7dd1667a _ZN7WebCore11FrameLoader14checkCompletedEv + 298
9   WebCore                              0x00007fff7e0186dd _ZN7WebCore20CachedResourceLoader8loadDoneEPNS_14CachedResourceEb + 109
10  WebCore                              0x00007fff7dd70284 _ZN7WebCore17SubresourceLoader16didFinishLoadingEd + 1332
11  CFNetwork                            0x00007fff760edbcb __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 72
12  CFNetwork                            0x00007fff760edadd -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 198
13  CFNetwork                            0x00007fff760eda05 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 48
14  CFNetwork                            0x00007fff760f1ff4 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 104
15  CFNetwork                            0x00007fff76314cc7 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 100
16  libdispatch.dylib                    0x00007fff8befd128 _dispatch_client_callout + 8
17  libdispatch.dylib                    0x00007fff8bf11ec7 _dispatch_block_invoke_direct + 322
18  CFNetwork                            0x00007fff760ed8d0 _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
19  CoreFoundation                       0x00007fff76eb62b4 CFArrayApplyFunction + 68
20  CFNetwork                            0x00007fff760ed7c9 _ZN19RunloopBlockContext7performEv + 137
21  CFNetwork                            0x00007fff760ed660 _ZN17MultiplexerSource7performEv + 282
22  CFNetwork                            0x00007fff760ed482 _ZN17MultiplexerSource8_performEPv + 72
23  CoreFoundation                       0x00007fff76f13551 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
24  CoreFoundation                       0x00007fff76ef46bd __CFRunLoopDoSources0 + 557
25  CoreFoundation                       0x00007fff76ef3bb6 __CFRunLoopRun + 934
26  CoreFoundation                       0x00007fff76ef35b4 CFRunLoopRunSpecific + 420
27  HIToolbox                            0x00007fff76494f6c RunCurrentEventLoopInMode + 240
28  HIToolbox                            0x00007fff76494da1 ReceiveNextEventCommon + 432
29  HIToolbox                            0x00007fff76494bd6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
30  AppKit                               0x00007fff74b8b5f5 _DPSNextEvent + 1093
31  AppKit                               0x00007fff7529b8eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
32  AppKit                               0x00007fff74b7ffbd -[NSApplication run] + 926
33  AppKit                               0x00007fff74b4aa8a NSApplicationMain + 1237
34  TG Pro                               0x0000000108087434 start + 51

Thread 1:
0   HockeySDK                            0x000000010836eb54 mach_exception_callback + 238
1   HockeySDK                            0x0000000108378c73 exception_server_thread + 152
2   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
3   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
4   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 2:
0   libsystem_kernel.dylib               0x00007fff8c0624e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8c149221 start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib               0x00007fff8c05a41a mach_msg_trap + 10
1   CoreFoundation                       0x00007fff76ef48d4 __CFRunLoopServiceMachPort + 212
2   CoreFoundation                       0x00007fff76ef3d61 __CFRunLoopRun + 1361
3   CoreFoundation                       0x00007fff76ef35b4 CFRunLoopRunSpecific + 420
4   AppKit                               0x00007fff74cd7e9e _NSEventThread + 205
5   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
6   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
7   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 4:
0   libsystem_kernel.dylib               0x00007fff8c05a41a mach_msg_trap + 10
1   CoreFoundation                       0x00007fff76ef48d4 **CFRunLoopServiceMachPort + 212
2   CoreFoundation                       0x00007fff76ef3d61 __CFRunLoopRun + 1361
3   CoreFoundation                       0x00007fff76ef35b4 CFRunLoopRunSpecific + 420
4   CFNetwork                            0x00007fff760c9144 +[NSURLConnection(Loader) _resourceLoadLoop:] + 313
5   Foundation                           0x00007fff7890130d __NSThread__start** + 1243
6   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
7   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
8   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 5:
0   libsystem_kernel.dylib               0x00007fff8c0624e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8c149221 start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib               0x00007fff8c0624e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8c149221 start_wqthread + 13

Thread 7:
0   libsystem_kernel.dylib               0x00007fff8c061fde __semwait_signal + 10
1   libc++.1.dylib                       0x00007fff8ab1965b _ZNSt3__111this_thread9sleep_forERKNS_6chrono8durationIxNS_5ratioILl1ELl1000000000EEEEE + 80
2   JavaScriptCore                       0x00007fff79d4b3df _ZNSt3__111this_thread9sleep_forIxNS_5ratioILl1ELl1000EEEEEvRKNS_6chrono8durationIT_T0_EE + 63
3   JavaScriptCore                       0x00007fff79d4a3d1 _ZN7bmallocL14waitUntilFalseERNSt3__111unique_lockINS_11StaticMutexEEENS0_6chrono8durationIxNS0_5ratioILl1ELl1000EEEEERb + 113
4   JavaScriptCore                       0x00007fff79d4a220 _ZN7bmalloc4Heap8scavengeERNSt3__111unique_lockINS_11StaticMutexEEENS1_6chrono8durationIxNS1_5ratioILl1ELl1000EEEEE + 48
5   JavaScriptCore                       0x00007fff79d4a0b4 _ZN7bmalloc4Heap18concurrentScavengeEv + 68
6   JavaScriptCore                       0x00007fff79d4b621 _ZN7bmalloc9AsyncTaskINS_4HeapEMS1_FvvEE13threadRunLoopEv + 97
7   JavaScriptCore                       0x00007fff79d4b529 _ZN7bmalloc9AsyncTaskINS_4HeapEMS1_FvvEE16threadEntryPointEPS4_ + 9
8   JavaScriptCore                       0x00007fff79d4b7dd _ZNSt3__114__thread_proxyINS_5tupleIJPFvPN7bmalloc9AsyncTaskINS2_4HeapEMS4_FvvEEEES8_EEEEEPvSC_ + 93
9   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
10  libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
11  libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 8:
0   libsystem_kernel.dylib               0x00007fff8c0624e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8c149221 start_wqthread + 13
2   ???                                  0x000070000fedbbe0 0x0 + 0

Thread 9:
0   libsystem_kernel.dylib               0x00007fff8c0624e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8c149221 start_wqthread + 13

Thread 10:
0   libsystem_kernel.dylib               0x00007fff8c0624e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8c149221 start_wqthread + 13
2   ???                                  0x000070001016ab40 0x0 + 0

Thread 11:
0   libsystem_pthread.dylib              0x00007fff8c149214 start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib              0x00007fff8c149214 start_wqthread + 0

Thread 13:
0   libsystem_kernel.dylib               0x00007fff8c061c8a __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aad858d _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   JavaScriptCore                       0x00007fff79d357de _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEENSt3__16chrono10time_pointINSD_12steady_clockENSD_8durationIxNSC_5ratioILl1ELl1000000000EEEEEEE + 2494
3   JavaScriptCore                       0x00007fff79aeb8ea _ZN3JSC11JITWorklist9runThreadEv + 234
4   JavaScriptCore                       0x00007fff79aebd7d _ZNSt3__110__function6__funcIZN3JSC11JITWorklistC1EvE3$_0NS_9allocatorIS4_EEFvvEEclEv + 13
5   JavaScriptCore                       0x00007fff79333072 _ZN3WTFL16threadEntryPointEPv + 178
6   JavaScriptCore                       0x00007fff79332f9f _ZN3WTFL19wtfThreadEntryPointEPv + 15
7   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
8   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
9   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 14:
0   libsystem_kernel.dylib               0x00007fff8c061c8a __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aad858d _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   JavaScriptCore                       0x00007fff79d357de _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEENSt3__16chrono10time_pointINSD_12steady_clockENSD_8durationIxNSC_5ratioILl1ELl1000000000EEEEEEE + 2494
3   JavaScriptCore                       0x00007fff79d34bd2 _ZN3WTF18ParallelHelperPool21waitForClientWithTaskERKNS_6LockerINS_8LockBaseEEE + 370
4   JavaScriptCore                       0x00007fff79d34943 _ZN3WTF18ParallelHelperPool16helperThreadBodyEv + 83
5   JavaScriptCore                       0x00007fff79333072 _ZN3WTFL16threadEntryPointEPv + 178
6   JavaScriptCore                       0x00007fff79332f9f _ZN3WTFL19wtfThreadEntryPointEPv + 15
7   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
8   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
9   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 15:
0   libsystem_kernel.dylib               0x00007fff8c061c8a __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aad858d _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   JavaScriptCore                       0x00007fff79d357de _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEENSt3__16chrono10time_pointINSD_12steady_clockENSD_8durationIxNSC_5ratioILl1ELl1000000000EEEEEEE + 2494
3   JavaScriptCore                       0x00007fff79d34bd2 _ZN3WTF18ParallelHelperPool21waitForClientWithTaskERKNS_6LockerINS_8LockBaseEEE + 370
4   JavaScriptCore                       0x00007fff79d34943 _ZN3WTF18ParallelHelperPool16helperThreadBodyEv + 83
5   JavaScriptCore                       0x00007fff79333072 _ZN3WTFL16threadEntryPointEPv + 178
6   JavaScriptCore                       0x00007fff79332f9f _ZN3WTFL19wtfThreadEntryPointEPv + 15
7   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
8   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
9   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 16:
0   libsystem_kernel.dylib               0x00007fff8c061c8a __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aad858d _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   JavaScriptCore                       0x00007fff79d357de _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEENSt3__16chrono10time_pointINSD_12steady_clockENSD_8durationIxNSC_5ratioILl1ELl1000000000EEEEEEE + 2494
3   JavaScriptCore                       0x00007fff79d34bd2 _ZN3WTF18ParallelHelperPool21waitForClientWithTaskERKNS_6LockerINS_8LockBaseEEE + 370
4   JavaScriptCore                       0x00007fff79d34943 _ZN3WTF18ParallelHelperPool16helperThreadBodyEv + 83
5   JavaScriptCore                       0x00007fff79333072 _ZN3WTFL16threadEntryPointEPv + 178
6   JavaScriptCore                       0x00007fff79332f9f _ZN3WTFL19wtfThreadEntryPointEPv + 15
7   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
8   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
9   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 17:
0   libsystem_kernel.dylib               0x00007fff8c061c8a __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aad858d _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   JavaScriptCore                       0x00007fff79d357de _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEENSt3__16chrono10time_pointINSD_12steady_clockENSD_8durationIxNSC_5ratioILl1ELl1000000000EEEEEEE + 2494
3   JavaScriptCore                       0x00007fff79d34bd2 _ZN3WTF18ParallelHelperPool21waitForClientWithTaskERKNS_6LockerINS_8LockBaseEEE + 370
4   JavaScriptCore                       0x00007fff79d34943 _ZN3WTF18ParallelHelperPool16helperThreadBodyEv + 83
5   JavaScriptCore                       0x00007fff79333072 _ZN3WTFL16threadEntryPointEPv + 178
6   JavaScriptCore                       0x00007fff79332f9f _ZN3WTFL19wtfThreadEntryPointEPv + 15
7   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
8   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
9   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 18:
0   libsystem_kernel.dylib               0x00007fff8c061c8a __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aad858d _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   JavaScriptCore                       0x00007fff79d357de _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEENSt3__16chrono10time_pointINSD_12steady_clockENSD_8durationIxNSC_5ratioILl1ELl1000000000EEEEEEE + 2494
3   JavaScriptCore                       0x00007fff79d34bd2 _ZN3WTF18ParallelHelperPool21waitForClientWithTaskERKNS_6LockerINS_8LockBaseEEE + 370
4   JavaScriptCore                       0x00007fff79d34943 _ZN3WTF18ParallelHelperPool16helperThreadBodyEv + 83
5   JavaScriptCore                       0x00007fff79333072 _ZN3WTFL16threadEntryPointEPv + 178
6   JavaScriptCore                       0x00007fff79332f9f _ZN3WTFL19wtfThreadEntryPointEPv + 15
7   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
8   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
9   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 19:
0   libsystem_kernel.dylib               0x00007fff8c061c8a __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aad858d _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   JavaScriptCore                       0x00007fff79d357de _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEENSt3__16chrono10time_pointINSD_12steady_clockENSD_8durationIxNSC_5ratioILl1ELl1000000000EEEEEEE + 2494
3   JavaScriptCore                       0x00007fff79d34bd2 _ZN3WTF18ParallelHelperPool21waitForClientWithTaskERKNS_6LockerINS_8LockBaseEEE + 370
4   JavaScriptCore                       0x00007fff79d34943 _ZN3WTF18ParallelHelperPool16helperThreadBodyEv + 83
5   JavaScriptCore                       0x00007fff79333072 _ZN3WTFL16threadEntryPointEPv + 178
6   JavaScriptCore                       0x00007fff79332f9f _ZN3WTFL19wtfThreadEntryPointEPv + 15
7   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
8   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
9   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 20:
0   libsystem_kernel.dylib               0x00007fff8c061c8a __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aad858d _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   JavaScriptCore                       0x00007fff79d357de _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEENSt3__16chrono10time_pointINSD_12steady_clockENSD_8durationIxNSC_5ratioILl1ELl1000000000EEEEEEE + 2494
3   WebKitLegacy                         0x00007fff7ef6f0fc _ZN3WTF13ConditionBase18waitForSecondsImplINS_4LockEEEbRT_d + 124
4   WebKitLegacy                         0x00007fff7ef6ef1d _ZN3WTF12MessageQueueINS_8FunctionIFvvEEEE33waitForMessageFilteredWithTimeoutIZNS4_14waitForMessageEvEUlRKS3_E_EENSt3__110unique_ptrIS3_NS9_14default_deleteIS3_EEEERNS_22MessageQueueWaitResultEOT_d + 109
5   WebKitLegacy                         0x00007fff7ef6e6dc _ZN7WebCore13StorageThread16threadEntryPointEv + 172
6   JavaScriptCore                       0x00007fff79333072 _ZN3WTFL16threadEntryPointEPv + 178
7   JavaScriptCore                       0x00007fff79332f9f _ZN3WTFL19wtfThreadEntryPointEPv + 15
8   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
9   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
10  libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 21:
0   libsystem_kernel.dylib               0x00007fff8c061c8a __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aad858d _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   JavaScriptCore                       0x00007fff79d357de _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEENSt3__16chrono10time_pointINSD_12steady_clockENSD_8durationIxNSC_5ratioILl1ELl1000000000EEEEEEE + 2494
3   JavaScriptCore                       0x00007fff798e3eae _ZN3JSC3DFG8Worklist9runThreadEPNS0_10ThreadDataE + 382
4   JavaScriptCore                       0x00007fff79333072 _ZN3WTFL16threadEntryPointEPv + 178
5   JavaScriptCore                       0x00007fff79332f9f _ZN3WTFL19wtfThreadEntryPointEPv + 15
6   libsystem_pthread.dylib              0x00007fff8c149abb _pthread_body + 180
7   libsystem_pthread.dylib              0x00007fff8c149a07 _pthread_body + 0
8   libsystem_pthread.dylib              0x00007fff8c149231 thread_start + 13

Thread 0 crashed with X86-64 Thread State:
   rip: 0x00007fff8b647b5d    rbp: 0x00007fff57b78d60    rsp: 0x00007fff57b78cf8    rax: 0x00006000001bbc80 
   rbx: 0x00000001086861b0    rcx: 0x0100000000000000    rdx: 0x011dffff926b1649    rdi: 0x00006000001bbc80 
   rsi: 0x00000001086cd9f7     r8: 0x0000000000000040     r9: 0x000060800017a728    r10: 0x00000a14c448bea8 
   r11: 0x00000001086cd9f7    r12: 0x00007fff57b78ec8    r13: 0x000000011101bb10    r14: 0x00006000001350e0 
   r15: 0x00007fff87cd4975 rflags: 0x0000000000010202     cs: 0x000000000000002b     fs: 0x0000000000000000 
    gs: 0x0000000000000000 

Binary Images:
       0x108085000 -        0x108258fff +TG Pro x86_64  <73a5419131b83a479ee93c65ea2b8140> /Applications/TG Pro.app/Contents/MacOS/TG Pro
       0x1082d5000 -        0x108311fff +Sparkle x86_64  <852faba7327631e785d48182810549d3> /Applications/TG Pro.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x108337000 -        0x1083b0fff +HockeySDK x86_64  <ec747b3c129c3124a2865ab8b4fd4881> /Applications/TG Pro.app/Contents/Frameworks/HockeySDK.framework/Versions/A/HockeySDK
       0x108435000 -        0x10859afff +MailCore x86_64  <e95e964f40f93f2883ed8201b37b67f2> /Applications/TG Pro.app/Contents/Frameworks/MailCore.framework/Versions/A/MailCore
       0x108674000 -        0x1086e1fff +Paddle x86_64  <43b5b0eb572935b6868a3ad397ef30e5> /Applications/TG Pro.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle

**Comment by avalore** [comment]
Thanks @tunabelly - this is related to #104 
3.0.12 is due to be released today, following this the next release will be addressing a number of bugs including this one.

**Comment by GregularExpressions** [comment]
Hey @tunabelly are you still seeing this issue?

**Comment by tunabelly** [comment]
@GregularExpressions I don't believe so. Thanks for checking in. I would go ahead and close this one.
