### ISSUE TITLE
Cannot see all of license key in window

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#111]
The font in the registration dialog from the Paddle SDK is too large to allow the entire license key to be seen. Customers have to scroll left/right to see if it's the correct one if there's an issue.

I've attached a screenshot from a customer who's license isn't registering, and I can't tell what he's typed in.
<img width="513" alt="screen shot 2016-10-20 at 11 08 37 am" src="https://cloud.githubusercontent.com/assets/2223932/19655146/f9603c86-99e8-11e6-86d5-677b61e05f23.png">

**Comment by avalore** [comment]
Thanks, this is being fixed on the next release due later this week.
