### ISSUE TITLE
paddle does not seem to automatically send a receipt with the serial-number to customers

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework#112]
i've got customers that complain to me that they lost the serial number for UninstallPKG. i am wondering why customers are not automatically receiving a receipt by e-mail that also contains their purchased serial-number for future reference.

in case this already exists (and the customers just lost that mail) we would need a way to trigger a re-send of this receipt/serial e-mail to the customer again.

**Comment by tjosten** [comment]
My customers do receive an email with the license code, so I would assume yours do as well. Your request is also strongly related to #67 I would think.
