### ISSUE TITLE
Audience email prompt appearing on every launch

### ISSUE THREAD

**Issue by OskarGroth** [PaddleHQ/Mac-Framework#113]
I have several Mac apps using the Paddle SDK to collect newsletter signup through the Audience feature.

Example of how I'm setting it up:

`[[PaddleToolKit sharedInstance] presentEmailSubscribePromptWithSchedule:@"1 launches"  message:nil];`

**Expected behavior: Prompt the user once, on the first launch.**

**Actual behavior: Prompt appears on every launch**

I'm seeing this issue across all my apps using the latest Paddle SDK.

I also think the syntax of having to spell out "1 launches" as a string is infinitely stupid, why not just make it an integer?

**Comment by GregularExpressions** [comment]
Hey @OskarGroth have you seen this issue lately? Do we need to investigate further?
