### ISSUE TITLE
Need a way to setup localized trial text from web dashboard

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#114]
There doesn't seem to be a way to setup localized text for the trial string from the web dashboard. I can do it from the code in the app except I believe if an Internet connection is active, the web will override the code. 

We have a localized app (Disk Diet) and it's kind of odd showing the trial dialog with nicely translated strings, except for the trial description string.

**Comment by Iomegan** [comment]
I absolut agree. Please add localization features for the **Trial Greeting** etc. This is overdue.

**Comment by GregularExpressions** [comment]
Hey, we're still working on Localization in general but the SDK does now have a method to override the trial text:

```obj-c
- (void)setCustomProductTrialText:(nonnull NSString *)productTrialText;
```

Hope that's helpful in the meantime.

Greg.
