### ISSUE TITLE
version 3.0.13 crashes in [PADDataStore store]

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework#115]
we recently updated from version 2.3.9 to version 3.0.13 and now we received a crash log for a crash inside Paddle. can you look into this?

[UninstallPKG_2016-12-05-222107_MacBook-Air-de-Jean-Bernard.txt](https://github.com/PaddleHQ/Mac-Framework/files/633647/UninstallPKG_2016-12-05-222107_MacBook-Air-de-Jean-Bernard.txt)

**Comment by core-code** [comment]
we are getting ready to ship an update and would really like to include a fix for this

**Comment by avalore** [comment]
Thanks for pointing this out. Could you send over a copy of your paddata.padl file please?

**Comment by core-code** [comment]
i am not sure my 'paddata.padl' helps, obviously the crash happened at a customers mac. should i try to ask him for the file?

**Comment by avalore** [comment]
Sorry, I read it as it happened on your machine. If you could get a copy of your customers .padl file that would be amazing but understand that's not always convenient. We'll be looking into it anyway.

**Comment by core-code** [comment]
thanks. i've obtained the paddata file from the customer. i do not know if it has been modified since the crash but i hope its useful.

anyway since this file may contain private data of the customer (not sure there) i don't want it to post it here publicly. please drop me a mail at feedback@corecode.io and i'll pass it along

**Comment by core-code** [comment]
any progress on this? we want to release an update that fixes this issue

**Comment by GregularExpressions** [comment]
Hi @core-code we believe this is fixed, have you see it recently - do we need to investigate further?

**Comment by core-code** [comment]
thanks
no i haven't seen it recently - didn't seem to be a very common issue in any case

is the fix server-side or in a new framework release?

**Comment by GregularExpressions** [comment]
@core-code It was a threading issue (aren't they always!?), so an SDK fix.

**Comment by core-code** [comment]
ok thanks we are gonna upgrade to 3.0.20 ;)
