### ISSUE TITLE
Assertion failure in -[NSTextFieldCell _objectValue:forString:errorDescription:]

### ISSUE THREAD

**Issue by muruganandham** [PaddleHQ/Mac-Framework#116]
I got follwing error in xcode 8.1 (not in xcode 8.0)

**Assertion failure in -[NSTextFieldCell _objectValue:forString:errorDescription:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504/AppKit.subproj/NSCell.m:1682**

**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: aString != nil'**
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffbc0ce52b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffd07a6cad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffbc0d3232 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fffbdb06390 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fffb9d0972a -[NSCell _objectValue:forString:errorDescription:] + 177
	5   AppKit                              0x00007fffb9d095cf -[NSCell setStringValue:] + 41
	6   AppKit                              0x00007fffb9db7eda -[NSControl setStringValue:] + 135
	7   Paddle                              0x0000000100149261 -[PADProductWindowController displayProductInfo] + 6049
	8   Padd
libc++abi.dylib: terminating with uncaught exception of type NSException

while running below code:

 **[[Paddle sharedInstance] startLicensing:productInfo timeTrial:NO withWindow:mainWindow];**

**Comment by avalore** [comment]
Thanks, will test on 8.1 and look for a fix.

**Comment by IshanAmin** [comment]
I'm also having this issue.  Any update?

**Comment by IshanAmin** [comment]
Was this ever resolved?

**Comment by GregularExpressions** [comment]
@IshanAmin yes, we believe so - let us know if you experience this.

**Comment by kaspesla** [comment]
New and testing out Paddle. Seeing this exact crash. Any tips?

**Comment by GregularExpressions** [comment]
@kaspesla can you confirm which version of the SDK you're working with please?

**Comment by kaspesla** [comment]
Hi Greg,
It said v-4. Downloaded it a few days ago.
Ken

**Comment by GregularExpressions** [comment]
Thanks @kaspesla it would be useful to see what you do with your Product Configuration and know what the productID is that you are working with.

**Comment by kaspesla** [comment]
Btw, it’s because I was passing in an empty product with a nil productName. The sample code should probably check for errors!  :)
Still unclear why the call to refresh the product is failing.
Ken

**Comment by kaspesla** [comment]
Hi Greg,
I'm using the sample code  Now that I've added a check for error I can see refresh: returns error -112.
541047 is a subscription plan. I also tried a regular product with the same results.
Thanks,
-Ken

    NSString *myPaddleProductID = @"541047"; 
    NSString *myPaddleVendorID = @"35452";
    NSString *myPaddleAPIKey = @"redacted";
    
    // Default Product Config in case we're unable to reach our servers on first run:
    PADProductConfiguration *defaultProductConfig = [PADProductConfiguration configuration:@"Standard"
                                                                               vendorName:@"Ecamm Network, LLC"];
    
    // Initialize the SDK singleton with the config:
    Paddle *paddle = [Paddle sharedInstanceWithVendorID:myPaddleVendorID
                                                 apiKey:myPaddleAPIKey
                                              productID:myPaddleProductID
                                          configuration:defaultProductConfig];
    
    // Initialize the Product you'd like to work with:
    PADProduct *paddleProduct = [[PADProduct alloc] initWithProductID:myPaddleProductID productType:PADProductTypeSubscriptionPlan configuration:nil];

    // Ask the Product to get it's latest state and info from the Paddle Platform:
    [paddleProduct refresh:^(NSDictionary * _Nullable productDelta, NSError * _Nullable error) {
        // Optionally show the default "Product Access" UI to gatekeep your app
        if (error)
            NSLog(@"error: %@", error);
        else
            [paddle showProductAccessDialogWithProduct:paddleProduct];
    }];

**Comment by leochou0729** [comment]
@kaspesla have you resolve this problem?

**Comment by leochou0729** [comment]
@kaspesla have you resolved this problem?
