### ISSUE TITLE
In-App Purchases can't be downloaded

### ISSUE THREAD

**Issue by floschliep** [PaddleHQ/Mac-Framework#119]
The current version of the SDK doesn't allow users to download In-App Purchases, in a sense of getting variable information about an IAP, to e.g. display them in a custom UI.

There are two separate classes, `PADProduct` and `PSKProduct`, but neither class has this kind of functionality. Furthermore, the responsibilities of these classes are unclear and the similar naming is confusing.

`PADProduct` has the instance method `productInfo:apiKey:vendorId:`, which apparently allows downloading (unknown) information about an IAP, but there's no way to actually get this information. Once `productInfoReceived` of the objects' delegate is being called, the `receivedData` instance variable is nil, which is the only exposed instance variable.
`PSKProduct` has the necessary properties to store information about an IAP, but there's no (public) way to create a `PSKProduct` from a `PADProduct`.

The property `productController` of `PaddleStoreKit` implies that the class `PSKProductController` is able to load/manage products, but the interface is private.
Interestingly the `PaddleStoreKitDelegate` protocol has a method which appears to be a callback for loading products, `PSKProductsReceived:`, but it is never being called, not even when a product is obviously being downloaded, e.g. due to calling `showProduct:` on `PaddleStoreKit`.

If I'm mistaken and there is in fact a way to achieve this, please let me know. Otherwise I suggest adding a clear and public API to the SDK.

**Comment by GregularExpressions** [comment]
Thanks for this Florian, hopefully the new Child Products are a step in the right direction.
