### ISSUE TITLE
PaddleResetTrial prefs param doesn't seem to work

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#120]
I'm trying to get a trial to reset so I can test some Paddle specific items in an app. However if I run the following in the terminal, it still doesn't work:

defaults write com.tunabelly.handsfree2 PaddleResetTrial -bool YES
sudo killall cfprefsd

Restarting the app and getting this:

![screen shot 2017-03-22 at 1 25 46 pm](https://cloud.githubusercontent.com/assets/2223932/24211660/21ca4f88-0f03-11e7-8d8e-fb9bb82f4f7e.png)

And this is with Paddle framework v3.0.16.

**Comment by avalore** [comment]
Thanks for raising this. We've got this scheduled to be fixed in the next release towards the end of the week.

**Comment by tunabelly** [comment]
Good to hear. Thanks for the update.

**Comment by avalore** [comment]
3.0.18 should resolve this issue. You should add the value to prefs while the app is closed and then start the app once it has been set.
