### ISSUE TITLE
In-App purchase failing

### ISSUE THREAD

**Issue by massimobio** [PaddleHQ/Mac-Framework#121]
I couldn't find any documentation regarding In-App purchases so this is based on what I could see in the API.
I do this to show the product store:
```Swift
PaddleStoreKit.sharedInstance().delegate = self
PaddleStoreKit.sharedInstance().showProduct("com.technimo.irealpro.macos.stylepack.blues")
```
and I get the product window:
<img width="671" alt="screen shot 2017-04-05 at 5 45 33 pm" src="https://cloud.githubusercontent.com/assets/240599/24728774/5a273b26-1a29-11e7-8e0b-d9a2953f296d.png">

but when I click on the buy button I get this and it cannot be dismissed
<img width="503" alt="screen shot 2017-04-05 at 5 45 46 pm" src="https://cloud.githubusercontent.com/assets/240599/24728786/66a9916e-1a29-11e7-9bcc-f86938b0728e.png">

Any ideas?

**Comment by involer** [comment]
We're actually in the process of deprecating 'Purchase' products (hence the lack of documentation) in favour of 'Feature Licenses' (which achieve very similar functionality – ie. ability to have multiple subsequent in-app purchases), but allow usage of the other areas of our licensing/checkout functionality (remote validation, expiring licenses, deactivations, multi-machine licensing etc...)

We're hoping to fully document (and publish) the new Feature Licenses functionality over the next couple of weeks, however it is currently in production and available for use. I'm going to add @avalore to this comment who should be able to provide you with the documentation and help with setup.

**Comment by massimobio** [comment]
Thank you. Looking forward.

**Comment by exevil** [comment]
@involer, @avalore: Any news regarding this issue?

**Comment by GregularExpressions** [comment]
Hey @exevil we have these features currently in beta with a few vendors while we're fine tuning, it shouldn't be long now before public release.
