### ISSUE TITLE
startLicensing / showLicensing won't work again if user cancels purchase

### ISSUE THREAD

**Issue by donkthemagicllama** [PaddleHQ/Mac-Framework#122]
If a user cancels a purchase or license activation, the startLicensing/showLicensing functions won't work (they seem to do nothing) until the app is restarted.

If user clicks "Continue Trial", it works as expected, but if they click Activate or Purchase, then cancel, it seems to break.

**Comment by avalore** [comment]
@donkthemagicllama could you confirm which version of the SDK you're seeing this on?

**Comment by donkthemagicllama** [comment]
I was having the issue in 3.0.9, I updated to 3.0.17 (latest in git as far as I can tell) and the problem remains.
