### ISSUE TITLE
Crash in startLicensing - related to showing modal window

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#124]
This is occurring with Paddle 3.0.18 which should have the fix for the modal session crash.

Incident Identifier: D1DD1003-7A72-4982-BA1D-9239861CE4BA
CrashReporter Key:   BC0379A5-C6AB-545A-A51F-7AB8432A1908
Hardware Model:      MacPro3,1
Process:         TG Pro [609]
Path:            
Identifier:      com.tunabellysoftware.tgpro
Version:         2.19 (3980)
Code Type:       X86-64
Parent Process:  launchd [1]

Date/Time:       2017-04-28T17:53:37Z
Launch Time:     2017-04-28T17:53:31Z
OS Version:      Mac OS X 10.11.6 (15G1421)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x7fff93d7bf06
Crashed Thread:  0

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modal session requires modal window'

Last Exception Backtrace:
0   CoreFoundation                       0x00007fff893fb43a __exceptionPreprocess + 154
1   libobjc.A.dylib                      0x00007fff88f1573c objc_exception_throw + 47
2   CoreFoundation                       0x00007fff8940012a +[NSException raise:format:arguments:] + 105
3   Foundation                           0x00007fff9acdc856 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 197
4   AppKit                               0x00007fff8c53774e -[NSApplication _commonBeginModalSessionForWindow:relativeToWindow:modalDelegate:didEndSelector:contextInfo:] + 691
5   Paddle                               0x000000011050d5fd 0x110506000 + 30205
6   Paddle                               0x000000011050baab 0x110506000 + 23211
7   Paddle                               0x00000001105091af 0x110506000 + 12719
8   TG Pro                               0x000000010ff2e4a6 -[TGAppDelegate finishLoadingApp] (TGAppDelegate.m:1088)
9   libdispatch.dylib                    0x00007fff9211e93d _dispatch_call_block_and_release + 11
10  libdispatch.dylib                    0x00007fff9211340b _dispatch_client_callout + 7
11  libdispatch.dylib                    0x00007fff92126c1c _dispatch_main_queue_callback_4CF + 1684
12  CoreFoundation                       0x00007fff893b0949 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
13  CoreFoundation                       0x00007fff8936f83d __CFRunLoopRun + 1948
14  CoreFoundation                       0x00007fff8936ee38 CFRunLoopRunSpecific + 295
15  HIToolbox                            0x00007fff8bb85935 RunCurrentEventLoopInMode + 234
16  HIToolbox                            0x00007fff8bb8576f ReceiveNextEventCommon + 431
17  HIToolbox                            0x00007fff8bb855af _BlockUntilNextEventMatchingListInModeWithFilter + 70
18  AppKit                               0x00007fff8c2cadf6 _DPSNextEvent + 1066
19  AppKit                               0x00007fff8c2ca226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 453
20  AppKit                               0x00007fff8c2bed80 -[NSApplication run] + 681
21  AppKit                               0x00007fff8c288368 NSApplicationMain + 1175
22  TG Pro                               0x000000010feff434 start + 51

Thread 0 Crashed:
0   libsystem_kernel.dylib               0x00007fff93d7bf06 __pthread_kill + 10
1   libsystem_c.dylib                    0x00007fff95b6b6df abort + 128
2   HockeySDK                            0x00000001101ed4a1 uncaught_exception_handler + 26
3   CoreFoundation                       0x00007fff894627cb __handleUncaughtException + 730
4   libobjc.A.dylib                      0x00007fff88f19488 _objc_terminate() + 93
5   HockeySDK                            0x00000001101dba53 BITCrashUncaughtCXXTerminateHandler() (BITCrashCXXExceptionHandler.mm:146)
6   libc++abi.dylib                      0x00007fff9956b00e std::__terminate(void (*)()) + 7
7   libc++abi.dylib                      0x00007fff9956b083 std::terminate() + 50
8   libdispatch.dylib                    0x00007fff9211341f _dispatch_client_callout + 27
9   libdispatch.dylib                    0x00007fff92126c1c _dispatch_main_queue_callback_4CF + 1684
10  CoreFoundation                       0x00007fff893b0949 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
11  CoreFoundation                       0x00007fff8936f83d __CFRunLoopRun + 1948
12  CoreFoundation                       0x00007fff8936ee38 CFRunLoopRunSpecific + 295
13  HIToolbox                            0x00007fff8bb85935 RunCurrentEventLoopInMode + 234
14  HIToolbox                            0x00007fff8bb8576f ReceiveNextEventCommon + 431
15  HIToolbox                            0x00007fff8bb855af _BlockUntilNextEventMatchingListInModeWithFilter + 70
16  AppKit                               0x00007fff8c2cadf6 _DPSNextEvent + 1066
17  AppKit                               0x00007fff8c2ca226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 453
18  AppKit                               0x00007fff8c2bed80 -[NSApplication run] + 681
19  AppKit                               0x00007fff8c288368 NSApplicationMain + 1175
20  TG Pro                               0x000000010feff434 start + 51

Thread 1:
0   libsystem_kernel.dylib               0x00007fff93d7c5e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff96600341 start_wqthread + 12

Thread 2:
0   libsystem_kernel.dylib               0x00007fff93d7cefa kevent_qos + 10
1   libdispatch.dylib                    0x00007fff92118dcd _dispatch_mgr_thread + 51

Thread 3:
0   libsystem_kernel.dylib               0x00007fff93d7c5e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff96600341 start_wqthread + 12

Thread 4:
0   libsystem_kernel.dylib               0x00007fff93d7c5e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff96600341 start_wqthread + 12

Thread 5:
0   libsystem_kernel.dylib               0x00007fff93d7c5e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff96600341 start_wqthread + 12

Thread 6:
0   libsystem_kernel.dylib               0x00007fff93d75fae semaphore_wait_trap + 10
1   libdispatch.dylib                    0x00007fff92121994 _dispatch_barrier_sync_f_slow + 593
2   TG Pro                               0x000000010ff469a7 __33-[TGAppDelegate checkTimerFired:]_block_invoke (TGAppDelegate.m:4380)
3   libdispatch.dylib                    0x00007fff9211e93d _dispatch_call_block_and_release + 11
4   libdispatch.dylib                    0x00007fff9211340b _dispatch_client_callout + 7
5   libdispatch.dylib                    0x00007fff9211803b _dispatch_queue_drain + 753
6   libdispatch.dylib                    0x00007fff9211e707 _dispatch_queue_invoke + 548
7   libdispatch.dylib                    0x00007fff9211340b _dispatch_client_callout + 7
8   libdispatch.dylib                    0x00007fff9211729b _dispatch_root_queue_drain + 1889
9   libdispatch.dylib                    0x00007fff92116b00 _dispatch_worker_thread3 + 90
10  libsystem_pthread.dylib              0x00007fff966024de _pthread_wqthread + 1128
11  libsystem_pthread.dylib              0x00007fff96600341 start_wqthread + 12

Thread 7:
0   libsystem_kernel.dylib               0x00007fff93d75f72 mach_msg_trap + 10
1   HockeySDK                            0x00000001101f79a2 exception_server_thread + 200
2   libsystem_pthread.dylib              0x00007fff9660299d _pthread_body + 130
3   libsystem_pthread.dylib              0x00007fff9660291a _pthread_start + 167
4   libsystem_pthread.dylib              0x00007fff96600351 thread_start + 12

Thread 8:
0   libsystem_kernel.dylib               0x00007fff93d75f72 mach_msg_trap + 10
1   CoreFoundation                       0x00007fff89370124 __CFRunLoopServiceMachPort + 211
2   CoreFoundation                       0x00007fff8936f5ec __CFRunLoopRun + 1355
3   CoreFoundation                       0x00007fff8936ee38 CFRunLoopRunSpecific + 295
4   AppKit                               0x00007fff8c420d95 _NSEventThread + 148
5   libsystem_pthread.dylib              0x00007fff9660299d _pthread_body + 130
6   libsystem_pthread.dylib              0x00007fff9660291a _pthread_start + 167
7   libsystem_pthread.dylib              0x00007fff96600351 thread_start + 12

Thread 9:
0   libsystem_kernel.dylib               0x00007fff93d7c5e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff96600341 start_wqthread + 12

Thread 10:
0   libsystem_kernel.dylib               0x00007fff93d7c5e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff96600341 start_wqthread + 12

Thread 11:
0   libsystem_kernel.dylib               0x00007fff93d7c5e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff96600341 start_wqthread + 12

Thread 0 crashed with X86-64 Thread State:
   rip: 0x00007fff93d7bf06    rbp: 0x00007fff4fd00ed0    rsp: 0x00007fff4fd00ea8    rax: 0x0000000000000000 
   rbx: 0x0000000000000006    rcx: 0x00007fff4fd00ea8    rdx: 0x0000000000000000    rdi: 0x000000000000160b 
   rsi: 0x0000000000000006     r8: 0x0000000000000010     r9: 0x00000000ffe00000    r10: 0x0000000008000000 
   r11: 0x0000000000000206    r12: 0x00007fff74fe6160    r13: 0x00007f900da48890    r14: 0x00007fff778c4000 
   r15: 0x00007f900f80f200 rflags: 0x0000000000000206     cs: 0x0000000000000007     fs: 0x0000000000000000 
    gs: 0x0000000000000000 

Binary Images:
       0x10fefd000 -        0x1100d3fff +TG Pro x86_64  <e4680d798ea33840a1b245bd8bf761da> /Applications/TG Pro.app/Contents/MacOS/TG Pro
       0x11014d000 -        0x11018cfff +Sparkle x86_64  <dd2762ab6ccb3e69a0ecd3f1786cd902> /Applications/TG Pro.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x1101b2000 -        0x110233fff +HockeySDK x86_64  <6acd18b964f2348291f0dadc4e7ae812> /Applications/TG Pro.app/Contents/Frameworks/HockeySDK.framework/Versions/A/HockeySDK
       0x1102ca000 -        0x11042ffff +MailCore x86_64  <e95e964f40f93f2883ed8201b37b67f2> /Applications/TG Pro.app/Contents/Frameworks/MailCore.framework/Versions/A/MailCore
       0x110506000 -        0x11057afff +Paddle x86_64  <6cf23f04867f3cafb0c2c4034e7b46f5> /Applications/TG Pro.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle
       0x1105b3000 -        0x11060ffff +Growl x86_64  <6c20b93b75b230a482678c81bf90872b> /Applications/TG Pro.app/Contents/Frameworks/Growl.framework/Versions/A/Growl

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

There's a workaround (hopefully) for this in the SDK at the moment, there's a delegate method:

```obj-c
- (BOOL)willPresentModalForWindow:(NSWindow * _Nullable )window;
```

If you have other modal windows presented you can choose what to do (dismiss, or prevent SDK window) and avoid the crash.

Thanks,
Greg.

**Comment by tunabelly** [comment]
@GregularExpressions ok, I'll give that workaround a try for now and hopefully the source of the crash can be fixed too. Thanks for the info.
