### ISSUE TITLE
isSiteLicensed does not work

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#125]
We issued an update for TG Pro with Paddle 3.0.18 and with the isSiteLicensed flag set to YES. However, we're getting numerous reports from customers where they still have to enter the license key for every single user on the Mac.

Is there something else we need to add to make this work?

**Comment by GregularExpressions** [comment]
Hi,

Thanks for reporting the issue.

Could you send us the section of code with the isSiteLicensed implementation please?

Thanks,
Greg.

**Comment by tunabelly** [comment]
It's as simple as setting isSiteLicensed to YES in the Paddle shared instance. Let me know if there's anything else I can provide.

**Comment by tunabelly** [comment]
@GregularExpressions any update on this?

**Comment by GregularExpressions** [comment]
@tunabelly Apologies for the delay, we'll be in contact shortly with an updated SDK build to help debug this.

**Comment by tunabelly** [comment]
@GregularExpressions ok, thank you.

**Comment by avalore** [comment]
Do you have a shared folder on the machine that presents this issue?
If you do, does this folder container another with the name of your app?
`/Users/Shared/App Name`

**Comment by tunabelly** [comment]
Sorry for the delay - I replied from my phone and it didn't seem to post it. I can't say either way because it's on customer machines although if it's critical to find out, I can inquire with them.

**Comment by avalore** [comment]
Apologies for the delay. It would be very useful to find this out in order to resolve.

**Comment by tunabelly** [comment]
I apologize for the delay in getting back to you about this. There is a /Users/Shared/TG Pro/ folder with one file - paddata.padl and no subfolders.
