### ISSUE TITLE
Xcode Buildtime Documentation Warning

### ISSUE THREAD

**Issue by lovette** [PaddleHQ/Mac-Framework#126]
Xcode complains at build time that parameter 'mainWindow' is not found in the function declaration for startLicensingSilently. [/Paddle.framework/Headers/Paddle.h:180] (There are two other similar documentation warnings, but Xcode is able to fix them itself by renaming the parameter.)

**Comment by GregularExpressions** [comment]
Hey @lovette 

Thanks for reporting, we'll get these warnings resolved in the next release or two.

Thanks,
Greg.
