### ISSUE TITLE
onlyDestroyLicenceOnVerificationFail never called

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#127]
With the app delegate as the delegate of the Paddle framework with this code, onlyDestroyLicenceOnVerificationFail is never called, which never removes an invalid license (ex: it was generated with a keygen).

[paddle verifyLicenceWithCompletionBlock:^(BOOL verified, NSError *error) {
				if (verified) {
					NSLog(@"verified");
				}
			}];

// THIS IS CALLED
- (BOOL)shouldDestroyLicenceOnVerificationFail {
	return YES;
}

// THIS IS NEVER CALLED
- (BOOL)onlyDestroyLicenceOnVerificationFail {
	return YES;
}

- (int)failedAttemptsBeforeLicenceDestruction {
	return 1;
}

**Comment by tunabelly** [comment]
@avalore any luck on figuring out what the issue was and a fix for it?

**Comment by tunabelly** [comment]
@avalore having this work properly would be a **huge** help in cutting down on pirated versions of our apps (which there are a lot).

**Comment by tunabelly** [comment]
Is this fixed in 3.0.20?

**Comment by tunabelly** [comment]
@avalore is this fixed in 3.0.20?

**Comment by avalore** [comment]
@tunabelly We haven't completely replicated this issue but have resolved a related problem here and done some further testing. onlyDestroyLicenceOnVerificationFail will only get called when the API returns an invalid licence response, which could possibly be why you're not seeing it being called.

We have capacity to work on this further so if you experience this same issue could you please email a copy of the paddata.padl file (when the app has been activated with an invalid licence) and I'll dig into this further.

**Comment by tunabelly** [comment]
I just ran a test by registering HandsFree2 with a fake license that was generated with a keygen (it also installs it into the padl file). The v3.0.20 framework checked the license when verifyLicenceWithCompletionBlock was called and it returned:

verified = NO
error = nil

and it never called onlyDestroyLicenceOnVerificationFail, which means the app still runs perfectly for someone who's using a fake license key (and there are a LOT of them).

I was really hoping this would work since I've already sent Paddle the information on how to use a keygen to generate a fake license so it's pretty easy to test. I'll send the paddata.padl separately in an email right now.

**Comment by tunabelly** [comment]
Is this fixed in 3.0.21? I couldn't tell my looking at the changelog. Thanks.

**Comment by GregularExpressions** [comment]
@tunabelly No, we're still working on this one.

**Comment by tunabelly** [comment]
@GregularExpressions I sent all the information on how to replicate this along with the PADL file and the keygen to make the fake license keys about a month ago. Did you guys have a chance to try it out and see why the fake license isn't being removed?

**Comment by GregularExpressions** [comment]
@tunabelly Unfortunately not yet, but it's not been forgotten about.

**Comment by tunabelly** [comment]
@GregularExpressions I would really like to see this fixed in the next framework update. I'm assuming (and maybe incorrectly) that this should be a relatively easy fix. It would certainly cut down on the thousands of pirated copies people are using.

**Comment by GregularExpressions** [comment]
@tunabelly recently we've been focused on the user license recovery feature and the migration from IAP -> Feature Licensing, as these benefit / impact almost all of our vendors. That's starting to wrap up now and we'll get back to this as soon as is possible.

**Comment by tunabelly** [comment]
@GregularExpressions thanks for the update. I'm really looking forward to seeing this fixed.

**Comment by adriangranados** [comment]
I think this issue should be given higher priority. "Cracked" copies of my apps can be found just hours after being released. Not being able to perform remote license verification is really a problem. 

In my case, shouldDestroyLicenseOnVerificationFail and failedAttemptsBeforeLicenceDestruction are being called, but onlyDestroyLicenceOnVerificationFail is not, so I'm assuming the license verification is not failing.

I've tested the remote license verification API using a key generator you can easily download from the Internet, like this one:

<img width="494" alt="screen shot 2017-08-16 at 9 53 39 pm" src="https://user-images.githubusercontent.com/12258792/29392701-7fd5207e-82cd-11e7-95fe-8fa7d8924777.png">

Any help on solving this is greatly appreciated. Software piracy is really hurting us.

**Comment by adriangranados** [comment]
I also tested the SDK method `verifyLicenceWithCompletionBlock:^(BOOL verified, NSError *error)`. For me, it correctly returns verified=NO when the license key is not registered with Paddle but the problem is that it also returns verified=NO when offline. Yes, I could try to check whether Internet access is working (calling the API itself for something simple), but I really would like to either have Paddle automatically dealing with the deactivation if the verification fails, or have this method return an error when the verification couldn't be performed (e.g. offline).

**Comment by tunabelly** [comment]
@adriangranados software piracy is really hurting us as well. I was so excited to see remote license validation in the Paddle framework, except it doesn't work. 

I've sent instructions to @avalore and @GregularExpressions quite a while ago on how to reproduce this with the keygen. Any (honest) idea of when we'll see a fix? To be fair, I reported this 3 1/2 months ago and it seems like it would be an easy fix since the license keys don't exist in the Paddle database.

**Comment by adriangranados** [comment]
I know piracy would still be a thing no matter what, and that probably most of the people who download pirated copies of the app will never buy it anyway, but making it a little bit difficult for them to use pirated copies would be nice. As it is, it's just too easy to download and run these key generators. I see hundreds of "active users" in my DevMate dashboard, yet only a few transactions in Paddle.

**Comment by tunabelly** [comment]
@GregularExpressions is this something that is fixed in the 3.0.25 release?

**Comment by andrewha** [comment]
I'm seeing this same issue. I'm returning 10 for failedAttemptsBeforeLicenceDestruction, and true for shouldDestroyLicenceOnVerificationFail. I disabled the network connection on a test machine, the license is never de-activated after calling verifyLicenceWithCompletionBlock 10+ times. 

verifyLicenceWithCompletionBlock should return an error if it cannot make a connection. If there is no error, then I would presume that your server correctly returns verified = false, and I can deactivate the license programatically. 

If there is no internet connection, perhaps because someone blocks connection using a firewall, we should get the ability to deactivate the license after a certain number of failed connections to your activation server. 

This is core functionality for a licensing framework, is there an ETA on getting this fixed?

**Comment by tunabelly** [comment]
@andrewha good point that this should really be considered a core component of a licensing framework. I created this ticket 5 months ago and also emailed instructions on how to reproduce. I'm guessing it won't be fixed soon since Paddle is merging with the DevMate SDK and that's probably priority.

**Comment by andrewha** [comment]
Well, unfortunately I simply won't be releasing my app to the public until this issue is resolved. Or perhaps I'll write my own at this rate...

**Comment by GregularExpressions** [comment]
hey @pixeleyesltd thus far we've been unable to replicate this issue our end, would you mind emailing me some more details / code samples about your implementation please? it's greg at Paddle.com. Thanks!

**Comment by pixeleyesltd** [comment]
@GregularExpressions I've just sent this information your way 👍

**Comment by tunabelly** [comment]
@GregularExpressions this is absolutely killing our sales. There are so many pirated copies of our apps because of the ease of working around the licensing in the Paddle framework. This is an excellent example of how people are doing it. We've sent all the necessary info on how to reproduce this and how to help prevent pirating. 

When will this be fixed?

**Comment by GregularExpressions** [comment]
hey @pixeleyesltd because of the internal behaviours of the SDK we believe it should've worked after 12 calls, where-as your test case appears to stop at 11? We're going to amend it to be more intuitive.

**Comment by GregularExpressions** [comment]
@pixeleyesltd [v3.0.26](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.26) should work as you expected.

@tunabelly improving the piracy situation is one of the major focuses for v4, some of the most successful piracy techniques are the result of v3's legacy support and backwards compatibility. I'll keep you updated.

**Comment by charlieMonroe** [comment]
@GregularExpressions - unfortunately, this isn't fixed yet (tested against v3.0.29). I have a delegate that on `shouldDestroyLicenceOnVerificationFail` returns `true`, on `failedAttemptsBeforeLicenceDestruction` returns 5. I've launched the app about 10 times, the license is still in place. Using breakpoints, I can confirm that both methods get called by Paddle SDK.

I also call manually license verification and the result is that the license is not valid (correct). But no matter how many times I launch the app and the license gets checked, it still stays in place. I will add my own counter, but I think this is something that should be addressed ASAP and not in v4 which is still months away from what I understand.

**Comment by tunabelly** [comment]
@charlieMonroe I couldn't agree more. I don't understand why it's still not fixed after more than 6 months. This should absolutely be priority, otherwise I don't see the point of having this feature and advertising that it will remove invalid licenses when it doesn't.

**Comment by GregularExpressions** [comment]
Hey @charlieMonroe thanks for the report, we'll look into this and aim to get a fix out for v3.

**Comment by GregularExpressions** [comment]
@charlieMonroe would you mind sending me over the paddata.padl file in your test case please?

**Comment by charlieMonroe** [comment]
Sure, here it is (it's from a Paddle keygen that floats around, so I don't mind it being here):

[Downie 3.zip](https://github.com/PaddleHQ/Mac-Framework/files/1527763/Downie.3.zip)

**Comment by GregularExpressions** [comment]
[v3.30](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.30) has some new functionality to help combat the keygen piracy method.

In short, the keygen creates SDK v2 licenses which then v3 of the SDK honours as it's unsure of it's origin. It also does not purge it when it fails verification, regardless of the remote license verification delegate methods config.

v3.30 adds new preference that you can toggle before entering your various IDs and keys on initialisation that will enable the purging of these keys, `setShouldRemoveAmbiguousLicenses`. This will cause any of these v2 license generation keygen licenses to be removed once they reach your verification attempts threshold (or 65 by default).

The only thing to be aware of is that any legitimate customers still on v2 licenses will also experience a license purge, however if they re-enter that same license then it'll be activated in the v3 scheme and then be exempt from these issues in future.
