### ISSUE TITLE
License Prompt on Each Update

### ISSUE THREAD

**Issue by charlieMonroe** [PaddleHQ/Mac-Framework#131]
Hi,

one of my customers needs to enter a license with each update (2.4 to 2.4.1, 2.4.1 to 2.4.2, etc.). This app is licensing silently and uses these parameters:

```
paddle.disableLicenseMigration()
paddle.resetTrialOnVersionUpdate(forMajorOnly: true)
```

I am using the latest framework (3.0.19) and only one user is affected.

Is there any further information I can provide? If you need to get in touch with the end user, please let me know at support@charliemonroe.net.

Thanks!

**Comment by GregularExpressions** [comment]
Hey Charlie,

Thanks for reporting this, I've sent you an email requesting some additional data.

Greg.

**Comment by charlieMonroe** [comment]
Hi Greg,

I've sent you info about one more customer experiencing the same issue. I've included the licensing files.

Cheers,

Charlie Monroe
support@charliemonroe.net
