### ISSUE TITLE
Found way to crash framework

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#133]
**Before** calling startLicensing, call these two methods:

[PaddleAnalyticsKit enableTracking];
[PaddleAnalyticsKit startTracking];

You'll get a crash with the following stack trace:

'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: product_id)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff854752cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff9a28048d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8537201a -[__NSDictionaryM setObject:forKey:] + 1146
	3   Paddle                              0x00000001008e8d5e +[PADUtilities urlRequestWithParameters:andMethod:] + 1550
	4   Paddle                              0x00000001008d4d1c -[PADConfig getTools] + 60
	5   Paddle                              0x00000001009068a4 +[PaddleAnalyticsKit startTracking] + 84

Ideally, the framework should not crash and maybe print out a message to the console that startLicensing needs to be called first.

**Comment by GregularExpressions** [comment]
Hey @tunabelly,

We believe we've resolved this in [v3.0.22](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.20), there's now a console warning as you suggested.

Thanks,
Greg.
