### ISSUE TITLE
Customer lost license after upgrading from Paddle 3.0.18 -> 3.0.20 (pre-release)

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#134]
We have a customer that is pretty upset that after updating TG Pro from 2.20 (Paddle 3.0.18) -> 2.21 (Paddle 3.0.20 pre-release), the app went into "trial over" mode. To make it even worse, when he tried to enter his license key, it was already used too many times. So needless to say, he wasn't very happy that his app was unusable until I was able to reply to him.

PM or email me for the license key and his email.

**Comment by tunabelly** [comment]
Got another one:

> I bought your product last year. After the latest update I was asked to activate the license again. Now I get an error message saying: "License code has already been utilized” 
> I need to have this fixed

These customers are getting really upset - I can't imagine how frustrating it would be to update an app, only for it to say I need to enter the license key again and then to find out the key has been used too many times.

**Comment by tunabelly** [comment]
It seems that every step forward is going two back with regressions.

**Comment by tunabelly** [comment]
Got another one this afternoon. So we now have 3 separate customers that emailed about this (and probably a ton more that didn't). Please let us know what you need to try and fix this.

**Comment by avalore** [comment]
Thanks for reporting this @tunabelly 
We have a release scheduled to be released this week to resolve these issues.
I'll PM you for the details of this customer to double check it's the same issue.

**Comment by tunabelly** [comment]
@avalore is this still scheduled to be released this week?

**Comment by tunabelly** [comment]
Is this fixed in 3.0.20?

**Comment by GregularExpressions** [comment]
@tunabelly We believe so, yes.
