### ISSUE TITLE
Licensing window has no shadow on macOS 10.13 (17A264c)

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#135]
Here's a screenshot of it on 10.13:

![screen shot 2017-06-20 at 6 12 45 pm](https://user-images.githubusercontent.com/2223932/27363229-2e4b7616-5601-11e7-92d7-87af6bcca506.png)

Here's a screenshot on 10.12.5:

<img width="524" alt="screen shot 2017-06-20 at 6 14 47 pm" src="https://user-images.githubusercontent.com/2223932/27363240-374be566-5601-11e7-8e02-bed8bef1d0a5.png">

**Comment by avalore** [comment]
Thanks for raising this. We're currently working on an update for 10.13.

**Comment by tunabelly** [comment]
How's it going with the update for 10.13?

**Comment by fiam** [comment]
@tunabelly Have you tested the last release? The bug seems worse in my tests, since the licensing window won't even appear. I reported the issue in #138, but it seems no one has looked at it yet.

**Comment by tunabelly** [comment]
@fiam I did try one of our apps that's been updated to use Paddle 3.0.21 on the latest 10.13 dev beta and the licensing window does appear although without the shadow.

**Comment by fiam** [comment]
@tunabelly That's definitely strange. I've just tested with Paddle 3.0.21 and the latest 10.13 beta (17A306e) and the product window won't even appear.

**Comment by fiam** [comment]
@tunabelly Just figured it out thanks to your comment. I was launching the app from a network volume, which in the current High Sierra beta breaks resource loading from bundles (so the nib for the licensing window wouldn't load).

**Comment by tunabelly** [comment]
Will this be fixed soon? I'm getting concerned that customers are now starting to use 10.13 (betas) and when the public beta is out all our apps are going to look pretty bad with the trial dialog having no shadow. I was hoping this would be an easy fix, like the NSWindow not having the shadow property or something like that.

**Comment by tunabelly** [comment]
@GregularExpressions @avalore when will this be fixed? macOS 10.13 will be released to the public soon and this needs to be resolved since it looks really bad.

**Comment by tunabelly** [comment]
Looks like I reported this in **2015** with #74.

**Comment by tunabelly** [comment]
@GregularExpressions @avalore macOS 10.13 is being released on September 25 of this year and we still don't have a fix for this. Everyone needs to get their apps ready for High Sierra and it's a huge bummer to have **our apps look like garbage when they're first launched with the new OS**. 

When can we expect a fix? I'm getting pretty frustrated, considering I reported this almost 3 months ago and it seems like a relatively simple fix.

**Comment by GregularExpressions** [comment]
Hey @tunabelly 10.13 is a focus of ours right now, I agree on the perception damage,  we will try to get this fixed ahead of time.

**Comment by GregularExpressions** [comment]
@tunabelly You'll be pleased to hear that this appears to now be fixed in an internal build, we'll be releasing an SDK update soon.

**Comment by tunabelly** [comment]
@GregularExpressions yes, I'm happy to hear it's fixed and will be released soon. Thank you for the update. Will this also include fixes for #148 and #141?

**Comment by GregularExpressions** [comment]
@tunabelly 141 we believe so, we found some unicode edge cases around the storage of the license key that we hope is the final remaining cause of this.

148 we've not investigated yet, I'll try and get it into the next release.
