### ISSUE TITLE
Licensing window fails to appear on macOS High Sierra public beta

### ISSUE THREAD

**Issue by fiam** [PaddleHQ/Mac-Framework#138]
The licensing doesn't appear on macOS High Sierra after calling startLicensing:timeTrial:withWindow:, using the latest release of the framework (3.0.21). The following is printed to stderr:

```
2017-07-09 10:20:45.575 XXXXXX[807:7751] -[PADProductWindowController loadWindow]: failed to load window nib file 'PADProductWindowControllerYosemite'.
2017-07-09 10:20:45.575 XXXXXX[807:7751] beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo: requires a non-nil sheet
2017-07-09 10:20:45.575 XXXXXX[807:7751] -[PADProductWindowController loadWindow]: failed to load window nib file 'PADProductWindowControllerYosemite'.
```

The licensing window works fine on macOS Sierra (10.12).

**Comment by GregularExpressions** [comment]
Hey Alberto,

Thanks for reporting this, the SDK team is aiming to be fully compatible before the public release.

Thanks,
Greg.

**Comment by fiam** [comment]
@GregularExpressions Thanks for letting me know. Unfortunately, due to Apple's public beta program I'm already  getting several support requests per day asking for High Sierra support even when the final release is still months away. Could you please prioritise this issue and try to get it fixed as soon as possible? Thanks!

**Comment by fiam** [comment]
Closing this, since I've found that my installation of High Sierra won't correctly load any .framework resources from the app bundle, not just Paddle.framework, so the problem has to be somewhere else.

**Comment by fiam** [comment]
Just found the root cause, posting it here so no one else loses half a day stuck in the same place. Current macOS High Sierra betas won't correctly load framework resources if the app is in a network volume. The framework binary will load and the app won't crash but it won't be able to find the framework sources, breaking nib loading (which caused the error in my first message).

Since I was testing from a VM running High Sierra which was launching the app from a network volume shared by the host, this was a total pain to figure out.
