### ISSUE TITLE
Calling deactivateLicence brings up modal view

### ISSUE THREAD

**Issue by Joebayld** [PaddleHQ/Mac-Framework#139]
I've found that if I call deactivateLicence from my app, it then brings up a modal view to purchase/activate the software. I want it to display as a sheet view. Is this possible? I can't find a way to force this into a sheet view.

Thanks,
Joe

**Comment by GregularExpressions** [comment]
Hey @Joebayld 

This may be because the SDK isn't sure which window to attach the sheet to, can you try using the below to set it before calling deactivate please?

```obj-c
[[Paddle sharedInstance] setDevMainWindow:self.window];
```

Thanks,
Greg.

**Comment by Joebayld** [comment]
Ah! That did it! I must have missed that in the documentation.

Thanks,
Joe
