### ISSUE TITLE
showLicencing() does nothing on second call

### ISSUE THREAD

**Issue by JosephTurner** [PaddleHQ/Mac-Framework#140]
Hi,

When a trial has expired, the Paddle.showLicensing() method on the first call shows a dialog informing the user their trial has expired. This dialog itself doesn't have a cancel button, but the purchase and activation dialogs after it do. After the user cancels one of these dialogs, subsequent calls of showLicensing() do not seem to do anything. I'd expect it to show the same trial expired dialog as the first time the method is called. Can this functionality be achieved?

Many thanks,

Joseph

**Comment by GregularExpressions** [comment]
Hey @JosephTurner 

It sounds like something odd might be happening here, can you confirm the exact steps you're seeing please? A video would be ideal if it's not too much trouble.

Thanks,
Greg.

**Comment by Iomegan** [comment]
Same issue here.
[video](https://www.dropbox.com/s/ummwtwtjglatvzn/showLicencing%28%29%20does%20nothing%20on%20second%20call%20%23140.mov?dl=0)

**Comment by GregularExpressions** [comment]
Thanks @Iomegan !

**Comment by tunabelly** [comment]
This may be related to #148.
