### ISSUE TITLE
Licensing window without option to continue trial after license has been deactivated by the user.

### ISSUE THREAD

**Issue by Iomegan** [PaddleHQ/Mac-Framework#142]
Paddle v.3.0.22

- App has no time trial. (Trial is has limited features.)
- `timeTrial` is set to `false` in code and on Dashboard.
- `kPADTrialDuration` is set to `0`

If the user deactivates his license, `showLicencing()` and `startLicensing()` shows a window without the option to continue in the the trial mode. Instead there is a "Quit" button.

Before the license has been deactivated, `showLicencing()` and `startLicensing()` show the same window with the option to continue the trial.

Restarting the app does not help.

![ohne titel 2](https://user-images.githubusercontent.com/1634465/28449343-4318bfaa-6e33-11e7-804a-d581ec50d0fe.png)

**Comment by Iomegan** [comment]
https://github.com/PaddleHQ/Mac-Framework/issues/140 might be related

**Comment by GregularExpressions** [comment]
Hey @Iomegan 

Thanks for reporting this, we'll look into it and get back to you.

Thanks,
Greg.

**Comment by adriangranados** [comment]
It just happens that I've been working on adding the option to deactivate the license and I'm seeing the following behavior as well: in my app I'm using a time trial (set to 3 days) and after deactivating the license, sometimes it goes back to the trial window as if the trial period was starting (it says 3 days remaining) and sometimes it shows the window without the option to continue the trial (same as @Iomegan). The window also doesn't have a shadow. I haven't been able to find the combination of steps that would end up in one situation or another.

I'm also using Paddle v3.0.22.

**Comment by tunabelly** [comment]
If it helps, I've been seeing this random behaviour with older versions of the framework as well. Sometimes after deactivating, it will say to continue the trial and other times it won't. I can't seem to find a common theme either for when it happens.

**Comment by GregularExpressions** [comment]
Hi everyone,

Can you confirm if any of you are using `disableTrialResetOnDeactivate` please?

Thanks,
Greg.
