### ISSUE TITLE
Transaction search is broken for bundle purchases

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#146]
I don't know where to file issues with the web dashboard, so I'm putting it here. 

I have a customer who lost their license and I'm trying to find it in the dashboard by searching for "All Time" and "All Products" (this includes bundles). Nothing appears when searching with their email yet when I do a Spotlight search on my Mac, it shows up in a CSV file of customer purchases. They purchased a TG Pro + Disk Diet bundle.

It seems that searching on the web dashboard will not find transactions for certain bundles which is a bummer.

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

Thanks for reporting this, can you email me your example email and I'll look into this to find out if it's a bug or current feature limitation.

Thanks,
Greg.

**Comment by tunabelly** [comment]
@GregularExpressions I'm sorry I don't have the email right now. I'll see if I can look back through the support emails and find the one.

**Comment by GregularExpressions** [comment]
Closing as not currently reproduced and is a vendor dashboard issue.
