### ISSUE TITLE
After deregistering license, Paddle SDK returns productActivated=YES

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#147]
I'm having an odd problem. I was testing one of our apps that's getting updated and it now uses Paddle 3.0.23. I tried deactivating the license (it was already registered) and the call to deactivate returned properly and the trial over window appeared. I quit and re-opened the app and this is what the Paddle SDK is returning:

productActivated = YES
daysRemainingOnTrial = 0
verifyLicenceWithCompletionBlock returns verified = NO

It's a bit concerning that people can potentially still use one of our apps after deactivating.

**Comment by tunabelly** [comment]
@avalore I just sent the associated PADL file in case that helps.

**Comment by tunabelly** [comment]
Is this related to #149?

**Comment by tunabelly** [comment]
@GregularExpressions I can still reproduce this. I just deactivated a new build of TG Pro using the latest framework (3.0.25) and it's still returning YES for:

`[[Paddle sharedInstance] productActivated]; // returns YES when there's no license`

**Comment by GregularExpressions** [comment]
@tunabelly Thanks for this and the files, we'll look into it.

**Comment by GregularExpressions** [comment]
Hey @tunabelly, we believe we have a fix for this. It'll be in the next release (3.0.26).

**Comment by GregularExpressions** [comment]
[v3.0.27](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.26) is now released.
