### ISSUE TITLE
Customers are having to enter their license every time the Mac restarts

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#149]
I've had at least two customers complain that every time they restart their Mac, once TG Pro opens, it's prompting them to enter a license key as the "trial has expired". This seems to continue in a loop with the Paddle SDK never remembering the license key. 

I've cc'ed Paddle support for both of them, and so far the suggestion is that it may be fixed by
**A)** Updating to the latest Paddle SDK (which at least one of them has and it's still happening)
**B)** Clearing their web browser caches. I still don't understand how this would affect an app, although if someone could explain that it would be helpful to know.

This is occurring with Paddle SDK 3.0.23 which is concerning since they have the latest and greatest.

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

Apologies for the inconvenience to your users and yourself on this. We have two hypotheses as to cause at the moment:

1. Particularly old license (these can sometimes fail to verify and the SDK will get stuck in this loop)
2. NSTemp File Exceptions (i.e the user permissions / disk space / etc prevent us from writing to disk)

If you could arrange to email me the paddata.padl file I could verify if it is the first case, if it is then the 'fix' to break the loop is:

1. Close the app.
2. Delete the paddata.padl file
3. Open the app
4. Activate with their existing license

Thanks,
Greg.

**Comment by tunabelly** [comment]
@GregularExpressions OMG we are getting **swamped with angry customers**. You should see how many emails I have this morning from customers complaining that they have to re-enter their licenses each time they restart their Mac. We have 1000s of users of TG Pro - this is not good!

I'll try and get the PADL files from some of them and send them to you right away.

I seriously can't believe this is happening again...

**Comment by GregularExpressions** [comment]
@tunabelly Sorry to hear that, we'll do our best to help resolve.

**Comment by tunabelly** [comment]
@GregularExpressions @avalore I just sent the paddata.padl file from one of the affected customers to Louis' email. I hope this sheds some light on what went wrong.

I honestly wouldn't be that upset if this wasn't at the least the **3rd time this has happened** with different Paddle releases.

**Comment by tunabelly** [comment]
@avalore @GregularExpressions I've sent over two more padl files from customers that have taken the time to find and email them over.

This is getting worse - I have a new customer where it's loosing the license every time he restarts the Mac:

> Iv’e just bought TG Pro, downloaded and installed it. After that I typed in my mail address and the activation code that I got from you.
>  
> When I restart my Mac it’s trial version which starts up, and I have to activate it again. This also happens if I close TG Pro.
>  
> What can I do to keep the app activated all the time?

**Comment by tunabelly** [comment]
Guys, what the heck is going on?? I'm having more and more angry customers - this should be an absolute priority to get fixed! 

I've already sent the padl files that were requested from a number of customers.

**Comment by tunabelly** [comment]
Here is more info from a customer who took the time to try this out with no luck:

> I tried these steps but it still asks me to register again at reboot:
> 
> - Deleting TGPro using AppCleaner (screenshot attached)
> - Deleting default caches and perform routing maintenance using Cocktail (screenshots attached)
> - Power down/up
> - DL and re-install TGPro
> - Register TGPro
> - Reboot
>

**Comment by avalore** [comment]
@tunabelly this is absolutely being treat as a priority. Thank you for the .padl files you've sent through - these have been a big help. We're making sure we find the right fix.
If possible, could you ask any of these users if there is also a .padl file in `/Users/Shared/TG Pro` and if there is to also send that through.

**Comment by tunabelly** [comment]
@avalore I can ask them since I'm getting more every day. I got a great one today:

> In fact after restarting the app, it still show the first screenshot (Trial period).
> 
> So, I've spent 18$ but the app doesn't work to me.

**Comment by tunabelly** [comment]
@avalore I sent the .padl file that a customer just sent from /Users/Shared/TG Pro. Hope that helps so we can get a fix out.

**Comment by tunabelly** [comment]
Just got a lovely email from a very upset customer that emailed two days ago saying that it's continuously showing that it's in trial mode every time he restarts his Mac.

> Still no response from any one. C’mon guys I need this fixed.

**Comment by tunabelly** [comment]
Guys come on, where is the fix for this? It's been 5 days and the number of upset/angry customers is growing...

**Comment by tunabelly** [comment]
@avalore Good news - it appears the fix in Paddle 3.0.25 (pre-release) has resolved the issue so I'm glad that's fixed up. However, now we have a different issue (documented in #141) with other customers loosing their licenses after updating, which is honestly pissing them off quite a bit. It's been a disaster messaging this to customers without looking incompetent.
