### ISSUE TITLE
Crashes when calling showLicensing()

### ISSUE THREAD

**Issue by lvandal** [PaddleHQ/Mac-Framework#150]
Hi!

I have a user that is having an issue where the app crashes when he clicks on the Purchase button.

*** Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray replaceObjectsInRange:withObject:length:: Out of bounds'

And

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modal session requires modal window'

I do specify a valid window:

`Paddle.sharedInstance().startLicensing(productInfo, timeTrial: true, with: window)`

All I do in my code is this:

`Paddle.sharedInstance().showLicencing()`

I haven't changed any of my Paddle-related code for months. This just started to occur out of nowhere.

According to the crash reports, the crash occurs in the Paddle framework. I’ve updated to the latest version of the framework (3.0.24) and the issue is still present. Not sure if that changes anything but the user seems to be using Chinese localization.

I haven’t been able to recreate this issue.

[5622c113c49a8e63d78708899f4ed5ae.txt](https://github.com/PaddleHQ/Mac-Framework/files/1229428/5622c113c49a8e63d78708899f4ed5ae.txt)
[cce9a50d157a85b53068bde81b527d31.txt](https://github.com/PaddleHQ/Mac-Framework/files/1229429/cce9a50d157a85b53068bde81b527d31.txt)

**Comment by GregularExpressions** [comment]
Hey Luc,

Thanks for reporting this, we'll look into it - I presume it's just this one user experiencing the issue at present?

Greg.

**Comment by lvandal** [comment]
Hi Greg,

I had a few users having these crashes. Not many (3-4 total) took the time to report the crash so I don't know how many where actually affected.

**Comment by GregularExpressions** [comment]
Hey @lvandal I think [v3.30](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.30) should prevent the `NSRangeException` crash. Regarding the `NSInternalInconsistencyException` that's to do with the SDK attempting to present UI modally when something modal is already in place. There's a delegate method to allow you to handle the SDK's modal behaviour if/when you already have your own modal window, it's `- (BOOL)willPresentModalForWindow:(NSWindow * _Nullable )window`.
