### ISSUE TITLE
Web: Coupon text field is too hard to see/find

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#152]
We decided to send out an email to all TG Pro customers with an offer via a limited time coupon to help make up for the PR disaster that bugs #141 and #149 have caused.

Unfortunately, quite a few customers have emailed us back saying they could not find the field to enter the coupon in at checkout and therefore either didn't purchase or purchased at full price (without the coupon).

IMHO it would be better to have the coupon field more prominent. I've attached screenshots of what the checkout looks like on my 13" rMBP. Notice you can't see the "Add Coupon" button. Scrolling down, it becomes visible at the bottom of the checkout - however if the customer scrolls down enough to see and click the Continue button, they will miss the coupon button.

<img width="1278" alt="screen shot 2017-09-01 at 9 36 57 pm" src="https://user-images.githubusercontent.com/2223932/29991928-133fa2ca-8f5e-11e7-8582-977e5442f163.png">

<img width="1280" alt="screen shot 2017-09-01 at 9 40 19 pm" src="https://user-images.githubusercontent.com/2223932/29991935-305c8d64-8f5e-11e7-939d-4eaad9309107.png">

**Comment by GregularExpressions** [comment]
Thanks for the feedback @tunabelly our product team are currently looking at new design variants of the checkout and I've forwarded this feedback along.

**Comment by Iomegan** [comment]
That's why I always send them a checkout link with a coupon parameter
https://www.paddle.com/docs/checkout-links

**Comment by GregularExpressions** [comment]
Thanks for the suggested work around @Iomegan, I'm going to close this for now as the checkout team are aware and it's not an outstanding SDK issue.
