### ISSUE TITLE
White activation window if custom message contains apostrophe

### ISSUE THREAD

**Issue by Iomegan** [PaddleHQ/Mac-Framework#153]
To make it short:

This: `Paddle.sharedInstance().overridePrice("0", withCustomMessage: "Don't do this.", customProductName: nil)`

leads to: 
![ohne titel 2](https://user-images.githubusercontent.com/1634465/30263734-3bf5286a-972a-11e7-9c37-edc521b168f7.png)

This: `Paddle.sharedInstance().overridePrice("0", withCustomMessage: "Do this.", customProductName: nil)`

works fine:
<img width="474" alt="bildschirmfoto 2017-09-11 um 19 50 02" src="https://user-images.githubusercontent.com/1634465/30263785-715d04b4-972a-11e7-9f41-3ff5dde58f27.png">

**Comment by GregularExpressions** [comment]
Hey @Iomegan, thanks for reporting this. I've been able to replicate this end, I've raised it as a bug. Thanks.

**Comment by GregularExpressions** [comment]
This should be fixed as of 3.0.25 🎉
