### ISSUE TITLE
Web: Feedback from a customer

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#154]
I'm not sure where to put this so I'm adding it here since I'd like to have it documented somewhere. I believe this is valuable feedback from a real customer. I asked him what he thought could be better and what he liked about the Paddle checkout since he had some comments about it. Here is his detailed explanation:

> They have nice post-sale documentation, with the receipt and license key. It cute the way they use modern methods of triggering the mini-overlay screens to do the business, instead of having to go through a standard shopping cart old html-style shopping cart. It feels sleek and quick. What you are purchasing is nice and clear. 
> 
> * It has “email address”  as a field. That’s OK. 
> 
> * Remember this email is there as a checkbox, even without an email in the email field. It should say on click “Please enter the email you wish to use for this purpose” or “Please enter your email” 
> 
> * It breaks if you have larger text for accessibility
> 
> * it should probably say even before entering email “If you have used this email with paddle previously you will be able to login with your password, or reset it” Nothing like a bit of explanation, eh!
> 
> * on entering password “enter key” should work to continue
> 
> * I am now buying disk diet as an experiment (for the cause!)
> 
> * entered the password I think was reset to when buying folder tidy, but it is not correct. So evidently the code acts as a temporary password and the password didn’t actually update.
> 
> * Forgot Password says "Enter your email below and click the "Recover Password" button to start the reset process.” Either you recover your password or you reset it. It is no longer secure (if it ever was) to email passwords, so the only option is Reset, which is what the button should say!
> 
> * The 5 digit field comes up. I wait a while, then enter it. Presumably it accepts my new password this time. I’m not going to buy anything else at the moment. 
> 

Hopefully this helps out to improve the UX of the checkout.

**Comment by GregularExpressions** [comment]
Thanks for this @tunabelly I've forwarded it onto the checkout product team - I'm going to close for now as it's not an SDK issue.
