### ISSUE TITLE
What does forceLoadLicense do?

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#156]
I noticed a new method in the 3.0.25 release:

`- (void)forceLoadLicense;`

I wasn't able to find anything in the documentation about it. What does it do and when should it be called?

**Comment by GregularExpressions** [comment]
Hey @tunabelly, this was added for a specific vendor who was operating as a plugin and had some tricky license file read/write scenarios. This method forces a read of the license file from disk, it's not something you (or most vendors) should need to worry about.

Thanks,
Greg.

**Comment by tunabelly** [comment]
Ok thanks for letting us know.
