### ISSUE TITLE
How do you specify kPADProductImage?

### ISSUE THREAD

**Issue by stel** [PaddleHQ/Mac-Framework#158]
Where should the local image file be located inside the bundle and how should I specify it for `kPADProductImage`? Image from `Resources` directory doesn't seem to work or should I specify a relative path somehow? Is there a way to use `AppIcon` by default?

Thanks!

**Comment by GregularExpressions** [comment]
Hey @stel you specify `kPADProductImage` as a string from the main app bundle, you could set it to the filename of the AppIcon if desired. 👍

**Comment by stel** [comment]
Thanks for getting back, @GregularExpressions and sorry for delay on this. 

Unfortunately I still can't get it working, my product info dictionary looks like this:
```Swift
let productInfo = [
    kPADProductName: "Test",
    kPADProductImage: "AppIcon",
    kPADDevName: "Test Developer",
    kPADCurrentPrice: "99.99",
    kPADCurrency: "USD"
]
```

I also tried `AppIcon.icns`, `Resources/AppIcon`, etc and using `png` image as well – still no luck.

**Comment by GregularExpressions** [comment]
Hey @stel, internally the SDK looks for the string supplied using `NSImage imageNamed:` which checks in a [few places](https://developer.apple.com/documentation/appkit/nsimage/1520015-imagenamed). Greg.
