### ISSUE TITLE
Make PaddleAccelerateTrial stick in between debugging sessions

### ISSUE THREAD

**Issue by lvandal** [PaddleHQ/Mac-Framework#160]
Can you ensure that `PaddleAccelerateTrial` remains when relaunching the app while debugging? Right now, using that setting will make the trial expirer after 15 minutes unless you quit the app and relaunch it.

I want to be able to debug the app launch in trial expiration mode and right now it's not possible.

Thanks!

**Comment by GregularExpressions** [comment]
Hey @lvandal thanks for the feedback, this seems like a logical improvement. I'll get it added to the SDK backlog to be considered for future releases. Thanks, Greg.
