### ISSUE TITLE
Enhancement Request: Static Library

### ISSUE THREAD

**Issue by pixeleyesltd** [PaddleHQ/Mac-Framework#162]
There seems to be a common crack available, where the Paddle framework is replaced by a hacked framework that bypasses license activation. This seems to lower the bar to making a cracked application available. 

Just a thought, perhaps it's possible to introduce a static library, so it makes cracking the application just that little bit more difficult. I understand that perhaps using a bundle is required due to NIB and other resources, however with some build time creativeness it could be possible to compile those into a static library.

Here's someone who experimented with this concept: https://github.com/nielsbot/StaticLibraryXIB

**Comment by tunabelly** [comment]
@pixeleyesltd one thing I've been experimenting with is to check the code signing of the Paddle framework. If it's been modified after code signing or was signed with a different certificate, it's been pirated. 

Regardless, it's way too easy to get around the licensing in the Paddle framework for pirates.

**Comment by pixeleyesltd** [comment]
Are you using Apple's built in command line tools for this? Seems common to also replace these binaries with scripts that produce a successful exit status. Those sneaky pirates. 

I understand software will always be pirated once your app becomes popular, some people would rather spend time rather than money to get something working. Ideally Paddle just has to make it hard enough to crack, so that perhaps paying for the app is more preferable to time spent getting a pirated version working.

**Comment by tunabelly** [comment]
@pixeleyesltd very true. Right now it's way too easy to use a pirated version. If it was a bit more difficult, that should be good enough. 

If you'd like a example of the code, email me: matt at tunabelly dot com.

**Comment by GregularExpressions** [comment]
Hey @pixeleyesltd thanks for the info here, we do have a stop-gap static library that obfuscates the licensing methods to make it more difficult to reverse engineer. It doesn't address all the concerns but it may be better than nothing.

I'll share it with you.

**Comment by pixeleyesltd** [comment]
Cool - I'll check it out. Thanks @GregularExpressions !
