### ISSUE TITLE
Web: Stop forwarding customer emails when it's a bug in the Paddle framework

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#164]
It's getting a bit frustrating when customers email Paddle saying for example that they have to enter their license key after every restart. It's a bug in the Paddle framework (example #141) although they forward it to "the developer since they only handle the checkout process".

Also the customer's license key was un-useable since the activations were used up because of this bug. It would have been nice for Paddle to reset it for him. I had to go look it up and do that for him.

My suggestion is to have Paddle mention that it's a bug in their service/framework (**so it's clear it's not our fault**) and then include us in the conversation with the customer.

**Comment by GregularExpressions** [comment]
@tunabelly I agree, I'll co-ordinate with support on this.
