### ISSUE TITLE
Questions about resetTrialOnVersionUpdateForMajorOnly:onlyMajor

### ISSUE THREAD

**Issue by channing** [PaddleHQ/Mac-Framework#167]
1. What's this method's definition of "major version"? Does it check for `CFBundleVersion`, `CFBundleShortVersionString`, or something else?
2. 1.x versions of my app **don't** call this method. If I add it to 2.x, will it still be able to reset trial when a user update from 1.x to 2.x?
3. Is there a method to check if the trail ends? My app is a utility that runs in background. The "trial ends" dialog doesn't fully prevent it from functioning.

**Comment by GregularExpressions** [comment]
Hey @channing 

1. `CFBundleShortVersionString` but will check if it contains `.` and only check the major number. e.g. if that contains `2.3.4` it will just check `2`.

2. Yes, as long as your app's 1.x used `3.x` versions of the SDK.

3. Yes, it's `- (nonnull NSNumber *)daysRemainingOnTrial` and it can return negative numbers (the days beyond the trial end).

Hope that's helpful,
Greg.

**Comment by channing** [comment]
Thanks for your answer, Greg.

For 3), is it enough to use `daysRemainingOnTrial < 0` to check if the trial expires? Do I also need to check if there is a license activated?

**Comment by GregularExpressions** [comment]
Hey @channing, that's no problem. You should check `productActivated` in tandem as you suggest, `< 0` should be fine 👍
