### ISSUE TITLE
Unicode Dashes

### ISSUE THREAD

**Issue by charlieMonroe** [PaddleHQ/Mac-Framework#169]
I had a customer who reported to me that they can't use the following license (modified):

`B5AAAA7B-75BBBBB5–2CXXXX89–7BYYYYB8–10ZZZZBD`

The first dash is a regular dash, but the remainder are `EN DASH` unicode characters. It is extremely hard to spot and I don't know how they go there (most likely the "Smart Dashes" in macOS).

There's really just a few dash characters in Unicode, so I was wondering if this couldn't be handled automatically by replacing them with the regular dash (or actually the minus sign `U+002D`). Here's a list of the dashes:

- `SMALL EM DASH` - `U+FE58`
- `EM DASH` - `U+2014`
- `EN DASH` - `U+2013`
- `FIGURE DASH` - `U+2012`

**Comment by charlieMonroe** [comment]
BTW, this would be great if this got applied on server side as well (e.g. when looking up license in the vendor panel).

**Comment by GregularExpressions** [comment]
@charlieMonroe thanks for this, we agree it's a worthwhile improvement to catch this - even if it's just from a UX angle. I've added a ticket for the next major version to get this handled / improved.
