### ISSUE TITLE
Crash when calling showLicensing

### ISSUE THREAD

**Issue by lvandal** [PaddleHQ/Mac-Framework#170]
I'm still seeing crashes when calling that method.

`

             let paddle = Paddle.sharedInstance()

            if paddle.productActivated() {
                paddle.showLicencing()
            }
            else {
                paddle.showActivateLicence(with: self.libraryWindowController.window!)
            }
`

See attached crash.
[42a8a9bfc770180e2b71c44ff3a29f50.log](https://github.com/PaddleHQ/Mac-Framework/files/1488804/42a8a9bfc770180e2b71c44ff3a29f50.log)

**Comment by lvandal** [comment]
I'm using v3.0.28, BTW.

**Comment by GregularExpressions** [comment]
Hey @lvandal thanks for this, we have a theory about what's causing it - we're hoping to verify and fix it this week.

**Comment by GregularExpressions** [comment]
Hey @lvandal our theory here is that some of the expected licensing information is missing in some cases, do you know any specific users that have experienced the crash please? You can email them to me greg at paddle.com. Thanks, Greg.

**Comment by lvandal** [comment]
Sure, I'll send that shortly. This issue occurs when a user has an invalid (cracked) license.

**Comment by GregularExpressions** [comment]
This is fixed in [v3.30](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.30)
