### ISSUE TITLE
paddleDidFailWithError documentation

### ISSUE THREAD

**Issue by charlieMonroe** [PaddleHQ/Mac-Framework#171]
Hi,

here is my current issue:

- I had an app with some product ID and made a paid upgrade for it with another product ID
- there is some upgrade pricing and people who purchased the original app within some period get a free upgrade
- nevertheless, as people tend not to read emails thoroughly, they only see "free upgrade" and rush to enter their original license into the new app and it doesn't work - of course, since it's a license for another product

I was hoping to see some delegate method that would notify me when the activation fails so that I can suggest something to the user. I've found `paddleDidFailWithError:` delegate method, however, there is quite lack of documentation for it and it's not entirely self-explanatory. Paddle did fail doing what with error?

I have implemented this method and it did not get called when the activation failed. When exactly does this method get called? Is there something I may do to get notified about failed activation?

Thanks!

**Comment by GregularExpressions** [comment]
Hey @charlieMonroe 

`paddleDidFailWithError:` is currently only for hard errors, like the API returning an unexpected response for example.

To get more information on activation attempts there are some variations of the `showActivateLicence` methods that include completion blocks, like:

`- activateLicence:licenceCode email:email withCompletionBlock:completionBlock`

If you need to specify an alternative product ID to the initialisation SDK product then you can use the child product variant - it's not restricted to child products specifically:

`- activateLicence:licenceCode email:email forChildProduct:childProductId withCompletionBlock:completionBlock `

Thanks,
Greg

**Comment by charlieMonroe** [comment]
Hi @GregularExpressions ,

thanks for the info, however, it only helps partially. I would need to come up with custom UI for licensing. Currently when you call `-startLicensing: timeTrial:withWindow:`, Paddle will automatically open the licensing UI and there is no way to catch such events in this case. I'd need to use the silent licensing, do all the UI and activation myself...

Not that it would be a great big of deal, I was just hoping to see an easier solution.

The upgrade strategy is still something I lack in the SDK or in Paddle in general - the ability to define previous product from which the user is able to upgrade, including some minor upgrade conditions (e.g. timeframe for when the upgrade is free). I'm not saying this is something easily achievable, but I don't think I'm alone here with paid upgrades.

It would help enourmously just to have one of these two options:

**1) Set previous product IDs.**
`Paddle.sharedInstance().setPreviousProductIDs(["123", "345"], informationURL: URL(string: "http://example.com/upgrade_info/"))`

-- or perhaps this can be set up on the server side. And when a user tries to activate the product with previous product ID, they will be told that this is a paid upgrade and for more information a link will be opened.

**2) Have an API for a license check.**

Currently, you can check whether a license is valid. But the app needs to be already licensed with that license in order for that to work. There is no way to take the license and ask Paddle whether it's a valid license and what product is it for. This is a general issue in the Vendor's Panel as well - a user sends me a license, asking for anything about it - if they don't include additional information, I can't look up:

- which product this is for
- when the license was generated
- how it was generated (regular purchase, API, license batch, ...)

As I have Downie 1, Downie 2 and Downie 3, I need to make 3 searches to figure out which app the license is for. And as I offer a free upgrade to Downie 3 for users who purchased the app after Mar 1, 2017, I need to know when is this license from. I guess this by looking on the activations, but it's not precise, nor is it usable automatically from PHP or the app itself.


--------------------

Currently, if you release a paid upgrade, it's all in the hands of the developer and having done this twice already, I have to say that the experience is not all that pleasant. There's a lot of stuff that needs to be done manually - for example, in order to offer users discount, you need to create a database of users, when they purchased it, then use the coupon API, etc.

If there was an API to make a check based on the license, it would be much much easier.

Sorry that I got sidetracked a little bit, but I think all these pieces are kind of connected. I think that Paddle should develop an upgrade strategy for products or a way to make this easier for developers.

**Comment by GregularExpressions** [comment]
Hey @charlieMonroe thanks for the detailed write up, it's very helpful. I've added it to our feature requests and we'll look at how we can make this better in future.
