### ISSUE TITLE
"No write key" displayed in console 1000's of times

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#173]
I'm not 100% sure this is a Paddle issue although from my searching it may very well be. People are complaining that the message "No write key" is being displayed in the console, from TG Pro over and over. It turns out people have found this with other developer's apps, so it's not just ours. There's nothing in our code that prints this to the console. It seems it may have to with the Paddle code trying to connect to analytics.paddle.com and if that's blocked, it will print out that message to the console, repeatedly.

See https://www.tapforms.com/forums/topic/console-message-no-write-key/

If this is something the Paddle code is doing, please get this fixed in the next release since this should be an extremely quick and easy fix.

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

Yes this is a message of ours, it'll occur when the end user has blocked connections to our analytics platform before we've been able to request our analytics write key for their particular project (as you alluded to).

We agree it could be a lot less frequent, we'll reduce it to something like once per launch for the next v3 release.

Thanks,
Greg.

**Comment by tunabelly** [comment]
@GregularExpressions thanks for clarifying that and working on a fix. When can we expect the next release? We desperately need to do a TG Pro update, specifically to include an updated Paddle framework since it's causing the majority of the bugs and crashes in the app. I don't want to do an update today to find out there is another release tomorrow. On the flip side if it's going to be longer than a few days, we can't wait any longer. 

Please advise. Thanks.

**Comment by GregularExpressions** [comment]
@tunabelly if everything goes to plan the next v3 update will be this week 👍

**Comment by tunabelly** [comment]
@GregularExpressions ok sounds good, thanks for the update. I'll wait until Friday for the next v3 release. If it's not out, I'll have no choice but to issue back-to-back TG Pro updates which will for sure upset a whole bunch of customers. 

Please try your best to get this fixed and #172 so we can give our customers a better experience.

**Comment by tunabelly** [comment]
@GregularExpressions any update on when we'll see a release with fixes for this, #172 and #175? It's been almost another week.

**Comment by GregularExpressions** [comment]
@tunabelly Apologies for the delay, the work is complete on these and there will be a release imminently.

**Comment by GregularExpressions** [comment]
@tunabelly v3.30 reduces this to once per launch.
