### ISSUE TITLE
Delegate method licenceDeactivated changed without warning / code no longer works

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#174]
So here I am, trying to figure out why when people deactivate a license in TG Pro, they get the generic "License deactivated" dialog that's not nice looking at all. We have a nice looking one with a more informative message - however it's no longer being displayed.

Looking into this, it turns out the method signature for the Paddle **licenceDeactivated delegate method changed with no mention** of this in the changelog/release notes. So existing code will never be called which is why our custom dialog never shows anymore. If existing API method signatures are going to change, THIS NEEDS TO BE DOCUMENTED and CONVEYED TO THE DEVELOPERS. 

I'm pretty annoyed at having to waste time hunting down a bug like this.

**Comment by avalore** [comment]
Hey Matt, 

Sorry to hear about your frustrations debugging this issue - we certainly should have communicated the change to you much better. We can’t apologise enough for the time wasted, and poor experience some of your users received.

The change was documented in [these release notes](https://github.com/PaddleHQ/Mac-Framework/blob/master/CHANGELOG.md), but wholly understand how this could be missed, and should have been more pertinent to yourself (+ other sellers!).  In future any similar changes will only be included in major updates to the SDK, with fair warning as well as being marked in the headers.
