### ISSUE TITLE
Crash when running on MacPro6,1

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#175]
It appears that when running on a MacPro6,1 there is a bug in the Paddle framework (found with 3.0.25 - not sure if it exists in latest version) that may not be fixed.

The exception is: `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: HW.GPU_MODEL)'`

The crashlog isn't symbolized and I don't know why this happens for this customer (I don't have any more info about the customer so can't contact him/her), so I apologize if it makes it harder to decipher.

I've attached the crashlog and if this is still an issue, please fix it.
[71da97cb909cf97e7c443ff3f34a0fc8.log.txt](https://github.com/PaddleHQ/Mac-Framework/files/1546437/71da97cb909cf97e7c443ff3f34a0fc8.log.txt)

**Comment by avalore** [comment]
Thanks for reporting this. We have a fix for this in place for the next release.

**Comment by GregularExpressions** [comment]
This has been fixed in [v3.30](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.30).
