### ISSUE TITLE
Customer losing license with Paddle 3.0.29

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#176]
To be honest, I'm getting really upset with the number of times I have to file this bug and how many updates we're had to issue to include Paddle framework updates.

I've replied to the customer and cc'ed Paddle support and @GregularExpressions.

Here is his original email:

> Yesterday morning I downloaded Version 2.28 of TG Pro and immediately entered the license key when asked. I got the thank you for purchase and registering the app message as before. This time around, the first three times I restarted my laptop after having shut it down, TG Pro retained my license key (I checked the about TG Pro window) and did not revert to a trial mode. However, this evening (the fourth time shutting down after installing version 2.28) upon restarting my laptop, TG Pro reverted to trial mode. I checked the about TG Pro window and found that the license key was gone. A subsequent restart of my laptop confirmed the absence of the license key.
> 
> Hope this helps you find the problem. I have found the preference page where TG Pro was set to always start up on login and changed that. So, I can wait out your Paddle problem without the aggravation of dealing with the trial mode start up.

**Comment by GregularExpressions** [comment]
The License key had been copied from a PDF and retained a `\r` character that was causing it to fail remote validation and be purged. We'll look into catching extraneous characters better in future.
