### ISSUE TITLE
Trial not expiring, remaining days don't decrease

### ISSUE THREAD

**Issue by dokterdok** [PaddleHQ/Mac-Framework#177]
I have a case where the trial days are not decreasing and stay indefinitely stuck at the initial default trial period of 7 days, pretty much like I was running a cracked version.
This is with 3.0.29, macOS 10.13.2, public build (17C88).  It happened on a fresh install of the app, without a reboot. I haven't set any `PaddleAccelerateTrial` or `PaddleResetTrial` keys in case that's relevant.

Any idea what could be causing this?

**Comment by GregularExpressions** [comment]
Hey @dokterdok, sorry to hear you're having problems - thanks for reporting.

We're not sure what could be causing this at present, does a licensing file exist at the below path?

`~/Library/Application Support/<app name>/paddata.padl`

If so could you email it to me please, it's greg at paddle.com.

Thanks,
Greg.

**Comment by GregularExpressions** [comment]
Hey @dokterdok 

Would you mind elaborating on the case please? Is this in your development environment or with an end user? 

We have seen behaviour like this before when `PaddleAccelerateTrial` and `PaddleResetTrial` are used and the productID is amended - does that sound feasible?

Thanks,
Greg.

**Comment by dokterdok** [comment]
Hey Greg,

I've experienced this on my testing environment. That means that I'm regularly installing, updating, testing, uninstalling various versions of my app, but there are no specific use cases I can think of that a regular user wouldn't ever be doing.
When I type _defaults read ch.tripmode.TripMode_ (my app bundle id) the output doesn't show any references to Paddle keys. I haven't ever set Paddle keys on the machine I'm using for testing.
The last significant action I did was uninstall then reinstall my app via its included [uninstall script (temp link)](tripmode.ch/Uninstall.command). Could it be that something affects Paddle in this process?

If you'd like to give it a go, [here's the build](http://www.tripmode.ch/app/TripMode-2.1.1-589-app-Release.dmg) of my app where I see the issue (temp link). I've also asked other people in our team to see if they can reproduce the issue.

Not sure what you mean with productID amended?  

Thanks
David

**Comment by avalore** [comment]
Hey @dokterdok 
    Could you set the value `PaddleLoggingEnabled` to true in your apps `NSUserDefaults` and then send us the contents of your console after running the app again?

`defaults write ch.tripmode.TripMode PaddleLoggingEnabled -bool YES`

**Comment by dokterdok** [comment]
Sure. Here's what I have when running TripMode and going to the About screen (where we display the remaining trial days):

Console output when filtering for Paddle:
```
default	14:23:48.940375 +0100	TripMode	Paddle All Keys Setup
default	14:23:48.946967 +0100	TripMode	Paddle Start Silent Licencing
default	14:23:48.947049 +0100	TripMode	Paddle Set Default Product Data
default	14:23:49.908699 +0100	TripMode	PADProduct Received Product Data
```

Console output when filtering for TripMode:
```default	14:23:48.854276 +0100	launchservicesd	CHECKIN:0x0-0x130130 4239 ch.tripmode.TripMode
error	14:23:48.921365 +0100	TripMode	        AEGetDescData of non-desc type 'reco' not a good idea
default	14:23:48.940375 +0100	TripMode	Paddle All Keys Setup
default	14:23:48.946967 +0100	TripMode	Paddle Start Silent Licencing
default	14:23:48.947049 +0100	TripMode	Paddle Set Default Product Data
default	14:23:48.948285 +0100	TripMode	Faulting in NSHTTPCookieStorage singleton
default	14:23:48.950301 +0100	TripMode	Faulting in CFHTTPCookieStorage singleton
default	14:23:48.950648 +0100	TripMode	Creating default cookie storage with process/bundle identifier
default	14:23:48.952375 +0100	TripMode	Previous run 2.1.1, current run 2.1.1, upgrade = false
default	14:23:48.953078 +0100	TripMode	TIC Enabling TLS [1:0x60400017ac40]
default	14:23:48.953118 +0100	TripMode	TIC TCP Conn Start [1:0x60400017ac40]
default	14:23:48.953659 +0100	TripMode	Task <8979D7B2-783A-40BF-B6B7-83147781F594>.<1> setting up Connection 1
default	14:23:48.953965 +0100	TripMode	TIC Enabling TLS [2:0x60400017cc80]
default	14:23:48.955465 +0100	TripMode	TIC TCP Conn Start [2:0x60400017cc80]
default	14:23:48.957191 +0100	TripMode	Task <6DBC8498-5FB8-4223-A664-A5064F97FFA1>.<2> setting up Connection 2
default	14:23:48.994769 +0100	TripMode	TIC TLS Event [1:0x60400017ac40]: 1, Pending(0)
default	14:23:49.005312 +0100	TripMode	TIC TLS Event [2:0x60400017cc80]: 1, Pending(0)
default	14:23:49.018660 +0100	TripMode	TIC TLS Event [1:0x60400017ac40]: 2, Pending(0)
default	14:23:49.024225 +0100	TripMode	Helper tool version 1.1.0 589
default	14:23:49.024626 +0100	TripMode	KEXT version 2.0.0
default	14:23:49.037054 +0100	TripMode	TIC TLS Event [1:0x60400017ac40]: 11, Pending(0)
default	14:23:49.038698 +0100	TripMode	TIC TLS Event [2:0x60400017cc80]: 2, Pending(0)
default	14:23:49.038932 +0100	TripMode	TIC TLS Event [1:0x60400017ac40]: 12, Pending(0)
default	14:23:49.042586 +0100	TripMode	TIC TLS Event [2:0x60400017cc80]: 11, Pending(0)
default	14:23:49.042629 +0100	TripMode	TIC TLS Event [1:0x60400017ac40]: 14, Pending(0)
default	14:23:49.043632 +0100	TripMode	TIC TLS Event [2:0x60400017cc80]: 12, Pending(0)
default	14:23:49.044651 +0100	TripMode	TIC TLS Event [2:0x60400017cc80]: 14, Pending(0)
default	14:23:49.056227 +0100	TripMode	System Trust Evaluation yielded status(0)
default	14:23:49.064567 +0100	TripMode	TIC TLS Trust Result [1:0x60400017ac40]: 0
default	14:23:49.071812 +0100	ch.tripmode.TripMode.HelperTool	Exit requested by client
default	14:23:49.074943 +0100	TripMode	System Trust Evaluation yielded status(0)
default	14:23:49.086683 +0100	TripMode	TIC TLS Trust Result [2:0x60400017cc80]: 0
default	14:23:49.090784 +0100	TripMode	TIC TLS Event [1:0x60400017ac40]: 20, Pending(0)
default	14:23:49.090900 +0100	TripMode	TIC TCP Conn Connected [1:0x60400017ac40]: Err(16)
default	14:23:49.091318 +0100	TripMode	TIC TCP Conn Event [1:0x60400017ac40]: 1
default	14:23:49.091597 +0100	TripMode	TIC TCP Conn Event [1:0x60400017ac40]: 8
default	14:23:49.091693 +0100	TripMode	TIC TLS Handshake Complete [1:0x60400017ac40]
default	14:23:49.098617 +0100	TripMode	Task <8979D7B2-783A-40BF-B6B7-83147781F594>.<1> now using Connection 1
default	14:23:49.098840 +0100	TripMode	Task <8979D7B2-783A-40BF-B6B7-83147781F594>.<1> sent request, body S
default	14:23:49.109466 +0100	TripMode	TIC TLS Event [2:0x60400017cc80]: 20, Pending(0)
default	14:23:49.110151 +0100	TripMode	TIC TCP Conn Connected [2:0x60400017cc80]: Err(16)
default	14:23:49.110657 +0100	TripMode	TIC TCP Conn Event [2:0x60400017cc80]: 1
default	14:23:49.110680 +0100	TripMode	TIC TCP Conn Event [2:0x60400017cc80]: 8
default	14:23:49.110702 +0100	TripMode	TIC TLS Handshake Complete [2:0x60400017cc80]
default	14:23:49.111058 +0100	TripMode	Task <6DBC8498-5FB8-4223-A664-A5064F97FFA1>.<2> now using Connection 2
default	14:23:49.111242 +0100	TripMode	Task <6DBC8498-5FB8-4223-A664-A5064F97FFA1>.<2> sent request, body S
default	14:23:49.124430 +0100	TripMode	Connected to Kernel Extension version 2.0.0
default	14:23:49.145191 +0100	TripMode	Check for updates in background
default	14:23:49.149736 +0100	TripMode	Profile: Found latest sample 2018-01-04 13:21:53 +0000
default	14:23:49.150289 +0100	TripMode	Profile: profile traffic has never been reset
default	14:23:49.151823 +0100	TripMode	Rescheduling reset timer, last=2001-01-01 00:00:00 +0000, next=nil type=manual
error	14:23:49.152787 +0100	TripMode	Scheduling the NSURLDownload loader is no longer supported.
default	14:23:49.180861 +0100	TripMode	HelperClient: HelperTool connection invalidated
default	14:23:49.181353 +0100	TripMode	Connection to helper invalidated, error = Error Domain=NSCocoaErrorDomain Code=4099 "Couldn’t communicate with a helper application."
default	14:23:49.181705 +0100	TripMode	Cancelling reset timer source
default	14:23:49.181707 +0100	TripMode	TIC Enabling TLS [3:0x600000360e40]
default	14:23:49.181762 +0100	TripMode	TIC TCP Conn Start [3:0x600000360e40]
default	14:23:49.181918 +0100	TripMode	Task <1CD33FC6-725B-41D5-B2D8-A1EE7D55A049>.<0> setting up Connection 3
default	14:23:49.241347 +0100	TripMode	TIC TLS Event [3:0x600000360e40]: 1, Pending(0)
default	14:23:49.274248 +0100	TripMode	TIC Enabling TLS [4:0x600000361b00]
default	14:23:49.274298 +0100	TripMode	TIC TCP Conn Start [4:0x600000361b00]
default	14:23:49.274533 +0100	TripMode	Task <A86A9F21-2938-4699-ADBD-CE3E5B99686A>.<1> setting up Connection 4
default	14:23:49.296660 +0100	TripMode	TIC TLS Event [3:0x600000360e40]: 2, Pending(0)
default	14:23:49.310441 +0100	TripMode	TIC TLS Event [3:0x600000360e40]: 11, Pending(0)
default	14:23:49.313214 +0100	TripMode	TIC TLS Event [3:0x600000360e40]: 12, Pending(0)
default	14:23:49.314376 +0100	TripMode	TIC TLS Event [3:0x600000360e40]: 14, Pending(0)
default	14:23:49.323670 +0100	TripMode	System Trust Evaluation yielded status(0)
default	14:23:49.329526 +0100	TripMode	TIC TLS Trust Result [3:0x600000360e40]: 0
default	14:23:49.329586 +0100	TripMode	TIC TLS Event [4:0x600000361b00]: 1, Pending(0)
error	14:23:49.348505 +0100	TripMode	Function nw_protocol_boringssl_input_finished: line 1386 Peer disconnected during the middle of a handshake. Sending errSSLFatalAlert(-9802) alert
default	14:23:49.350251 +0100	TripMode	TIC TCP Conn Event [4:0x600000361b00]: 3
error	14:23:49.350379 +0100	TripMode	TIC TCP Conn Failed [4:0x600000361b00]: 3:-9802 Err(-9802)
default	14:23:49.350501 +0100	TripMode	TIC TCP Conn Cancel [4:0x600000361b00]
default	14:23:49.350836 +0100	TripMode	NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
error	14:23:49.350905 +0100	TripMode	Task <A86A9F21-2938-4699-ADBD-CE3E5B99686A>.<1> HTTP load failed (error code: -1200 [3:-9802])
error	14:23:49.351065 +0100	TripMode	Task <A86A9F21-2938-4699-ADBD-CE3E5B99686A>.<1> finished with error - code: -1200
default	14:23:49.357223 +0100	TripMode	Deleted obsolete history, 0 items
default	14:23:49.368530 +0100	TripMode	TIC TLS Event [3:0x600000360e40]: 20, Pending(0)
default	14:23:49.368646 +0100	TripMode	TIC TCP Conn Connected [3:0x600000360e40]: Err(16)
default	14:23:49.369113 +0100	TripMode	TIC TCP Conn Event [3:0x600000360e40]: 1
default	14:23:49.369193 +0100	TripMode	TIC TCP Conn Event [3:0x600000360e40]: 8
default	14:23:49.369288 +0100	TripMode	TIC TLS Handshake Complete [3:0x600000360e40]
default	14:23:49.369886 +0100	TripMode	Task <1CD33FC6-725B-41D5-B2D8-A1EE7D55A049>.<0> now using Connection 3
default	14:23:49.370026 +0100	TripMode	Task <1CD33FC6-725B-41D5-B2D8-A1EE7D55A049>.<0> sent request, body N
default	14:23:49.426612 +0100	TripMode	Task <1CD33FC6-725B-41D5-B2D8-A1EE7D55A049>.<0> received response, status 200 content K
default	14:23:49.427255 +0100	TripMode	Task <1CD33FC6-725B-41D5-B2D8-A1EE7D55A049>.<0> response ended
default	14:23:49.907017 +0100	TripMode	Task <6DBC8498-5FB8-4223-A664-A5064F97FFA1>.<2> received response, status 200 content U
default	14:23:49.907879 +0100	TripMode	Task <6DBC8498-5FB8-4223-A664-A5064F97FFA1>.<2> response ended
default	14:23:49.908473 +0100	TripMode	Task <8979D7B2-783A-40BF-B6B7-83147781F594>.<1> received response, status 200 content U
default	14:23:49.908699 +0100	TripMode	PADProduct Received Product Data
default	14:23:49.909055 +0100	TripMode	Task <8979D7B2-783A-40BF-B6B7-83147781F594>.<1> response ended
default	14:23:52.028463 +0100	TripMode	Using sample 536503245.559401 as counter start
default	14:23:53.786589 +0100	TripMode	Task <264831D5-54FA-4723-83D3-6659998ECA47>.<0> now using Connection 3
default	14:23:53.786836 +0100	TripMode	Task <264831D5-54FA-4723-83D3-6659998ECA47>.<0> sent request, body N
default	14:23:53.888671 +0100	TripMode	Task <264831D5-54FA-4723-83D3-6659998ECA47>.<0> received response, status 200 content K
default	14:23:53.889372 +0100	TripMode	Task <264831D5-54FA-4723-83D3-6659998ECA47>.<0> response ended
default	14:23:58.868512 +0100	TripMode	LSExceptions shared instance invalidated for timeout.
default	14:24:08.954694 +0100	TripMode	TIC TCP Conn Event [3:0x600000360e40]: 2
default	14:24:08.954745 +0100	TripMode	TIC TCP Conn Cancel [3:0x600000360e40]
```

**Comment by avalore** [comment]
Thanks @dokterdok we're looking into it and will get back to you

**Comment by avalore** [comment]
@dokterdok It does indeed seem to be related to the "month 13 out of bounds" issue, which has recently been introduced to a core framework, which happens when writing to file in some scenarios in 10.13.1

Can you confirm which versions of Xcode and macOS you're using?

**Comment by dokterdok** [comment]
TripMode 2.1.1 (link I shared with you) => macOS 10.13.1 build 17B1003,  Xcode 9.2 build 9C40b, Paddle 3.0.29
TripMode 2.0.3 (public release) => macOS 10.12.6 build 16G29, Xcode 9 beta 3 build 9M174d, Paddle 3.0.22

From our dev:
> Month 13 out of bounds seems to have appeared in 10.13 (“.0”)
> Some devs traced it to an assert warning in (IIRC) CoreFoundation, it does not seem to be the result of a bug in app code but in the system frameworks.

**Comment by legerl** [comment]
Location of the assert in CoreFoundation (CFDate):
https://github.com/apple/swift-corelibs-foundation/blob/master/CoreFoundation/NumberDate.subproj/CFDate.c#L228

**Comment by dokterdok** [comment]
FYI, we're testing a debug build of our app with silent licensing disabled. When the trial window shows up, the console outputs this:

```default	08:53:10.205306 +0100	TripMode	Paddle Show Trial Window: TimeTrial BLANK - Set Time```

Is that normal?
As I just installed this debug version today, I can't tell yet if the trial days are decreasing normally.

**Comment by avalore** [comment]
@dokterdok does it do this on every launch? If it does then it's the CFDate bug in the system frameworks (we're looking into a fix for this)

**Comment by GregularExpressions** [comment]
hey @dokterdok we think we might have a workaround solution for this, can you drop me an email to greg at paddle dot com and I'll reply with instructions. Thanks.

**Comment by dokterdok** [comment]
@avalore no, I launched our debug build today (has silent licensing disabled) and the days countdown appears to work. Console produces this:

```
default	15:11:28.257707 +0100	TripMode	Paddle Show Trial Window: TimeTrial AND Time Set
```

**Comment by legerl** [comment]
I did some tests in a 10.12.6 VM (16G29). Our app is compiled with the latest public Xcode (v9.2 9C40b) running on macOS 10.13.2 (17C205). 
Please note that our app is a menu bar application, so there is no MainWindow and the Dock icon is hidden as well. The licensing call is one of the very first things executed on startup in applicationDidFinishLaunching()

### Using startLicensingSilently()
Code stays the same, runs are started after a clean wipe of all files, as per the mail sent by @GregularExpressions 

- With the Paddle framework <= v3.0.11:
the PaddleT entry in the app's preferences is not written on startup, but gets written after trying to buy the product and cancelling. The trial window appears just after clicking on cancel in the buy dialog. 

- With a newer version (tested .12, .14, .20, .29 and .30):
No PaddleT entry is written in any case. Trial window never appears after trying to purchase then cancelling. 

**Note:** After installing the app with a framework > 3.0.11, trial is reset (7 days in our case). If rolling back from this point, even with complete wipe, to 3.0.11, the trial expires. 

### Using startLicensing()
Changed only the licensing start method. 
With 3.0.30, licensing window does not appear on startup, but PaddleT writing occurs in the same conditions as <= 3.0.11

### Using startLicensing() + showLicencing()
Licensing window shows as requested, PaddleT gets written and the whole process seems to start it should. 

So we may be missing something critical here, or triggering a side effect with our uncommon setup. 
Can you confirm if calling Paddle.sharedInstance().startLicensing() / startLicensingSilently() is enough to correctly bootstrap the whole process or if we must call the licensing window for the trials to start ?

**Comment by GregularExpressions** [comment]
Hey @dokterdok & @legerl 

Thanks for your help with this, we believe we've found the issue and have prepared [a release](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.31)

Yet us know if you continue to have issues.

Thanks,
Greg.

**Comment by dokterdok** [comment]
Hi guys,
Thanks. We've tested the new framework version and the issue appears to be fixed. We're releasing a new version soon. Let's hope this didn't negatively affect sales too much, we'll be keeping a close eye on the numbers on our vendor platform.
Cheers
David

**Comment by GregularExpressions** [comment]
Hey @dokterdok 

I'm glad to hear the issue appears resolved, we believe it will only have manifested on macOS 10.13 and that those users should have just had the luxury of an extended trial. Hopefully any interested parties will continue to go ahead and purchase when their trial does finally end 👍

Thanks,
Greg.
