### ISSUE TITLE
Adding the framework to a particular project causes a crash (Paddle 3.0.30 - Xcode 9.2 Swift 4)

### ISSUE THREAD

**Issue by Televisorino** [PaddleHQ/Mac-Framework#179]
Hi there!
I tested the framework in a testing project and it worked fine, then I added it in a project that is a menu bar app (similar to [this one](https://www.raywenderlich.com/165853/menus-popovers-menu-bar-apps-macos) by raywenderlich.com) but it crashes.

> dyld: Library not loaded: @rpath/Paddle.framework/Versions/A/Paddle
>   Referenced from: /Users/metal/Library/Developer/Xcode/DerivedData/AppMenu-fhlvvmhhpaumszdqzxkvfwcfzbgm/Build/Products/Debug/App Menu.app/Contents/MacOS/App Menu
>   Reason: image not found
> (lldb) 

<img width="877" alt="sshot" src="https://user-images.githubusercontent.com/4642045/34714868-0f469d30-f52b-11e7-94a9-ad39b8383f13.png">

**Comment by GregularExpressions** [comment]
Hey @Televisorino 

Sorry to hear you're having issues, can you confirm you've completed the copy files build phase from the [SDK docs](https://paddle.com/docs/sdk-setup-mac) please?

Thanks,
Greg.

**Comment by Televisorino** [comment]
Hy @Greg,

Thank you for the replay. Yes I completed the copy files phase. There are two items: the helper app that has to launch the app at startup and Paddle.framework. Anyway the crash happens when running the app in Xcode, I have not compiled as app yet. I can provide you privately with the project if you need it.

**Comment by Televisorino** [comment]
Hi @greg,

Just discovered that was missing to select "Frameworks" as destination (it was "Wrapper" becouse the other item). Now I created a new Copy Files Phase specific for the Paddle framework and set destination as Framework and it works fine. I'm sorry for wasting your time.

Keep up with the good work!

**Comment by GregularExpressions** [comment]
@Televisorino that's no problem, thanks for letting us know what the solution was!
