### ISSUE TITLE
Triage & answer emails for customers that never got license keys after purchasing

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#180]
I just had a customer complain that he never got the license keys after purchasing a 2 app bundle from our website. The reason was, as I just discovered is that he mistyped his email address on checkout. 

He emailed Paddle to ask why he never received what he purchased and nothing was done. In his words:  

> I have even contacted this email on 11/20/2017 with no resolution but what was even more disturbing was that I received an email to rate the support when nothing was done. Any help is greatly appreciated!

I understand that some emails can slip through and get lost although in a big company like Paddle with lots of resources I would expect that these types of emails should be 1st priority and never get missed.

PS. If we had a public facing ticket system for the Paddle service & web dashboard that would be a better place to file things like this.

**Comment by GregularExpressions** [comment]
@tunabelly sorry to hear that, if you wouldn't mind emailing me some details about the customer I'll investigate with support.

**Comment by tunabelly** [comment]
@GregularExpressions I can't find the customer's email right now since I already closed the ticket. If I find it again, I'll let you know.

This issue isn't really specific to this user. I've noticed when I cc Paddle support it can take days for a customer to get a reply. To be honest sometimes it can take me a few days to clear our support tickets, but Paddle is a way bigger company that just got 12.5M in investment. You guys can do better!

**Comment by GregularExpressions** [comment]
@tunabelly sure, if you do manage track it down we might be able to investigate that case specifically.

We're investing time and money in scaling and improving all our departments (including support), you should see response time improve as we refine and optimise the processes.
