### ISSUE TITLE
Crash on macOS 10.9 in the Paddle framework

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#181]
I have a customer who is reporting that on macOS 10.9 with Paddle 3.0.29 he is experiencing a crash every time the app launches. I've attached the crash report he sent. 

It appears the Paddle framework is crashing trying to unarchive an object, so maybe a license key or some other type of data. I've asked the customer to remove a folder in Application Support that has the Paddle files to see if this resolves the issue so he doesn't have to wait for a fix.
[TG Pro crash info.pdf](https://github.com/PaddleHQ/Mac-Framework/files/1682410/TG.Pro.crash.info.pdf)

**Comment by GregularExpressions** [comment]
Hey @tunabelly thanks for the report, please keep me updated on if removing the Application Support directory solves the problem or not.
