### ISSUE TITLE
No way for customers to deactivate computers that they no longer have

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#182]
This has been a long standing issue that never seemed to have gotten fixed. I have customers on a regular basis that need their license key activation counts bumped up because they are at their limit and have no way to deactivate old Macs that they no longer have, or from an OS reinstall.

There really needs to be a way for customers to blanket wide deactivate all existing Macs so it will reset their license count to zero. iTunes/Apple has this and it's an essential part to having a complete licensing system.

**Comment by GregularExpressions** [comment]
Hey @tunabelly we agree that some user level license management would be good, but it's not currently a priority so I wouldn't expect it in the short to medium term.

I have forwarded it onto to the relevant Product Manager so they know it's being requested.

For the record, the SDK does support deactivations if the user considers their activations before uninstalling / formatting, however it's likely a large percentage will not 🙂

In the meantime our support team will be happy to field requests for this from your end users but I appreciate that this is slower than a self serve solution would be.

Thanks,
Greg.
