### ISSUE TITLE
3.0.32 messing up existing licenses!

### ISSUE THREAD

**Issue by markmunz** [PaddleHQ/Mac-Framework#188]
I recently updated my app's Paddle.framework (3.0.19 -> 3.0.32) and all my beta users are now complaining that the licensing is messed up.

1. The existing license is not recognized.
2. Re-entering the license key uses up a new activation. If user has already used their allotted activations, licensing fails to activate app.

I fear this means updating the framework would effectively require a support incident for every single customer, not something anyone wants to do for a minor update.

Is this a known issue? Any work-arounds? I would like to take advantage of the latest updates & fixes, but this makes that impossible.

**Comment by GregularExpressions** [comment]
Hey @markmunz 

Thanks for the report, sorry to hear your beta users are experiencing problems.

If you could email me (greg at paddle dot com) with some example license keys having this issue we'll investigate.

Thanks,
Greg.
