### ISSUE TITLE
How to get the license's expire date

### ISSUE THREAD

**Issue by vicalloy** [PaddleHQ/Mac-Framework#189]
Our license have a expire date. 
We want to display this date in our App.
Have to get the date?

PADDataStore.rootObject!["paddle_expiry"] can get the date, but PADDataStore not published in swift, and can't get child product's expire date.

**Comment by GregularExpressions** [comment]
Hey @vicalloy 

Child products do support license expiry but the date isn't currently exposed, this is also resolved and improved in v4.0.

Thanks,
Greg.
