### ISSUE TITLE
Can I change the default `Allowed number of activations` for license.

### ISSUE THREAD

**Issue by vicalloy** [PaddleHQ/Mac-Framework#195]
The default value of `Allowed number of activations` is `1`.
Can I change the default value(not just for one license)?

**Comment by GregularExpressions** [comment]
Hey @vicalloy, yes you can - it's in the `Set Description, Categories etc...` section for a specific product.

If you're not using trials you'll need to enable them to see the `Default activations per licence` UI and update the default activations - you can disable trials again after if you don't want them.

Thanks,
Greg.

**Comment by vicalloy** [comment]
Thanks, solved.
