### ISSUE TITLE
GDPR Questions

### ISSUE THREAD

**Issue by kolpanic** [PaddleHQ/Mac-Framework#198]
Since you've just released version 3.0.34 with GDPR compliance, I've started updating our macOS apps to use it. From your [documentation](https://paddle.com/docs/gdpr-changes), the update appears quite straightforward. However, I have a couple of questions:

1. We call `Paddle.sharedInstance().setCustomCheckoutAttributes()`, setting the value for `kPADCheckoutEmail` to the user's email address (if it's available), to speed the checkout process. However, AFAIK, we don't use Paddle Audience. Does that mean we should also set the value for `kPADCheckoutMarketingConsent` to `false` in these calls?
2. It looks like the deadline for releasing updates with these changes is May 9, 2018. What happens to people using old versions of our apps after that date?

Thanks.

**Comment by GregularExpressions** [comment]
Hey @kolpanic 

Marketing consent will default to `false` so you only need to amend your implementation to send it if you want to set it to `true`.

Once we begin enforcing GDPR on the 9th we'll default marketing consent to `false` unless expressly supplied or the email is collected through our compliant UI, this is a non-breaking change - older SDK versions will continue to work as before.

The changes are primarily around the audience feature, so the impact to yourselves should be minimal.

Greg.

**Comment by kolpanic** [comment]
Great! Thanks.
