### ISSUE TITLE
Affilate Program signup does not work

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#199]
I just tried signing up as an affiliate for my company to test how the flow works (https://a.paddle.com/join/program/114) and I can't create a new account.

I can only imagine how many potential people are trying to sign up, they can't so they abandon the effort!

This is with Safari 11.1 on macOS 10.13.4. And I don't see any errors in the Safari console when it shows the message that the **fields need to be all filled in**, even though from the screenshot it's clear they are.

<img width="594" alt="screen shot 2018-04-29 at 9 33 41 pm" src="https://user-images.githubusercontent.com/2223932/39413249-92637e10-4bf5-11e8-868f-80ab0f4dc80b.png">

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

Thanks for the report, though technically this isn't a mac SDK issue 🙂vendors@paddle.com is better for this sort of thing in future.

I've forwarded this onto the relevant Product Manager here (James) and he'll be in touch shortly with you directly.

Thanks,
Greg.

**Comment by involer** [comment]
Just for continuity given these were reported here, this (#199) and #200 have been fixed – but as Greg mentions, please submit non-SDK issues through vendors@paddle.com (or the chat in the dashboard).

**Comment by tunabelly** [comment]
@involer I really do appreciate the quick turn-around in getting these fixed. 

For filing future bug reports that are non-SDK related, shouldn't we have a GitHub repo for that (with no code) for keeping the issues public facing? That way us customers of Paddle will know if an issue is already in-progress, if it hasn't been reported, or if it's already been fixed. Is it possible to do this now? Thanks.
