### ISSUE TITLE
Need a license display method

### ISSUE THREAD

**Issue by coneybeare** [PaddleHQ/Mac-Framework#2]
I suggest using `[[Paddle sharedInstance] showLicencing];` to either

1. Show the "need license" popup
2. If already licensed, show the same popup that shows when the user has completed licensing.

That way, any "License..." menu item can either show the already applied license and key, or show the trial license entry screen.

Your current NSAlert of "You are already licensed" is pointless.

**Comment by avalore** [comment]
`[[Paddle sharedInstance] showLicencing];` currently shows the activated license (if it exists) or displays the normal licensing window (if an activated license doesn't exist).
