### ISSUE TITLE
Affilate links have disappeared

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#200]
I had 7 affiliate links I created for people to use. I checked out the updated affiliate dashboard today and only 2 links are there. **What happened to the other 5?** This is not good, especially for new people that have signed up!
<img width="1002" alt="screen shot 2018-04-29 at 9 39 23 pm" src="https://user-images.githubusercontent.com/2223932/39413277-1142f36e-4bf6-11e8-859d-530f542fee0d.png">

**Comment by GregularExpressions** [comment]
See comment on https://github.com/PaddleHQ/Mac-Framework/issues/199
