### ISSUE TITLE
Hide Buy Button on Activate License Window

### ISSUE THREAD

**Issue by kolpanic** [PaddleHQ/Mac-Framework#201]
We've switched one of our apps to a subscription-only business model. In the app there now are only buttons to buy a subscription plan.

To allow customers who bought licenses in the past to re-install the app on a new computer, we have an Enter License button that calls 
`- (void)showActivateLicenceWithWindow:(nullable NSWindow *)window licenceCode:(nullable NSString *)licenceCode email:(nullable NSString *)email withCompletionBlock:(nonnull void(^)(BOOL activated))completionBlock;'`. However, Paddle's license activation window has a Buy button that allows the purchase of a license.

Is there a way to hide or disable the license activation window's Buy button?

(BTW, we're on 3.0.34.)

**Comment by GregularExpressions** [comment]
Hey @kolpanic 

If you call `[[Paddle sharedInstance] setWillSimplifyViews:YES];` before you show the activateLicense UI that should hide that button. It'll also impact some other bits of UI, so you may want to set it back to NO in the completion.

Hope that helps.

Thanks,
Greg.

**Comment by kolpanic** [comment]
Thanks, I'll try that.

**Comment by kolpanic** [comment]
@GregularExpressions I just tried it unsuccessfully. The Buy Now button is still present. I'm using Paddle 3.0.34. Here's a stripped-down version of what I'm doing:
```swift
Paddle.sharedInstance().setPassthrough(paddlePassthrough())
Paddle.sharedInstance().willSimplifyViews = true
Paddle.sharedInstance().showActivateLicence(with: view.window, licenceCode: activateLicenseCode, email: activateEmail) { (activated : Bool) in
   DispatchQueue.main.async {
      Paddle.sharedInstance().willSimplifyViews = false
   }
}
```

![screen shot 2018-05-08 at 10 41 41 am](https://user-images.githubusercontent.com/117055/39764026-a5ecce7e-52ac-11e8-81c8-00bffa333e1c.png)

**Comment by GregularExpressions** [comment]
hey @kolpanic 

Sorry, my bad - you have to call `setWillSimplifyViews:YES` before you call any of the startLicensing variants.

However, this will hide the "buy" and "enter license" buttons from all UI - so maybe doesn't quite do what you need?

Thanks,
Greg.

**Comment by kolpanic** [comment]
@GregularExpressions In that case, can we turn this into an enhancement request for a method that will hide that Buy button before showing the window?

As I mentioned, we've gone subscription-only in _one_ of our apps, but the other still has licenses available.
