### ISSUE TITLE
Customers can't purchase app - Paddle causes app to become unresponsive 

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#202]
This is a HUGE problem. If people can't purchase the app, then what's the point. I'm so frustrated with these types of issues, I'm honestly ready to give up on Paddle. 

And this is with v3.0.34 of the framework. I already reported a similar issue (#197) that is now closed. 

From customer:

> I have tried twice to buy the app using a cc but the app seems to hang and is unresponsive requiring a force quit. I just want to pay - any suggestions?

**Comment by GregularExpressions** [comment]
@tunabelly do you have any more information on the behaviour? or on the user(s) in question please?

**Comment by tunabelly** [comment]
@GregularExpressions thank you.

**Comment by tunabelly** [comment]
@GregularExpressions I don't have any other info other than his email address which I'll send you now so you can get in touch with him. There are no crash reports since he's having to force quit the app.

**Comment by GregularExpressions** [comment]
@tunabelly The user tried another machine and was successful, we didn't receive any other reports so it's hopefully an isolated incident.
