### ISSUE TITLE
Customers loosing licenses after upgrading Paddle 3.0.29 -> 3.0.34.

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#203]
I've had two different customers complain today that after upgrading from TG Pro 2.28 (Paddle 3.0.29) to TG Pro 2.30 (Paddle 3.0.34) they had to re-enter their license keys. And in both cases they were at their activation limits which means **they were locked out of the app they paid for** until I was able to reset the keys. 

And guess who they got mad at? Hint: It wasn't Paddle.

This isn't a new issue and this is probably the 5th time I've filed the same bug report. Do you think we could get a proper fix for this?

**Comment by GregularExpressions** [comment]
@tunabelly you're welcome, no problem.

1. It should only be users coming from older versions like <= 3.0.29 and only the once.

2. I'll raise it again next time we discuss access control but I'm not confident it's where we'll focus our effort in the short term, as there's significant demand for other features.
