### ISSUE TITLE
Crash after purchasing

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#205]
I have at least two users who have submitted crash reports and one added a comment of:

> failed after purchase?

This has got to be the **crappiest user experience to have an **app crash right after paying money**** to purchase it in-app.

[5e8f3395bd0ad65d7c7de1a0305af30d.log.txt](https://github.com/PaddleHQ/Mac-Framework/files/2048643/5e8f3395bd0ad65d7c7de1a0305af30d.log.txt)
[7938b03b7bc21aa62edb9e8b8808d06a.log.txt](https://github.com/PaddleHQ/Mac-Framework/files/2048644/7938b03b7bc21aa62edb9e8b8808d06a.log.txt)

This is with Paddle 3.0.34 and I've attached both crash logs.

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

Thanks for the reports, we agree this isn't an acceptable experience. We've not received any other reports as of yet but we'll investigate urgently.

Thanks,
Greg.

**Comment by tunabelly** [comment]
@GregularExpressions thanks for looking into this promptly. If you need any more info, just let me know.

**Comment by GregularExpressions** [comment]
@tunabelly can you email me the email addresses of the users please, we can use them to find the checkouts and check for anything abnormal.

**Comment by tunabelly** [comment]
@GregularExpressions thanks I appreciate the quick turn-around on this.

**Comment by tunabelly** [comment]
@GregularExpressions any update on when this will be released? We need to do a point release for TG Pro and getting this included would be almost a requirement. Thanks.

**Comment by tunabelly** [comment]
@GregularExpressions guys, when will this be released?

**Comment by GregularExpressions** [comment]
hey @tunabelly we'll get this released by tomorrow, perhaps even today 👍

**Comment by GregularExpressions** [comment]
@tunabelly we've (now) shipped a fix for this in [3.0.36](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.36) let me know how you get on.
