### ISSUE TITLE
-childProductActivated doesn't work

### ISSUE THREAD

**Issue by nightbirdsevolve** [PaddleHQ/Mac-Framework#207]
See screenshot:

![screen shot 2018-06-09 at 00 20 00 copy](https://user-images.githubusercontent.com/528537/41184199-085ab40a-6b7f-11e8-8a90-252b019249c7.png)

**Comment by GregularExpressions** [comment]
Hey @nightbirdsevolve 

This was a race condition around when the completion block is called and it should be fixed in [v3.0.36](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.36).

Let us know if you continue to experience issues.

Thanks,
Greg.

**Comment by nightbirdsevolve** [comment]
@GregularExpressions Sorry but this wasn't fixed in 3.0.36

Also, my fault for not being explicit enough. But the expected result was that calling 
`-childProductActivated` would also return YES in this scenario.

I am using it to check for child product activation (without an internet connection). 
It always returns `NO`, even when I enter a valid user/license pair, and that the online checking method 
`-activateLicence:forChildProduct:withCompletion:` returns `activated == YES` like it should.

So there is some **inconsistency on license validation on the client side.**

⚠️ More importantly, I think the key to my issue is this:

The issue arose after setting up a child product, which had erroneously been set to expire after 3 days (dunno why that is the default, had I been more careful, i would have unchecked that initially).

It seems that the client-side verification technique `-childProductActivated` worked fine while the license was under the 3 days limit.
When the limit was reached, I went to the paddle vendor back-office and turned off the expiry date for both the specific licence and globally.

But since, even when calling `-activateLicence:forChildProduct:withCompletion:` to try and undo that change, `-childProductActivated` won't be satisfied anymore…

**Comment by nightbirdsevolve** [comment]
@GregularExpressions Side note: thanks for your previous effort and rapid feedback on the issue. It's appreciated.

**Comment by GregularExpressions** [comment]
@nightbirdsevolve we think this might be a separate issue to do with child product expiry dates as you've suggested. We'll investigate 👍

**Comment by nightbirdsevolve** [comment]
@GregularExpressions thank you! The running feature is already causing a furious amount of negative feedback emails amongst customers, hope that can be fixed swiftly. — Ben

**Comment by GregularExpressions** [comment]
hey @nightbirdsevolve I think part of the confusion here is that updating the license expiry rule(s) for a product won't be propagated to existing licenses - it'll only be applied to new ones.

The expiry date is only stored at time of activation, so just amending them on the dashboard (even for the existing licenses) won't take effect on it's own.

Effectively, we need to get any "expired" end users to re-activate with a license that hasn't expired. Either because it's been newly issued or it's their existing one with the expiry removed.

If you've implemented deactivate then your users can use that to reset their state and be able to activate again, assuming we amend all the expired issued licenses to not have an expiry.

If you have semi-frequent `verify` calls then deactivating the license(s) on the vendor dashboard will cause them to be removed on a verify call. This would probably need twinning with the issuing of a new license, so the end user doesn't need to wait for their license to be re-activated before they can activate.

Does that make sense?

**Comment by nightbirdsevolve** [comment]
@GregularExpressions the last bits I didn't get entirely. But I understand the issue (and I had assumed that expiry date wasn't updated on the client).

Wouldn't it be way simpler to just update the expiry date locally when calling `-activateLicence:forChildProduct:withCompletion:` ?

Please note, that in my test:
- Doing the deactivate/activate dance (testing on my machine) did not prove successful.
- Generating a new license for the child product did not prove successful either…

**Comment by GregularExpressions** [comment]
@nightbirdsevolve 

> Wouldn't it be way simpler for you to just update (or dismiss) the expiry date locally on every call to -activateLicence:forChildProduct:withCompletion: ?

This is what _should_ be happening, however expiries run from the time of purchase - not activation so that might be confusing things.

> Doing the deactivate/activate dance (testing on my machine) did not prove successful.
> Generating a new license for the child product did not prove successful either

Deactivating and then re-activating with a new license without an expiry date didn't work?

**Comment by nightbirdsevolve** [comment]
@GregularExpressions 

> Deactivating and then re-activating with a new license without an expiry date didn't work?

Just re-tried, and no, it won't work anymore.
`-activateLicence` works fine and returns `activated == YES`, but a succeeding call to `-childProductActivated` will still return NO.

**Comment by GregularExpressions** [comment]
hey @nightbirdsevolve just a quick update to let you know we are still looking into this.

**Comment by nightbirdsevolve** [comment]
Thanks @GregularExpressions , update appreciated :)

**Comment by nightbirdsevolve** [comment]
@GregularExpressions 👍🏼 congrats on hunting down this issue. Looking fwd to v3!
