### ISSUE TITLE
10.14 Dark Mode Issue

### ISSUE THREAD

**Issue by pixeleyesltd** [PaddleHQ/Mac-Framework#208]
![screen shot 2018-06-16 at 9 50 58 am](https://user-images.githubusercontent.com/246345/41491031-e3b0f138-714a-11e8-89de-43e8334c8627.png)

**Comment by adriangranados** [comment]
Do you guys have an updated timeline for when Paddle will support Mojave? Mojave's release is just around the corner. My app is ready for Mojave, including support for Dark Mode, but I don't want to publish the update until Paddle is ready too. Thanks!

**Comment by GregularExpressions** [comment]
Hey @adriangranados,

v3 and the imminent v4 of the mac SDK support Mojave, however only v4's UI supports dark mode (because of the differences in UI implementation between v3 and v4 it's much easier).

v4 does also have some conceptual differences (for flexibility and ease of use mostly), it's not a straight drop in replacement, so we're working to get this out as soon as possible to give everyone the most amount of time between v4 launch and Mojave's October likely public release. At the moment we think at least another week or two.

Thanks,
Greg.

**Comment by kolpanic** [comment]
@GregularExpressions As we discussed, moving to v4 is non-trivial for us and won't be happening soon. However, we do expect v3 to at least be usable on Mojave when the user has dark mode turned on. I'd suggest forcing any windows to have a regular Aqua appearance on 10.14 regardless of the user's preference.

**Comment by adriangranados** [comment]
When I asked if Paddle was ready I really meant if it had been modified to properly support Mojave's dark mode either by fixing the UI for when running in dark mode or forcing the regular appearance regardless of which mode is set. 

Same as @kolpanic, I don't think I'll jump into the v4 boat right away once it's released, so please consider looking on an alternative solution to properly display Paddle v3 window(s) in Mojave's dark mode.

Thanks.

**Comment by pixeleyesltd** [comment]
I agree - jumping into v4 this late would be a bad idea for most developers. It shouldn't be difficult to programatically change the window appearance to Aqua. The other views should inherit the appearance, as they are doing right now with dark mode.

I'd rather v4 was not released in a hurry to meet the Mojave release date, that seems like a project risk to me. Release it when it's ready to be released, and test it thoroughly to avoid migration issues 🙂

**Comment by GregularExpressions** [comment]
Thanks @adriangranados, @kolpanic, and @pixeleyesltd for your feedback - we will make sure that v3 doesn't have any broken / ugly / unexpected UI behaviour on Mojave 👍

**Comment by pixeleyesltd** [comment]
Can confirm this is fixed in the latest release. Thanks!
