### ISSUE TITLE
crash in -[PADLicence verifyLicence:activationId:productId:withCompletionBlock:]

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework#209]
a customer is complaining that our product is crashing on each launch (during paddle verification):

it didn't occur for him in 3.0.31 but does in 3.0.35 and 3.0.36

 Details: data parameter is nil data parameter is nil (null) (
0 CoreFoundation 0x00007fff2bd0132b __exceptionPreprocess + 171
1 libobjc.A.dylib 0x00007fff52e6bc76 objc_exception_throw + 48
2 CoreFoundation 0x00007fff2bd92dcd +[NSException raise:format:] + 205
3 Foundation 0x00007fff2ddc03db +[NSJSONSerialization JSONObjectWithData:options:error:] + 67
4 Paddle 0x000000010a957592 __71-[PADLicence verifyLicence:activationId:productId:withCompletionBlock:]_block_invoke + 274
5 CFNetwork 0x00007fff2aba08fb __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
6 CFNetwork 0x00007fff2aba0155 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147
7 Foundation 0x00007fff2dd935df __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
8 Foundation 0x00007fff2dd93441 -[NSBlockOperation main] + 68
9 Foundation 0x00007fff2dd918ee -[__NSOperationInternal _start:] + 778
10 libdispatch.dylib 0x00007fff53a4bdb8 _dispatch_client_callout + 8
11 libdispatch.dylib 0x00007fff53a5e33e _dispatch_block_invoke_direct + 317
12 libdispatch.dylib 0x00007fff53a4bdb8 _dispatch_client_callout + 8
13 libdispatch.dylib 0x00007fff53a5e33e _dispatch_block_invoke_direct + 317
14 libdispatch.dylib 0x00007fff53a5e1e1 dispatch_block_perform + 109
15 Foundation 0x00007fff2dd8d8fc __NSOQSchedule_f + 342
16 libdispatch.dylib 0x00007fff53a4bdb8 _dispatch_client_callout + 8
17 libdispatch.dylib 0x00007fff53a5ee81 _dispatch_continuation_pop + 472
18 libdispatch.dylib 0x00007fff53a56733 _dispatch_async_redirect_invoke + 703
19 libdispatch.dylib 0x00007fff53a4d9a9 _dispatch_root_queue_drain + 515
20 libdispatch.dylib 0x00007fff53a4d755 _dispatch_worker_thread3 + 101
21 libsystem_pthread.dylib 0x00007fff53d9d169 _pthread_wqthread + 1387
22 libsystem_pthread.dylib 0x00007fff53d9cbe9 start_wqthread + 13

**Comment by GregularExpressions** [comment]
hey @core-code thanks for the report, apologies for the inconvenience - we'll look into it. Can you please email me greg at paddle dot com any information you have about the user please, at least their license code would be great.

Thanks,
Greg

**Comment by core-code** [comment]
update: the user says our official build with Paddle 3.0.35 crashed every time on launch, but the private build with Paddle 3.0.36 apparently crashed only on the first time but works now. 

i was unable to find the e-mail he has used to purchase but will forward it to the mentioned e-mail address as soon as he provides me with this information.

thanks for looking into it.

**Comment by GregularExpressions** [comment]
hey @core-code we made some additional thread safety changes in 3.0.36, perhaps they've resolved the problem? Please let us know if this user continues experiencing this issue, as our investigation didn't turn up anything interesting.

**Comment by core-code** [comment]
thanks we'll update to 3.0.36 for the next release, i'll let you know if it occurs again.
