### ISSUE TITLE
Paddle support needs to provide support

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#210]
I'm getting a bit frustrated (again) with Paddle support. Some customer choose to email them before they contact us and when it's an app specific issue, Paddle support rightfully includes us in the reply so we can help the customer.

However, when the issue is with the Paddle service, you'd think that Paddle support would deal with it (and maybe cc us to keep us in the loop). But no, they bounce the customer to us, and we have to bounce them back to Paddle support, which is a terrible user experience. 

For example, in the last few days, we've had two customers, one with an issue where the Paddle framework would loose the license key, and another where he wants to know how to activate without an Internet connection (or if it's even possible). Both times, Paddle support forwarded their emails to us when they should have answered the question and included us if necessary.

So please pass on this to however needs to see it since there's no way to file bug reports for anything other than the framework.

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

I can pass this on to the relevant team(s), do you know which of our two support teams these instances were with? If the end user initiated the support request then it was probably our Buyer/Order support team?

Thanks,
Greg.

**Comment by tunabelly** [comment]
@GregularExpressions I believe it would have been simply help at paddle dot com. And thanks for passing that on, I hope it makes a difference.

**Comment by tunabelly** [comment]
@GregularExpressions here's a good example of a customer that just emailed me:

> The replies from Paddle are apparently automated and not related to the specifics of the problem. The reply bot they use doesn't have a very large repertoire of solution suggestions. and the correspondence has been useless. It's like talkihg to a wall.

**Comment by tunabelly** [comment]
And now I've lost money by having to give a refund to the above customer since Paddle was absolutely no help in helping him figure out why he was getting an error when trying to activate our app.

So the end result is one unhappy customer and no sale.

**Comment by GregularExpressions** [comment]
thanks @tunabelly I'll talk to the buyer support team about how we can avoid the above and let you know.
