### ISSUE TITLE
How to activate when doing a remote install

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#211]
I have a potential customer that would like to deploy one of our apps across about 100 Macs using a remote install tool. That part I can take care of, but how would we automate the licensing for each Mac? 

We can't have the end users to it themselves and need some type of automated way to do it, whether it's something on the command line, etc.

**Comment by tunabelly** [comment]
@GregularExpressions any suggestions or comments on this?

**Comment by GregularExpressions** [comment]
hey @tunabelly this isn't _technically_ supported but there are some workarounds - I'll email you directly.
