### ISSUE TITLE
Customers cannot activate on macOS 10.7

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#213]
I've had two users in the last few days who are complaining they cannot activate the apps they purchased. The common factor is they are running macOS 10.7 and both of them get a dialog saying there was an SSL error.

One of these customers was the one I mentioned in #210 who gave up and I had to refund because Paddle support didn't offer any real help to him.

I've attached screenshots of the error and of system info for one of the Macs.
![screen shot 2018-07-09 at 8 06 41 pm](https://user-images.githubusercontent.com/2223932/42858471-caadbae6-8a1c-11e8-918d-9825cf84c979.png)
![screen shot 2018-07-10 at 9 06 01 pm](https://user-images.githubusercontent.com/2223932/42858472-cabe7db8-8a1c-11e8-9993-fad4f2c205dd.png)

Is the Paddle framework no longer supported on 10.7? If so, what's the minimum OS version now and when did this change?

**Comment by GregularExpressions** [comment]
Hey @tunabelly just to confirm, we weren't able to find any workarounds for the TLS EOL on macOS versions Apple hasn't patched - so effectively the minimum version is now 10.9.

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

I appreciate that this is inconvenient and that it'll generate some support - we did take some steps to try and make it less painful.

We wrote a [blog post](https://paddle.com/blog/deprecating-tls-1.0-1.1/) back in March where we tried to be clear on the situation:

> From this date, any buyers using older operating systems or browsers will no longer be supported. Buyers on these older systems will have to upgrade to a newer platform to be able to shop online. This change will be enacted by all online merchants, not just Paddle.

Between the blog post and the deadline we ran 3 TLS 'brown outs' where we disabled 1.0 and 1.1 to help Sellers (and us) identify where there might be problems.

Finally, just before the deadline we updated our [changelog](https://new.paddle.com/turning-off-tls-1-0-and-1-1-64355) to let Sellers know we'd now disabled the TLS versions permanently.

Naturally there is always more we could've done but when we examined our traffic Buyers impacted by this represented quite a small percentage (~0.3%).

Let me know if we can be of any further help

Greg.

**Comment by tunabelly** [comment]
@GregularExpressions thanks for the update and for the extra info. I have no objection to turning off TLS 1.0 / 1.1 for security reasons. It's just something that I figured Paddle would communicate directly to vendors through an email campaign, alert on the dashboard, or whatever. 

Critical changes to the infrastructure need to be directly communicated to vendors. Even an email with a link to the blog post and a clear statement that support for 10.7 & 10.8 will end would have been great. 

It's not the support issue I have with my customers, it's that they can't use the app they paid for. Yes most people are on > 10.9 but I do have a few that use it on 10.7 still and I've mislead them by saying it's supported.

In the future if Paddle is going to be dropping support for a version of macOS (which I'm ok with) **please communicate this clearly and directly to vendors**. Thanks.

**Comment by tunabelly** [comment]
@GregularExpressions if you'd like you can close the ticket since I don't believe there's anything else left to do now. Thanks.

**Comment by GregularExpressions** [comment]
hey @tunabelly appreciate the feedback, I understand where you're coming from.
