### ISSUE TITLE
32-bit / Universal Binary version?

### ISSUE THREAD

**Issue by adamski** [PaddleHQ/Mac-Framework#215]
Hello

Can you provide a Universal Binary version of Paddle so I can link it to a Universal Binary VST plugin? Otherwise I cannot support 32-bit hosts, which many people still use for backwards compatibility with older plugins.

Thanks

**Comment by GregularExpressions** [comment]
Hey @adamski 

We've investigated this and it looks like the engineering work required to produce a 32 bit version of our framework is significant - especially as it appears we'd have to disable ARC and go back to manual reference counting!

Given that Apple are dropping support for 32 bit apps entirely after Mojave we're struggling to justify allocating the time at the moment.

Thanks,
Greg.
