### ISSUE TITLE
Paddle support still isn't providing support

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#218]
I filed a ticket about this, #210 (which is now closed) and it's still a problem.

I wanted to let you know that nothing has really changed. I got an email forwarded from Paddle from a customer who didn't know how to get their license key for one of the apps they purchased (it was a bundle with 2 Mac apps). So instead of providing it to her, they sent her to us. And guess where I found the license key for her? From the PADDLE dashboard.

This is wasting a lot of our time and needlessly frustrating paying customers.

**Comment by tunabelly** [comment]
To follow up, I just got another email from **Paddle support** the other day with a customer that was having trouble activating the app he just got. So instead of **Paddle support** helping the customer to activate the app and tell him how to get his license key and how to enter it into the **Paddle licensing dialog**, they just forwarded it to us. 

A very crappy user experience for the paying customer.

**Comment by GregularExpressions** [comment]
Hey @tunabelly apologies for this, I've spoken to Buyer Support and they're going to look at how they can amend their training to better handle this case to try and avoid it in future.
