### ISSUE TITLE
Customers have to enter license key after every restart (Paddle 3.0.39)

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#227]
I have two separate customers that are complaining they have to enter their license key into TG Pro after every single restart of the Mac. I thought this was resolved but it seems it's not. 

This is super frustrating that I have upset customers again.

I've cc'ed both Paddle support and @GregularExpressions for both customers so you guys can fix this for them.

**Comment by GregularExpressions** [comment]
Thanks @tunabelly, we'll investigate.

**Comment by tunabelly** [comment]
Thanks @GregularExpressions . I just got another one and I've forwarded you his info as well.

**Comment by tunabelly** [comment]
@GregularExpressions one of the customers has been trying since July, 2018 to get a resolution from Paddle and he's beyond frustrated. Every time he restarts his Mac, TG Pro goes back to trial mode because of bug in the Paddle framework.

I don't know what else to tell him because he's not getting the help from Paddle that he needs.

**Comment by tunabelly** [comment]
@GregularExpressions I just had another customer with the same issue. He managed to figure out that when using a **regular macOS account**, the license would not be stored properly. When using an **admin account**, it was stored properly.

So this may help you guys to figure out how to fix this properly.

**Comment by GregularExpressions** [comment]
@tunabelly thanks for letting us know! We'll add to our investigation.

**Comment by tunabelly** [comment]
@GregularExpressions I have yet another customer with the same issue and I've cc'ed you with this details. 

Also his original email was to Paddle support and they simply **bounced him to us** even though **it's an issue with the Paddle service!** This level of "support" is sure to piss off customers.

**Comment by GregularExpressions** [comment]
@tunabelly do you have any idea how many of these users are using site licensing and/or are "normal" users on their machines?

Our theory is that it is a file write permissions issue, especially in the case of site licensing as it is outside of the user's home directory.

One immediate step to try is to add a custom entitlement to the app(s) in question:

`com.apple.security.temporary-exception.files.absolute-path.read-write` with the key `/Users/Shared/`.

In the meantime we're going to look at how we can better handle file system complications like this, likely including some kind of delegate call so it becomes easier to handle this more gracefully in the cases where we can't recover (on both v3 & v4 where applicable).

**Comment by tunabelly** [comment]
@GregularExpressions they are all using the site licensing since it's for [TG Pro ](https://www.tunabellysoftware.com/tgpro/). It has the site licensing enabled in the code.

I'm not sure how adding that custom entitlement would help since the app is not sandboxed.

The faster you guys can fix this the better since it seems every week I have another customer emailing to complain about this. So I imagine there are other people having the same issue but haven't taken the time to email about it yet.

**Comment by tunabelly** [comment]
@GregularExpressions got yet **another** customer running into this issue with the Paddle framework.  He's actually upset enough that he's asking for a refund unless I can provide a way to fix this. 

Unfortunately this is out of my hands (otherwise I would have fixed it by now), so this is going to cost us lost revenue.

I've included your email in the reply to him so hopefully there's something this time you can get that will fix it for good.

**Comment by tunabelly** [comment]
@GregularExpressions I just **got a support email from another customer with the same problem**!! Come on, why can't this be fixed?

I'm looking really stupid since people assume it's a quality-control issue with our code.

**Comment by GregularExpressions** [comment]
@tunabelly [v3.0.40](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.40) has some changes to help with this.

If we're unable to write to the shared storage location (for site licensing) then we'll fall back to normal per user activation, this should prevent the repeated activation loss these users are experiencing.

We also log more info to console if it occurs, to help with further diagnosis on the cases where the above is insufficient.

**Comment by tunabelly** [comment]
@GregularExpressions thank you for including this fix into 3.0.40, this will be a huge help with increasing customer satisfaction.

**Comment by tunabelly** [comment]
@GregularExpressions this appears to be fixed from the customer feedback. I'm so happy this is finally resolved!
