### ISSUE TITLE
Update v3 SDK to migrate away from NSData for local license verification (ref. Catalina Fix)

### ISSUE THREAD

**Issue by rishimodha** [PaddleHQ/Mac-Framework#231]
related: https://github.com/PaddleHQ/Mac-Framework/issues/230

v4 SDK has been updated for this, please apply a similar fix for v3.

**Comment by kwokaaron** [comment]
Please see https://github.com/PaddleHQ/Mac-Framework/issues/230#issuecomment-538349543
