### ISSUE TITLE
Mac OS X Snow Leopard Support

### ISSUE THREAD

**Issue by 1951FDG** [PaddleHQ/Mac-Framework#29]
I have tested several versions and have confirmed that [v1.6](https://github.com/PaddleHQ/Mac-Framework/commit/b684ec709b0cce91a7c2bc079cbe60407ad1b91b) is the latest version to support Snow Leopard. Has Snow Leopard support been officially dropped? It would be helpful if the documentation could make a note of this.

Will earlier versions, such as v1.6 be guaranteed to continue working? Is testing performed on earlier versions to ensure that they are currently not broken? Must one always use the latest version provided, what is the current policy?

**Comment by 1951FDG** [comment]
Status update? Also, what is the current minimum os x version required for the latest version?

**Comment by 1951FDG** [comment]
Is it true, that Product ID's have changed, and newly created products ID's are incompatible with v1.6 of the framework which uses a previous version of the API? Is it still possible to create product ID's compatible with v1.6? When will the API used in v1.6 of the framework, cease to function? Will we be notified? How?

**Comment by involer** [comment]
v1.6 of the SDK will not be updated except for critical fixes, and is currently the most recent version of the SDK to support OS X 10.6

The current version of the SDK supports OS X 10.7+.

v1.x of the SDK will be deprecated at some point, however we have no clear plans on when this will happen.

**Comment by 1951FDG** [comment]
What about the product ID's? Is it still possible to create new products with product ID's compatible with v1.6?

**Comment by involer** [comment]
Yes, if you create a product within your dashboard and then raise a ticket from within your account we can supply the old-style IDs that will work with the legacy SDK and APIs.

**Comment by 1951FDG** [comment]
Ok, thanks for the info.
