### ISSUE TITLE
Click link to register app

### ISSUE THREAD

**Issue by henderea** [PaddleHQ/Mac-Framework#38]
There are some apps that provide a link/button that you can click to open up the app and register it automatically.  You obviously have to have the app installed first, and you might have to have opened it at least once before.

It would be really cool if Paddle supported this sort of thing.  I think it is done with a special URL scheme, so the way I envision it would be that the prefix would be specified in the framework call and in the dashboard.  Ideally the link would be to a regular page on paddle.com that then forwards to the special URL scheme, since in the Gmail web interface it doesn't support clicking on the special URLs.

This is definitely just a "nice to have", so I'm not expecting it to be done anytime soon, but it would be great if you could implement something like this when you have some time.

**Comment by involer** [comment]
This is in the planned roadmap.
