### ISSUE TITLE
Create a cocoapod for the framework

### ISSUE THREAD

**Issue by henderea** [PaddleHQ/Mac-Framework#39]
It would be nice if there were a cocoapod spec for the paddle mac framework.  It would make it much easier to keep up with the latest version and would allow me to remove the paddle framework from my source control.

You can find more information on cocoapods at <http://cocoapods.org/>.

Also, it would make it easier to integrate my RubyMotion gem motion-paddle (<http://rubygems.org/gems/motion-paddle>) into my projects if I didn't have to embed the framework in the source control of each one.

**Comment by avalore** [comment]
The latest release is now available as a Cocoapod.
```
platform :osx, '10.7'
pod "Paddle", "~> 2.2.x"
```
