### ISSUE TITLE
Obfuscate user defaults

### ISSUE THREAD

**Issue by coneybeare** [PaddleHQ/Mac-Framework#4]
````
$ defaults read com.urbanapps.simplescrobbler
{
    Paddle =     {
        MPSecureUserDefaultsHash = [REDACTED];
        MPSecureUserDefaultsValue = [REDACTED];
    };
    PaddleAPICheck = "1383660228.098098";
    PaddleApiKey = [REDACTED];
    PaddleEmail = [REDACTED];
    PaddleProductKey = [REDACTED];
    PaddleVendorKey = [REDACTED];
    "current_price" = "2.99";
    "default_image" = "AppIcon.icns";
    "developer_name" = "Urban Apps";
    "discount_line" = "";
    "on_sale" = 0;
    "payment_url" = "https://checkout.paddle.com/pay/92530-59d5bc9419f4a3c-60d1fcdb18";
    "price_currency" = USD;
    "product_image" = "http://paddle-static.s3.amazonaws.com/product-icons-new/framework/SimpleScrobbler-Icon.png";
    "product_name" = SimpleScrobbler;
    "trial_text" = "Thanks for trying out SimpleScrobbler!";
    "usual_price" = "2.99";
}
````

I noticed that my license key was stored in plain text under `MPSecureUserDefaultsValue`. Also, there is a ton of identifiable information in here, noted above by [REDACTED]. This seems like a major security breach, along with the values stored by paddle for the other entries. Perhaps storing them in the keychain would be better? Or, if stored here, obfuscate them somehow, perhaps with an (XOR of a known secret) to prevent clear text identifiable info in the user default.

It also brings up a security concern on the topic of software piracy. I am not an app pirate so I am unsure of how one might go about this exactly, but it seems that storing licensing data in the `NSUserDefaults` has generally been recommended as a no-no. Couldn't a hacker just pause execution, change these values at the right time, then hack in? Can you give me confidence that an app licensed by paddle will be secure enough for release?

**Comment by avalore** [comment]
NSUserDefaults is no longer used for product data as of v2.2
