### ISSUE TITLE
showLicensing is showing "null" as app name

### ISSUE THREAD

**Issue by tjosten** [PaddleHQ/Mac-Framework#41]
![screen shot 2015-02-01 at 17 36 29](https://cloud.githubusercontent.com/assets/807586/5992805/12686a92-aa39-11e4-9b47-4685223bb411.png)

Haven't changed any code, just updated to the most recent version of your Framework. Happens on both 10.9 and 10.10. I'm unable to post the update of my app because of this issue.

**Comment by involer** [comment]
We're looking into this issue now, have sent you an in-app message within your Paddle Dashboard asking for more information, could you reply there?

**Comment by avalore** [comment]
The latest release (v2.2.1) with improved migrations resolves this issue.
