### ISSUE TITLE
For activated app, startLicensing doesn't return kPADContinue or kPADActivated

### ISSUE THREAD

**Issue by BrainFeverMedia** [PaddleHQ/Mac-Framework#42]
For an application that is already activated, startLicensing doesn't show anything or return kPADContinue or kPADActivated notifications.

I know there's a method [[Paddle sharedInstance] productActivated], but the SDK instructions state that startLicensing must be called before productActivated.

If a product is activated, startLicensing should post a notification, or at least return a BOOL if it's going to show a dialog or not.  Doing nothing is not useful.

Thanks!

**Comment by 1951FDG** [comment]
I knew of this issue a while ago, I eventually came up with a workaround (see last comment of https://github.com/PaddleHQ/Mac-Framework/issues/32)

I agree that with you that if a product is activated, startLicensing should post a notification, but why this is not the case is not clear to me.

**Comment by BrainFeverMedia** [comment]
@1951FDG Thanks for replying. Yeah, I'm doing a workaround for this but wanted to enter a specific issue to get this fixed. A dialog either needs to display and/or return something, not do nothing for a very common use case, i.e. product is activated.

**Comment by 1951FDG** [comment]
@BrainFeverMedia StartLicensing does post a notification if the product is activated. You may have committed the same mistake I made, you should register an observer to receive notifications for kPADActivated before startLicensing.

@avalore Please update the [documentation](https://www.paddle.com/docs/sdk/trials-licensing) and under heading **Showing the Licensing Window before MainWindow**, make a mention of the following:

You should register an observer to receive notifications for either kPADContinue or kPADActivated **BEFORE** calling startLicensing.
