### ISSUE TITLE
Alert on successful license key could have nicer wording.

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#43]
After a customer registers a valid license key, they are presented with an alert with the message:

"License is valid. Thank you."

IMHO, it could say something a little less technical, like "Thank you for registering <app name>.".  I would skip mentioning anything technical about the license key.

**Comment by involer** [comment]
This makes sense, I'll add a note for the next release to have this changed to something friendlier.

**Comment by avalore** [comment]
v2.2.1 has changed this to "Thank you for registering."
