### ISSUE TITLE
Is there a way to reset trial period in development environment?

### ISSUE THREAD

**Issue by kaishin** [PaddleHQ/Mac-Framework#44]
I am trying to test app behavior during and outside the trial period. Is there a way I can reset the trial period locally? I have cleaned the build folder but that doesn't seem to have any effect.

![screenshot-2015-02-13](https://cloud.githubusercontent.com/assets/519433/6190458/62802296-b3a2-11e4-9115-6f9339a5b6f6.png)

**Comment by avalore** [comment]
As long as the app is running from Xcode you can simulate the reset of a trial by setting a key in the NSUserDefaults for your app. For example, from terminal:
`defaults write your.app.bundle.identifier PaddleResetTrial -bool YES`
This will reset the trial period for your app.

Similarly you can accelerate a trial period (any trial length expires in 15 minutes) by setting a different key:
`defaults write your.app.bundle.identifier PaddleAccelerateTrial -bool YES`

You should set these keys before running your app.

**Comment by kaishin** [comment]
Thank you @avalore. This doesn't seem to have any effect. Is this documented more in detail somewhere?

The key is properly added to the app identifier, but I am still getting *0 days remaining*. I added it using `defaults` from the command line.

Any hints of how I can debug this?

**Comment by avalore** [comment]
Are you using v2.2.1 of the framework? This has only just been added.

**Comment by kaishin** [comment]
@avalore Yes, I am: 
![screenshot-2015-02-16-4](https://cloud.githubusercontent.com/assets/519433/6212887/540c9a4c-b5ea-11e4-89c2-e88e98273340.png)

**Comment by bradjasper** [comment]
I'm not sure if this is related, but since 10.10 I've had to `killall cfprefsd` when editing most defaults to clear the cache.

**Comment by kaishin** [comment]
@bradjasper I just tried that without avail.

**Comment by avalore** [comment]
Are you using the `setApiKey:` `setVendorId:` and `setProductId:` methods or the old style `startLicensing` with api, vendor and product ids as parameters?

**Comment by kaishin** [comment]
@avalore Here's how the code is currently set up:

```swift
private func setupPaddle() {
    let paddle = Paddle.sharedInstance()
    paddle.setProductId("xxx")
    paddle.setVendorId("xxx")
    paddle.setApiKey("xxx")
    let bundle = NSBundle.mainBundle()
    let imagePath = bundle.pathForImageResource("xxx")
    
    let productInfo = [
      kPADCurrentPrice : "xxx",
      kPADDevName : "xxx",
      kPADCurrency : "xxx",
      kPADImage : imagePath!,
      kPADProductName : "xxx",
      kPADProductImage : "xxx"
      ] as [NSObject : AnyObject]
    paddle.startLicensing(productInfo, timeTrial: true, withWindow: nil)
  }
```

**Comment by kaishin** [comment]
I changed the vendor ID (unrelated to this issue), cleaned the build, reset the defaults cache and it's finally working!

Thanks @avalore and @bradjasper.

Is there something I can remove from the code snippet above?
