### ISSUE TITLE
Need a way to override the price from the app

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#46]
I have a need for certain customers that they can purchase the app at a reduced price.  This set of customers is determined at runtime.

For example, if the app is normally $10, I'd like to be able to override the price from the app and say for this specific user, it's $5.  So when they go to purchase inside the app, they get the reduced price.

There doesn't seem to be a way to do this since the prices are always determined by the Paddle server and not the app itself.

**Comment by involer** [comment]
This is planned functionality that we're hoping to have ready for the next release. Will keep this ticket open and update with more details when we have them/ when this is released.

**Comment by involer** [comment]
Resolved in recent SDK build.
