### ISSUE TITLE
Exception in [PAKQueue sendEvents:]

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#47]
I just got this exception:

2015-03-02 09:48:12.113 HandsFree 2[17227:1101562] Invalid type in JSON write (__NSCFData)
2015-03-02 09:48:12.116 HandsFree 2[17227:1101562] (
	0   CoreFoundation                      0x00007fff8d1d266c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff826e776e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8d1d251d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff8220917a _writeJSONValue + 715
	4   Foundation                          0x00007fff8220d74f ___writeJSONObject_block_invoke + 220
	5   CoreFoundation                      0x00007fff8d0fcec6 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 102
	6   CoreFoundation                      0x00007fff8d0fcdd9 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 217
	7   Foundation                          0x00007fff8220d33f _writeJSONObject + 439
	8   Foundation                          0x00007fff82209096 _writeJSONValue + 487
	9   Foundation                          0x00007fff8220d74f ___writeJSONObject_block_invoke + 220
	10  CoreFoundation                      0x00007fff8d0fcec6 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 102
	11  CoreFoundation                      0x00007fff8d0fcdd9 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 217
	12  Foundation                          0x00007fff8220d33f _writeJSONObject + 439
	13  Foundation                          0x00007fff82209096 _writeJSONValue + 487
	14  Foundation                          0x00007fff8220d62b ___writeJSONArray_block_invoke + 130
	15  CoreFoundation                      0x00007fff8d0f3385 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 133
	16  CoreFoundation                      0x00007fff8d0f2a89 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 313
	17  Foundation                          0x00007fff8220d540 _writeJSONArray + 277
	18  Foundation                          0x00007fff822090e3 _writeJSONValue + 564
	19  Foundation                          0x00007fff82208e7a -[_NSJSONWriter dataWithRootObject:options:error:] + 137
	20  Foundation                          0x00007fff8220b9c5 +[NSJSONSerialization dataWithJSONObject:options:error:] + 345
	21  Paddle                              0x00000001002edb60 -[PAKQueue sendEvents:] + 336
	22  Paddle                              0x00000001002ed13d -[PAKQueue processQueue] + 1197
	23  Foundation                          0x00007fff82069db3 __NSFireTimer + 95
	24  CoreFoundation                      0x00007fff8d125b64 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	25  CoreFoundation                      0x00007fff8d1257f3 __CFRunLoopDoTimer + 1059
	26  CoreFoundation                      0x00007fff8d198dbd __CFRunLoopDoTimers + 301
	27  CoreFoundation                      0x00007fff8d0e2288 __CFRunLoopRun + 2024
	28  CoreFoundation                      0x00007fff8d0e1858 CFRunLoopRunSpecific + 296
	29  HIToolbox                           0x00007fff88c3baef RunCurrentEventLoopInMode + 235
	30  HIToolbox                           0x00007fff88c3b86a ReceiveNextEventCommon + 431
	31  HIToolbox                           0x00007fff88c3b6ab _BlockUntilNextEventMatchingListInModeWithFilter + 71
	32  AppKit                              0x00007fff8e3bff81 _DPSNextEvent + 964
	33  AppKit                              0x00007fff8e3bf730 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194
	34  AppKit                              0x00007fff8e3b3593 -[NSApplication run] + 594
	35  AppKit                              0x00007fff8e39ea14 NSApplicationMain + 1832
	36  HandsFree 2                         0x000000010002b5fb main + 27
	37  libdyld.dylib                       0x00007fff80e5b5c9 start + 1
	38  ???                                 0x0000000000000003 0x0 + 3
)

I know that's not a whole lot to go off, although it is with Paddle 2.2.1 if that helps.

**Comment by tunabelly** [comment]
I think the markdown is messing up the stack trace, so here's a photo just in case.
![screen shot 2015-03-02 at 9 51 55 am](https://cloud.githubusercontent.com/assets/2223932/6442975/c7e87d3c-c0c1-11e4-9217-0bd07e517c3e.png)

**Comment by avalore** [comment]
We've added further validation to analytics data in v2.2.2, which should resolve this issue.
