### ISSUE TITLE
The IAP overlay looks a little buggy

### ISSUE THREAD

**Issue by tjosten** [PaddleHQ/Mac-Framework#49]
![screen-shot-2015-04-08-16-23-02](https://cloud.githubusercontent.com/assets/807586/7047230/957544c2-de0b-11e4-9c19-9cc187accb09.png)

This does not look like it should. :)

Reproducible: 

```
PaddleStoreKit *psk = [PaddleStoreKit sharedInstance];
[psk setDelegate:<delegate>];
[psk showProduct:<product_id>];
```

Select product, and you will see the screen above.

**Comment by involer** [comment]
Thanks for reporting this – we'll get right on it. :) It'll be a remote fix and will automatically apply to your app when resolved.
