### ISSUE TITLE
PaddleResetTrial is not working with debug build in Xcode

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#51]
I'm launching an app that I'm just about to release with a Paddle version, and I need to reset the trial (for testing).  I followed the docs with:

defaults write com.tunabelly.foldertidy PaddleResetTrial -bool YES

Yet, when I launch a debug build in Xcode, I see in the console:

2015-05-12 12:41:46.671 Folder Tidy[5174:323245] Warning: resetTrial should not be called in production apps
2015-05-12 12:41:46.677 Folder Tidy[5174:323245] Warning: resetTrial should not be called in production apps
2015-05-12 12:41:46.681 Folder Tidy[5174:323245] Warning: resetTrial should not be called in production apps

**Comment by avalore** [comment]
Is your app running from Xcode (attached to the debugger) or are you running it directly? The warning isn't indicative of anything going wrong, it's just to make sure it doesn't make it into production.

**Comment by tunabelly** [comment]
It's running from Xcode (attached to the debugger).  It's not reseting the trial, so I figured the output might be related to it.
![screen shot 2015-05-12 at 11 04 02 am](https://cloud.githubusercontent.com/assets/2223932/7593968/aaad1bde-f8ab-11e4-8262-db7faa326a38.png)

**Comment by tunabelly** [comment]
It's running from Xcode (attached to the debugger). It's not reseting the trial, so I figured the output might be related to it.  This is what I'm seeing:
![screen shot 2015-05-12 at 1 34 16 pm](https://cloud.githubusercontent.com/assets/2223932/7594005/e4a33666-f8ab-11e4-9317-5f7df0321d64.png)

**Comment by avalore** [comment]
Ah, interesting, is the app set to run as a time trial? (timeTrial:YES)

**Comment by tunabelly** [comment]
Yes, it's set as a 3 day trial.
