### ISSUE TITLE
Licensing window has no shadow in OS X 10.11

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#54]
Not sure if it's an issue with the Developer Preview of 10.11 (El Capitan) although I figured it's worth mentioning in case it's something that needs to be updated in the Paddle SDK.
![screen shot 2015-06-08 at 6 02 50 pm](https://cloud.githubusercontent.com/assets/2223932/8046628/7a4cd028-0e0a-11e5-9af8-89cb33f717f8.png)

**Comment by InerziaSoft** [comment]
Same here, on Golden Master (OS X 10.11 (15A282b)). This is definitely something that must be fixed before the release of El Capitan.

![screen shot 2015-09-28 at 12 21 18](https://cloud.githubusercontent.com/assets/2380018/10133147/754ceb20-65db-11e5-9b20-34c42edd8261.png)

**Comment by tunabelly** [comment]
This is still happening with the retail release of 10.11.

**Comment by paddleharrison** [comment]
Hey Matt, 

This was fixed in the latest SDK update (2.3.5). Are you using this version of the SDK?

**Comment by tunabelly** [comment]
Harrison you correct! This is indeed fixed with Paddle 2.3.5. Thanks for checking up on this.
