### ISSUE TITLE
Update PodSpec and git tags

### ISSUE THREAD

**Issue by henderea** [PaddleHQ/Mac-Framework#58]
The PodSpec still says 2.2.6, even though the git repo is at 3.3.1.  You should update the PodSpec and deploy it to CocoaPods.

You should also create git tags for 3.3.0 and 3.3.1.  Part of how I know that a new version is out is from the emails I get when a tag is made.  I do also check the repo on GitHub from time to time, but it would be best to have git tags and an updated PodSpec.

**Comment by digitalmoksha** [comment]
I agree, please update the cocoapod.  This is how i'm including the framework, and it would be great to be using the latest version.

**Comment by henderea** [comment]
@digitalmoksha Actually, if you're using Paddle via my `motion-paddle` RubyMotion gem, it takes the pod directly from this git repo, so the podspec version and release tags don't matter as long as the changes are committed to this repo (which they have been).
