### ISSUE TITLE
Trial window is way off center

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#59]
See screenshot.
<img width="1280" alt="screen shot 2015-08-15 at 4 18 48 pm" src="https://cloud.githubusercontent.com/assets/2223932/9290672/6a15c6bc-4369-11e5-8112-d28d79cc52a2.png">

**Comment by tunabelly** [comment]
This is still occurring with Paddle framework 2.3.7.

If anyone would like a workaround, I've developed this:

- (void)centerLicenseWindow
{
	NSWindowController *productWC = (NSWindowController *)[Paddle sharedInstance].productWindow;
	if ([productWC respondsToSelector:@selector(window)] == YES)
	{
		[productWC.window center];
	}
}

Use it after a call to showLicencing or startLicensing.

**Comment by tunabelly** [comment]
This is still occurring with Paddle framework 2.3.7.

**Comment by tunabelly** [comment]
I'm still seeing this with Paddle 2.3.9 and it looks really bad as the first thing people see when opening TG Pro.  Is there a way to center the window and work around this?

Thanks guys!

**Comment by tunabelly** [comment]
This is still occurring with Paddle 3.0.13. Having the trial window be off-center is not a good way to introduce the app to potential customers. It makes it look like amateur hour.
<img width="790" alt="screen shot 2017-01-16 at 5 33 58 pm" src="https://cloud.githubusercontent.com/assets/2223932/22001316/25e70e86-dc12-11e6-8bf4-7f84118a45cb.png">

**Comment by avalore** [comment]
Hey @tunabelly - just to confirm, when the window isn't attached would you expect it to be centred to the screen or to your main window?

**Comment by tunabelly** [comment]
Since there might not be a main window to center it on, I would expect it to be at least centred on the screen if no window is passed in (or that window is not visible). And if a visible window is passed into the call to startLicensing then I would imagine it's always centered on that.

**Comment by tunabelly** [comment]
Is there a specific fix that was put into the Paddle framework to resolve this? And which version has the fix?

**Comment by GregularExpressions** [comment]
@tunabelly No fix per-say, thus far we've been unable to replicate and we've not received any other reports, are you able to replicate consistently? Would you be able to supply us with a sample project we could use to debug?

Thanks,
Greg.
