### ISSUE TITLE
Analytics (http 80) connection fails on 10.11

### ISSUE THREAD

**Issue by binaryghost** [PaddleHQ/Mac-Framework#63]
I may be mistaken but I believe the in the current SDK, connections to analytics.paddle.com fail when running on 10.11 because it is an HTTP connection not using SSL. Xcode displays an error and I believe it is because of App Transport Security. Per Apple Documents:

All connections using the NSURLConnection, CFURL, or NSURLSession APIs use App Transport Security default behavior in apps built for iOS 9.0 or later, and OS X 10.11 or later. Connections that do not follow the requirements will fail. https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/

Attached is an image of the http call in question.

![screen shot 2015-09-10 at 6 05 26 pm](https://cloud.githubusercontent.com/assets/619955/9803447/538dce24-57e8-11e5-8e28-6f44b2a8f574.png)

**Comment by avalore** [comment]
Hey, are you definitely on the latest version (2.3.3)? This version should resolve this issue, with all connections being over https.

**Comment by binaryghost** [comment]
That was the issue. My mistake!
