### ISSUE TITLE
Trial window doesn't dismiss on OS X 10.11

### ISSUE THREAD

**Issue by bradjasper** [PaddleHQ/Mac-Framework#66]
Have gotten a few reports of the trial window not dismissing properly.

Have been able to reproduce it on 10.11 Beta (15A279b)

Customer that experienced it was on 10.11.1 (Build 15B22c)

* "Continue Trial" does nothing, window does not dismiss
* "Enter License" does allow entering license info, but window doesn't dismiss. On reboot the app is registered properly & licensing window isn't shown as expected
* "Buy Now" goes to custom buy window, but licensing window doesn't dismiss

**Comment by tunabelly** [comment]
I also have seen this on 10.11.

**Comment by bradjasper** [comment]
Looks like this is still happening with the 2.3.6 release. I've sent a video of the issue to Harrison to explain it in a bit more detail.

**Comment by avalore** [comment]
v2.3.7 fixes this issue now.
