### ISSUE TITLE
Customers need a way to find lost license keys

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#67]
Another area that takes up a lot of support time is finding license keys for customers that have lost them.  I'm able to look them up based on their email address and send it to them although it takes time when I have 50 a month to do.  

There needs to be a way where they can go to a webpage, somehow authenticate that they are who they say they are and get their license keys for any products purchased through that email address.

**Comment by bradjasper** [comment]
Agreed—sending licenses is a huge percentage of my support requests. If there was a way the customer could do this themselves it would dramatically help.

**Comment by involer** [comment]
We're currently working on a new version of `my.paddle.com` that's focused on order lookup and license recovery regardless of if the user has a Paddle account, it'll also contain an embeddable widget as part of the new `Paddle.js` (the successor to our current Overlay Checkout/ `Checkout.js`). Both of these should be here before the end of October.

**Comment by tunabelly** [comment]
That would be fantastic. Just to clarify, this would mean I could embed the widget in a support page for people to look up their licenses without having to go to another page - is that correct?

**Comment by involer** [comment]
The embed would be for your support page, and would be a 'license lookup' form. It'd send the user an email, to the address they type into the form, clicking on the link in the email reveals a page allowing the user to access all past orders (with invoices) for that email, and licenses associated with the email. (As well as download links if you have that info specified for your product within Paddle).

**Comment by tunabelly** [comment]
Ok, that's perfect! I'm excited to give this a try once it's ready.

**Comment by tjosten** [comment]
@involer what's the status of this?

**Comment by involer** [comment]
@tjosten We actually released an internal API for this yesterday. Widget and tools for integrating into your website, and support area(s) will be available within the week.

**Comment by tunabelly** [comment]
I would love to have this available. Looking up and sending license keys is eating up I'd say about 50% of the time I spend on support.

**Comment by tjosten** [comment]
@involer any update?

**Comment by tunabelly** [comment]
@involer any update on this? Having to look up lost license keys is still the #1 issue for my support emails.

**Comment by tjosten** [comment]
@avalore anyone?

**Comment by involer** [comment]
Hi All – We're very close on a solution for this.

We're working on two methods, one in the instance that you can store a value relating to the transaction your side. If you have the scope to do this, a solution is available now (note we'll need to provide you with this value historically to make your system work).

The second is a self-service method of users doing this themselves with email address confirmation etc...

If you're currently storing a database of transactions from Paddle on your side, please email me: christian@paddle.com and I can get you setup with docs for the beta of this immediately.

If you're not currently doing that, then the solution will be available and documented within the next 4-5 days.

Apologies for the delay on this.

**Comment by tjosten** [comment]
Hi @involer,

any update?

**Comment by dokterdok** [comment]
> a self-service method of users doing this themselves with email address confirmation etc...

Hi, any update about this one? 
Lost or unreceived license keys is the #1 recurring request that we get from our customers. Offering a self service page e.g. via a widget that we can add on our site would be terrific.

**Comment by tunabelly** [comment]
This ticket is well over a year old now. I'm sure there's something we can use to help our customer look up license keys? It's still eating up a ton of our support time.

**Comment by tjosten** [comment]
What bugs me is that you guys keep promising stuff "by the end of the week", however we get no feedback here. Please be transparent.

**Comment by bradjasper** [comment]
100% agree with the other comments here. This is by far my #1 support issue, and I've heard multiple times this is right around the corner.

**Comment by involer** [comment]
Hi all,

I wanted to give you an updated on progress here.

We initially sought to address this with the addition of our Post-Checkout API that allows the retrieval of order information and license codes based on the 'Checkout ID' which is available within webhooks sent by Paddle. (Documentation Here:
 [Post-Checkout Order API.pdf](https://github.com/PaddleHQ/Mac-Framework/files/577846/Post-Checkout.Order.API.pdf))

After trailing this method with a number of developers, it seems that this wasn't a solution workable by everyone – and most didn't have the desire to import Checkout ID data for historical sales, or in some cases weren't maintaining their own database of transactions.

We've been working on a new method of providing this functionality, this will consist of the following:

* An API, embeddable form and methods within Paddle.js that allow for placing of a license/order lookup form on your own website, or in-app.
* This API/form will accept a customer email address.
* Upon entering an email address, the customer will be sent a confirmation email to access their licenses and purchases.
* Clicking on a button/link within the email will take them to a page on the Paddle website listing Orders, Licenses and Subscriptions.

In the future we also plan to make this page/portal brandable and embeddable into your own website, as well as the addition of addition support tools and functionality to enable Paddle to take more of this scope away from you as developers.

A screenshot below:
<img width="799" alt="screenshot 2016-11-08 10 06 31" src="https://cloud.githubusercontent.com/assets/664790/20094888/1c2cd0a4-a59b-11e6-9c12-e5ae8602d272.png">

We're actively working on this, it is our goal to get this released in the month of November, and we're currently shooting for a release before the Black Friday/Cyber Monday customer support spike.

**Comment by bradjasper** [comment]
Looks like a good solution @involer—the admin looks nice but the form+email functionality are the most important pieces. Any chance to get those sooner?

**Comment by involer** [comment]
@bradjasper The form/email functionality links directly to the page on the web. We looked at a solution that re-sent licenses directly via email, but had too many instances of customers having lots of purchases per vendor, that didn't make this feasible. (In our testing we had various instances where customers had upwards of 10 licenses/purchases for a single vendor – which meant summary emails which would be truncated by email clients, or sending multiple emails for a single request).

**Comment by tunabelly** [comment]
Any idea when this will be released? November has come and gone. In fact, so has December as well. This ticket is over 14 months old. This is still one of our biggest time sucks when dealing with customer support issues. 

What's going on with the holdup? I think we would all understand if there was more transparency as to what the progress/status is. Or even if there was a beta we could use with the idea that it might not work 100% properly.

**Comment by dokterdok** [comment]
Actually, it looks like users have a way of recovering their license codes themselves. They have to register on https://my.paddle.com to access a locker which includes all of their Paddle order receipts etc. I wasn't aware of this and am not sure for how long it's been there, but thank you @involer !

We've built a canned response around this which reduces our support workload.

**Comment by OskarGroth** [comment]
The my.paddle is unrelated to this issue and has been available for a long while.
It is not a solution to direct our customers to another website asking for registration.
In most cases, the simplicity of the Paddle overlay checkout prevents customers from understanding that the purchase is made through Paddle and they have no clue what Paddle is or why I'm asking them to go register with them.

@involer: The feature promised looked great but seems abandoned. Any reason for this? I'm well into my second year as a Paddle merchant and this has been my No.1 desired feature since joining.
Right now I'm directing customers to Paddle support to get their license and I receive furious replies that they didn't get a reply for days.

Creating this feature would relieve merchants, Paddle Support, and most importantly Customers of a lot of emails, hassle, language barriers, confusion, anger and dissatisfaction.

**Comment by tunabelly** [comment]
@OskarGroth I agree, this is also our No.1 feature request for Paddle. And we're also finding if we re-direct customers to Paddle support, they do get an answer (which is good) although it takes a few days (which is bad). It's frustrating for a customer, especially if their license key is used up and they need a reset - which they are unable to do themselves. Or if they can't find the license key and need the software working asap.

@involer - This feature has been in development for 1.5 years. We saw a preview from 6 months ago and it was looking promising. All we need is an embeddable widget where customers can look up their license keys and if they could reset them too that would be a bonus (just like in iTunes where it deactivates all previous installations).

**Comment by ktraunmueller** [comment]
@involer I am currently evaluating Paddle against Fastspring, and the handling of this issue doesn't help to increase confidence in Paddle. Can you share more details on what the outcome of this month-long process is?

**Comment by adriangranados** [comment]
I'm going to jump in here too and kindly ask for this feature to be delivered as soon as possible. 

Going through the thread it appears there's been suggestions to use a portal (my.paddle.com), however, I don't think that's they way it should be done. As @OskarGroth mentioned, customers don't need to know what Paddle is, nor they should care. The way this should work is by using some sort of a form that let users enter their email address to receive a message with their license key (or deactivate it), for example.

So, please, can we get any feedback on this?
Thanks!

**Comment by tunabelly** [comment]
I'm with @adriangranados, getting some feedback of when this will be available is essential.

**Comment by involer** [comment]
Our intention is to ship the API version of this (very similar to @adriangranados comment), within the next 3 weeks.

**Comment by adriangranados** [comment]
Ok, thanks!
Keeping an eye on it.

**Comment by tunabelly** [comment]
@involer we're almost at the 3 week mark. Any update on this? It's getting very frustrating to repeatedly answer support emails for lost/full license keys when we could be working on other things.

**Comment by involer** [comment]
@tunabelly (and others) we have a beta of the license recovery API/email flow which we shipped today, this will be available in Paddle.js and the SDK + a web based API later this week, but we're looking for a few people who might be interested in helping us test the beta in production.

The APIs will be available publicly later this week, or early next – but anyone interested in trying the beta first and giving some feedback would be most welcome. Please email co@paddle.com if you'd like to try it.

**Comment by tunabelly** [comment]
@involer thanks for the update. I just sent an email saying I'd like to try it out on our support webpage and see how it goes. Will it allow customers to reset a license key (like iTunes where it deregisters old activations/hardware) ?
