### ISSUE TITLE
In-app credit card purchases are not working on OS X El Capitan

### ISSUE THREAD

**Issue by dokterdok** [PaddleHQ/Mac-Framework#70]
We can't get credit card payments to work for in-app purchases on OS X 10.11 (15A284 public release). We get an endless spinning wheel in the payment screen. No confirmation email, no transactions are recorded on the credit card, and no activation is done.

I just tried multiple times on two different El Capitan machines, connected to different ISPs, with different credit card brands (Visa + MasterCard). Tested with Paddle frameworks 2.3.0, 2.3.4 and 2.3.6. No success.

Note: I've tested PayPal on El Capitan, credit card on Website checkout, credit card on Yosemite, and 100% rebate coupons, all these seem to work OK.

Any idea what's going on?

**Comment by involer** [comment]
We're sporadically seeing this here, however payment volume is at a normal level for in-app purchases, so it doesn't appear to be affecting a significant portion of users.

Could you try adding an ATS exception for `core.spreedly.com` in your `Info.plist` file. See here for an example: <https://mobile.awsblog.com/post/Tx2QM69ZE6BGTYX/Preparing-Your-Apps-for-iOS-9>

**Comment by dokterdok** [comment]
Thanks for the swift reply. ```core.spreedly.com``` is indeed related the issue and we've identified the cause. Let me know if you need more info and how I can reach you in that case as I prefer not to post potentially sensitive debug info publicly.

**Comment by involer** [comment]
We're working with the folks at Spreedly with this one. They're migrating their certificates to SHA-2 on November 1st, which resolves the issue. We recommend keeping the ATS exception in place in production builds until then. I'll update this ticket to confirm when Spreedly have updated their certificates on Nov 1st.

**Comment by avalore** [comment]
The ATS exception for spreedly should not longer be needed for this to function correctly.
