### ISSUE TITLE
paddle framework needs NSAllowsArbitraryLoads /  NSAppTransportSecurity exception under el capitan

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework#73]
App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

**Comment by involer** [comment]
Do you know which resource is being attempted to be loaded?

**Comment by core-code** [comment]
i suspect the URL given to kPADImage was contacted, which has been provided with HTTP

**Comment by core-code** [comment]
indeed the icon (in the purchase view) is only loaded if i add the exception.

however, paddle does not try to contact my provided server url, but amazonaws instead

**Comment by 1951FDG** [comment]
@core-code While reading the [docs](https://www.paddle.com/docs/sdk/setup),   it mentions the issue and how to attempt to solve it:

Amazon S3 doesn't currently support ATS so you should add an exception to your project for product images to load correctly. [Amazon ATS Details](http://mobile.awsblog.com/post/Tx2QM69ZE6BGTYX/Preparing-Your-Apps-for-iOS-9).

Please provide feedback, thanks.

**NOTE**: App Transport Security (ATS) is on by default in OS X v10.11 and iOS 9.

**Comment by involer** [comment]
It should be noted that we are in the process of migrating to an alternate CDN that will resolve these issues. We'll update this ticket when that is rolled out.

**Comment by avalore** [comment]
These ATS exceptions should not be required any longer.
