### ISSUE TITLE
Licensing window has no shadow in OS X 10.11 after deactivating

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#74]
After deactivating a license (using Paddle 2.3.9 framework), the registration dialog that appears has no shadows.  It looks pretty odd.
<img width="538" alt="screen shot 2015-12-06 at 9 23 52 pm" src="https://cloud.githubusercontent.com/assets/2223932/11617664/192f4318-9c60-11e5-93b3-e826f5ac8e98.png">

**Comment by 1951FDG** [comment]
Same issue here (using Paddle 2.4.1 framework). Shadows appear the first time the registration dialog is shown. If the registration dialog is shown again, it is shown with no shadows!

**Comment by tunabelly** [comment]
This bug report is from late 2015. Turning the shadow back on for the window should be really simple (unless there's something more than normal that needs to be done).

This is a crappy user experience and it looks like our apps are the ones messing up.

**Comment by tunabelly** [comment]
This is still happening on macOS 10.12.5 using Paddle 3.0.19. I'm surprised this is still happening as I'm guessing it's a fairly simple fix to the window attributes.

**Comment by tunabelly** [comment]
@GregularExpressions this is still an issue with macOS 10.12.5 and Paddle 3.0.20.

![screen shot 2017-06-22 at 11 19 15 am](https://user-images.githubusercontent.com/2223932/27441862-b8a8130a-573c-11e7-8229-a43f71b390d8.png)

**Comment by avalore** [comment]
Thanks, we're getting on top of these and cleaning up. We'll investigate.
