### ISSUE TITLE
Crash in setObjectForKey:

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#76]
Quite a few customers are seeing this crash on app startup.

This is with Paddle SDK 2.3.7.
[a547d3f89998b42b7524ddd194a34af7.log.txt](https://github.com/PaddleHQ/Mac-Framework/files/60041/a547d3f89998b42b7524ddd194a34af7.log.txt)

**Comment by avalore** [comment]
Thanks, we'll look into this. Does your app use the `+ (void)identify:(NSString *)identifier;` method on `PaddleAnalyticsKit` at all?

**Comment by tunabelly** [comment]
I just checked and it doesn't use that method anywhere. Thanks for looking into this.

**Comment by avalore** [comment]
Great thanks. It seems to be down to MAC address collection.
Is there any pattern in terms of OS X version, machine model, etc for these customers?

**Comment by tunabelly** [comment]
Here's what's showing:

MacBookPro8,3 10.9.5
MacBookAir7,2 10.10.5
MacBookPro8,1 10.11.0
MacBookAir6,2 10.11.1
iMac11,1 10.11.2

**Comment by jessegrosjean** [comment]
I'm not sure, but this looks like a crash that I'm seeing. It happens anytime:

1. The application is unlicensed.
2. The application is launched without network access. (or with some network proxy/firewall that gets in way, I don't know correct terms here)

Can you reproduce it under those conditions?

**Comment by avalore** [comment]
Thanks for the feedback on this. This turned out to be down to some instances of OS X not returning a MAC address, which has now been resolved as of v3.0.0
