### ISSUE TITLE
Docs needs to be updated (the Paddle framework requires WebKit)

### ISSUE THREAD

**Issue by 1951FDG** [PaddleHQ/Mac-Framework#77]
[SDK: Basic Setup](https://www.paddle.com/docs/sdk/setup) makes no mention of WebKit. The Paddle framework requires WebKit to be included. **Step 3** of [Basic Setup](http://docs.paddle.com/article/76-basic-setup) (older docs) has been omitted and should be included in [SDK: Basic Setup](https://www.paddle.com/docs/sdk/setup) (newer docs). This is a rather very important step, which can not be omitted.

**Comment by avalore** [comment]
Thanks for the feedback, it's not immediately obvious. It's included in the screenshot on the new docs website but we'll clarify this further on the next update as well.
