### ISSUE TITLE
Text in licensing window buttons is not vertically centred

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#82]
The "Buy Now" text in the button looks especially bad.
<img width="479" alt="screen shot 2016-06-07 at 9 18 30 pm" src="https://cloud.githubusercontent.com/assets/2223932/15879839/8d1b480a-2cf5-11e6-9509-e3d2e2557fc2.png">

**Comment by henderea** [comment]
3.0.1 says it fixes text alignment in buttons.  Have you tested if the issue is fixed?  I haven't upgraded my app to 3.x yet, and I think I'll probably wait for some issues to be sorted out.

**Comment by avalore** [comment]
We've fixed this issue in 3.0.1
