### ISSUE TITLE
verifyLicenceWithCompletionBlock should have option to only delete a license if it's verified as invalid

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#85]
I tried using the verifyLicenceWithCompletionBlock, along with shouldDestroyLicenceOnVerificationFail (YES) and failedAttemptsBeforeLicenceDestruction (10) and it seems to be destroying a lot of legitimate licenses.  I've had quite a few customers who are fairly angry that now the app is saying it's back to trial mode right after updating to the latest version.

What should be an option is to only destroy the license if the Paddle framework successfully connects with the mothership and verifies that it's not a real license.  Otherwise, if a real paying customer doesn't have an Internet connection, their license will be destroyed after X number of failed attempts at reaching the Paddle mothership.

For now, I'm going to have to back this out since it's causing too many destroyed licenses for paying customers.

**Comment by avalore** [comment]
This method does only delete a license if it's determined to be invalid, it looks like the API is identifying some activations as invalid.

Would you be able to email over any details of a customer that's had this issue and we'll look into it?

**Comment by tunabelly** [comment]
I just emailed you a few of the email addresses of customers where their licenses where deleted.

**Comment by avalore** [comment]
3.0.2 fixes this issue, which was related to activations made using a much older version of the SDK. These licenses will not longer be removed and users won't be asked to re-enter their license details.
