### ISSUE TITLE
Clarification - if framework fails to connect to Paddle will license be destroyed?

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#86]
Just to clarify, if the remote validation is used and for some reason, the Paddle framework can't connect to its servers, will the license still be destroyed when it reaches the max number of tries returned by the delegate?

**Comment by avalore** [comment]
When it reaches the max number of attempts yes. The default maximum is 75 if you haven't set it

**Comment by tunabelly** [comment]
How often will it attempt? I'm thinking of a situation where a customer might not have an Internet connection for a period of time.

**Comment by avalore** [comment]
The only time the SDK will make an attempt on it's own is if it detects an older license, which it will try to verify and migrate to the new format. This happens on app start - or whenever you normally call `startLicensing`.

After this it won't be called automatically at all so you are free to call verify whenever you think it's appropriate.

**Comment by tunabelly** [comment]
Ok, that makes sense. Thanks for the clarification, I appreciate it.
