### ISSUE TITLE
Add ability to customize the deactivate license message.

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#87]
This is what's shown right now - it would be nice to allow the option to provide a more detailed message to the user.
<img width="532" alt="screen shot 2016-06-20 at 10 56 53 am" src="https://cloud.githubusercontent.com/assets/2223932/16198993/fa7798e2-36d5-11e6-891d-71a8ae96bb2b.png">

**Comment by avalore** [comment]
If you implement the `- (void)licenceDeactivated:(BOOL)deactivated message:(NSString *)deactivateMessage;` delegate method, the default alert won't be shown so you can show your own alert with a custom message

**Comment by tunabelly** [comment]
Awesome, thanks. I totally missed that!
