### ISSUE TITLE
Is there a way to show a custom dialog when the app is activated?

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#89]
Simliar to the - (void)licenceDeactivated:(BOOL)deactivated message:(NSString *)deactivateMessage delegate method to show a custom alert when the app is deactivated, is there one for when it's activated?

I tried using the - (void)licenceActivated delegate method and it still shows the regular Paddle alert.

**Comment by avalore** [comment]
This now works the same as `licenceDeactivated`, so if the `licenceActivated` delegate is implemented it will not show the standard alert as well.
