### ISSUE TITLE
productActivated should be KVO-able property and not a method

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework#9]
so we directly bind the visibility of user interface items to the property instead of having to bridge things manually in the controller by calling productActivated and observing kPADActivated

**Comment by core-code** [comment]
all the things that obviously should be properties still aren't. and its 2018.

**Comment by GregularExpressions** [comment]
Hey @core-code 

The incoming v4 of the SDK greatly improves this, products will each be their own object with their own properties -  giving you much more flexibility.

An internal alpha is due imminently, you should hear more in the next few months.

Thanks,
Greg.

**Comment by core-code** [comment]
sounds great!
