### ISSUE TITLE
Crash in [PaddleStoreKit:showStoreView]

### ISSUE THREAD

**Issue by adriangm20** [PaddleHQ/Mac-Framework#90]
The following calls to show the IAP store view are crashing:

`PaddleStoreKit *psk = [PaddleStoreKit sharedInstance];`
`[psk setDelegate:self];`
`[psk showStoreView];` // crashes

Also, these other variations are crashing: 

`[psk showStoreViewForProductIds:@[@"id1", @"id2"]]; // crashes`
`[psk showStoreViewForProductType:PSKConsumableProduct]; // crashes`

The error I'm getting is:

2016-07-12 16:48:21.873 WiFi Explorer[8936:426030] An uncaught exception was raised
2016-07-12 16:48:21.873 WiFi Explorer[8936:426030] *** setObjectForKey: object cannot be nil (key: product_id)
2016-07-12 16:48:21.876 WiFi Explorer[8936:426030] (
	0   CoreFoundation                      0x00007fff9a7024f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8e482f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9a5fc414 -[__NSDictionaryM setObject:forKey:] + 1236
	3   Paddle                              0x0000000100403414 +[PADUtilities urlRequestWithParameters:andMethod:] + 932
	4   Paddle                              0x0000000100414829 -[PSKStoreWindowController windowDidLoad] + 585
	5   AppKit                              0x00007fff860e1927 -[NSWindowController _windowDidLoad] + 592
	6   AppKit                              0x00007fff8607e43e -[NSWindowController window] + 110
	7   Paddle                              0x00000001003fac20 -[PaddleStoreKit showStoreViewForProductType:] + 336
	8   WiFi Explorer                       0x00000001000b4579 -[WEActivationHelper showAddons] + 121
	9   WiFi Explorer                       0x0000000100041328 -[AppDelegate onAddons:] + 88

Note that is complaining about a null product id even though the method doesn't require one or it is being provided (as an array of IDs).

**Comment by avalore** [comment]
Hi Adrian, have you called `[[Paddle sharedInstance] setProductId:@"..."];` (as well as `setVendorId` and `setApiKey` before using PaddleStoreKit?

**Comment by adriangm20** [comment]
Yes. Everything is working fine in version 2.4.4. It breaks when I switch to version 3.0.3.
