### ISSUE TITLE
Restore purchases prevents app from quitting

### ISSUE THREAD

**Issue by adriangranados** [PaddleHQ/Mac-Framework#94]
When using the "restore purchases" PSK API, if the connection that goes to analytics.paddle.com is blocked (using Little Snitch, for example), then only a modal spinning icon centered in the app's window is shown and cannot be dismissed. As a result, nothing can be done further and one cannot quit the app.

**Comment by avalore** [comment]
Thanks @adriangm20 will look into it and get resolved for next release.

**Comment by adriangm20** [comment]
This issue is actually very easy to reproduce. Just use "recoverPurchases" with no internet connection and you get the modal spinning wheel.
