### ISSUE TITLE
Need a way to destroy license if and only if it's invalid 

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#96]
Currently, the option to destroy a license on failed verification will do so even if it's not sure of this but the attempts fail (ex: no Internet connection).  Even with the option to set the number of attempts, this causes too many destroyed licenses for customers who have valid licenses but for whatever reason, it couldn't connect to Paddle (security software, no Internet connection, etc).

Having the option to destroy the license **if and only if** there is a successful connection to Paddle and the license is invalid would be extremely helpful.  Because right now, we can't reliably use this.

**Comment by avalore** [comment]
In `3.0.9` you can implement the delegate method `- (BOOL)onlyDestroyLicenceOnVerificationFail;` returning `YES` to only destroy a license on a hard verification fail (it will ignore the number of attempts and connectivity state).

**Comment by tunabelly** [comment]
Thank you for adding this!
