### ISSUE TITLE
What's the isSiteLicensed property for?

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#97]
There's a property called "isSiteLicensed" in the Paddle class.  I wasn't able to find any documentation on this. Is there an option somewhere to create a site license key?  If so, that would be really, really awesome.

**Comment by avalore** [comment]
Currently there aren't any site license keys but you can set `isSiteLicensed` to `true` which will store a license for the machine rather than just the current user.

**Comment by tunabelly** [comment]
Just to double check, if I set this to true will it resolve the issue where customers have to activate for every user on their Mac?                                                                                                                                                                        Sent from my BlackBerry Priv                                                                                                                                                                                                                   From:notifications@github.comSent:August 15, 2016 5:13 AMTo:Mac-Framework@noreply.github.comReply-to:reply@reply.github.comCc:matt@tunabelly.com; author@noreply.github.comSubject:Re: [PaddleHQ/Mac-Framework] What's the isSiteLicensed property for? (#97)  Currently there aren't any site license keys but you can set isSiteLicensed to true which will store a license for the machine rather than just the current user.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by avalore** [comment]
That's right, however if there is already a license for the user it will not be picked up - the user will need to re-enter a license but then it will be licensed for every user on that machine.

**Comment by tunabelly** [comment]
I'd like to verify this before I turn it on in the next app update - if I set **isSiteLicensed** to **true** will every customer who already has the app activated get prompted to re-enter their license?
