### ISSUE TITLE
Use better wording in activate failed dialog

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#98]
Right now, if a customer puts in an incorrect license key and attempts to activate, the dialog that appears says "Sorry - Unable to find requested license". 

If I was a customer, I wouldn't really understand what that's referring to since I'm not trying to look anything up.  I'm trying to activate the app I just purchased. 

Perhaps something along the lines of "Sorry - The license key entered is invalid."

**Comment by avalore** [comment]
@involer This is an API side message.

**Comment by tunabelly** [comment]
Ok, so is it possible to file an issue with the API side team? It would be nice to have a clearer error message for customers.
