### ISSUE TITLE
Multiple german Localization issues

### ISSUE THREAD

**Issue by Iomegan** [PaddleHQ/Mac-Framework#99]
_Paddle v.3.0.8._
Looking at the window that tells the user how long to he or she can use the application until the trial time is expired, there are three issues:
1. The word "Nach" is completely wrong. It has to be "Von". Everything else makes no sense at all.
2. The "Probezeit fortsetzen" (Continue trial) is too long for the button. I can't think of a shorter german phrase, so the button has to get bigger.
3. Long company names get cut off, although there should be enough space.

<img width="490" alt="bildschirmfoto 2016-08-18 um 21 05 23" src="https://cloud.githubusercontent.com/assets/1634465/17771960/75128c38-6589-11e6-9627-b20c263f71d6.png">

**Comment by Iomegan** [comment]
![bildschirmfoto 2016-09-21 um 11 09 00](https://cloud.githubusercontent.com/assets/1634465/18694312/4e1d932a-7fec-11e6-8aa4-56fe38d38b46.png)
Hope this is still on the list. At the moment hat window looks quite unprofessional. 

Cheers

**Comment by Iomegan** [comment]
Please fix this. Should take 10 minutes. :)

**Comment by avalore** [comment]
We have this fixed on the next release due to be out later this week :)

**Comment by Iomegan** [comment]
version 3.0.13 - still the same issues. :(
